### ISSUE TITLE
Write and adopt first by-laws

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#101]
## Shared Description

:speaking_head: **Loomio:** https://loomio.hypha.coop/d/5akByK9O/agm-preparations-by-laws-etc-  
:date: **Due date:** by first AGM
:dart: **Success criteria:** drafted and reviewed bylaws to take into AGM.  

## To Do

- [x] seek sample/model by-laws. [tweet.](https://twitter.com/ComeAsYouAreCo/status/1168607236106719232)
  - [x] [CAYA worker co-op](https://drive.google.com/file/d/0B2riIxpG2GHET3dCSE9fa0VSZGhrWFcxcEhBZ2g5aTl0d2ln/view?usp=sharing) :lock:
  - [x] [model by-laws of NS worker co-op](https://canadianworker.coop/model-worker-co-op-bylaws/) (CFWC)
  - [x] [list of model governing docs](https://www.uk.coop/resources/model-governing-documents) (Cooperatives UK)
    - "Worker Co-operative Society Model" is closest to a not-for-profit
- [x] [draft by-laws](https://docs.google.com/document/d/1QN8QzmSnnj1GoxybuuFqJoquUtqUEPdX4PRPfchWQFg/edit)
   - [x] initial draft
   - [x] review by gov working group:
       - [x] session 1: membership
       - [x] session 2: meetings, elections, directors
       - [x] session 3: financials, operating
   - [x] dc: review and modify draft based on research below and for AGM requirements
       - articles, voting, indemnification
- [x] @hyphacoop/finance-wg review Section 6+7 Surplus and Finance sections 
- [x] present for members comment with agenda package - June 5
- [x] June 10 all hands discussion on bylaws -- request to review
- [x] June 6-12 commenting / feedback on bylaws (set up in loomio pre-meeting)
- [x] Updates and prep for June 13 AGM
- [x] Adopt bylaws at AGM

**Comment by patcon** [comment]
## Proposal

Here's my proposal for how to break this down: (this should perhaps be in Loomio. was thinking could migrate if contentious -- messages seem easy to miss in there, and overly private.)

- [x] migrate NS worker co-op model by-laws to GDocs. [done.](https://docs.google.com/document/d/16CF4HazkQRypXWAwvDtgxeynXLdjj3aDdZMXNOFYlIw/edit)
- [ ] Migrate annotations verbatim into inline comments
- [ ] create a copy (to share back or with others)
- [ ] we make comments for general updates, based on
  - updates over time (e.g., 2009 Ontario amendments), and
  - across regions (NS => ON)
- [ ] we make a copy
- [ ] we start making customized comments/suggestions based on our own desires and inspirations from other co-op by-laws (Canada & US) and rulesets (UK)
- [ ] finalize draft -- undetermined future date before AGM
- [ ] approve at AGM

Sounds like a good start? Anyone have feedback or other ideas for approach? cc

---

## Considerations

- :heart: I feel that there's a reasonable argument that by-laws aren't our most urgent priority. (I say that proactively, not because I've heard it said.)
- :mag: Accountant candidates (incl Hema) have already made recommendations of things that should be in our by-laws.
- :bulb: Let's at least get a baseline draft up, so we can start marking it up with things we learn/hear.

**Comment by patcon** [comment]
As someone reading through others' by-laws, thinking that a **changelog** would be nice.

Yes, we'll have a git history (eventually), but it would be a neat precedent to have it in the official by-laws themselves for when it's printed/shared as a doc.

[one sample format.](http://www.necase.ca/main/committees/necase-bylaws-and-policy-committee/deliverables/359-02necase-bylaws-changelog-may12-2017)

**Comment by patcon** [comment]
- received sample by-laws from:
  - [Fourth Pig by-laws](https://drive.google.com/file/d/0B2riIxpG2GHEb0djTzBEVEdadTh6dGhQSTltV1lGRkVOcl93/view?usp=sharing) (free to share)
  - [Come As You Are by-laws](https://drive.google.com/file/d/0B2riIxpG2GHET3dCSE9fa0VSZGhrWFcxcEhBZ2g5aTl0d2ln/view?usp=sharing) (NOT free to share)
  - (keeping these in "Templates & Examples" folders)
- created our own [gdoc for drafting by-laws](https://docs.google.com/document/d/1QN8QzmSnnj1GoxybuuFqJoquUtqUEPdX4PRPfchWQFg/edit) based on CWCF sample

**Comment by patcon** [comment]
Feedback from Matt at Fourth Pig:

@patcon sent email:

> > Member Benefits
> >
> > The Board may create a reserve fund before any distribution of surplus arising from the
business of the co-operative in each fiscal year is made. Unless the surplus exceeds $12,000 in
one fiscal year, no patronage returns will be allocated, credited or paid to members or
non-members.
> 
> Not sure how to square this bit with not-for-profit status and your articles. Can you clarify? :)

Matt reply:

> In terms of your question - it is referencing the surplus fund - we are allowed to have a contingency (reserve)  fund in order to properly operate the business. We recently put this in to mark that we want to make sure that funds continue to go into the contingency fund. So with the money we get in we a) pay our account receivables b) put money in the reserve fund c) pay off any debts d) provide patronage returns.

**Comment by patcon** [comment]
From https://github.com/hyphacoop/organizing/issues/70#issuecomment-538146143

We go this advice from our accountant:

> document in constitution that money is going into separate bank account and have it all specified in by-laws. it will be part of the reserve.

**Comment by dcwalk** [comment]
Adding myself to this to keep it on my radar, not meant as a claim of exclusivity

**Comment by dcwalk** [comment]
Confirming we are :tada: ready to draft :tada:

**Comment by patcon** [comment]
@dcwalk mentioned in [`2020-01-29` gov wg notes](https://github.com/hyphacoop/organizing/pull/196):

> pc: what's in scope of bylaws? [...]  
> dc: good chapters in "ours to hack and own" platform coop book

https://worldpece.org/sites/default/files/artifacts/media/pdf/ourstohackandown.pdf

"Chapter 15: Three Essential Building Blocks for Your Platform Cooperative", written by Janelle Orsi, [known as the "sharing lawyer"](https://nextcity.org/daily/entry/raising-a-nation-of-lincolns-an-interview-with-janelle-orsi-the-sharing-law), including sharing bylaws.

> The list of things I would build into cooperative bylaws is actually
**much longer than the above**...

She apparently spent quite a bit of time drafting the [Loconomic Co-op bylaws](https://loconomics.gitbooks.io/loconomics-cooperative-bylaws/content/) (which we'd found already, but maybe an extra reason to lean on them 🙂)

**Comment by dcwalk** [comment]
@benhylau summary of the Janelle Orsi section:
Three elements to encode securely into the legal structures of platform cooperatives:
1. **Prevent the platform from being sold**
     It is critical to adopt strong safeguards against the potential for the platform and any of its major assets to be sold into for-profit structures. A decision to sell major assets of the platform should require a high threshold of approval, such as by 80 percent of members, after  what would hopefully be a long public conversation about alternatives.
2. **Put a cap on pay-outs and compensation**
    The platform cooperative Loconomics uses data from the Bureau of Labor Statistics to cap employee pay at 3.5 times the median wage for all occupations in the region where the employee works. In the Bay Area, the cap would be $165,000. Among tech CEOs, that might sound like poverty.
3. **Adopt a staff trusteeship model of governance**
   Staff trusteeship is a governance model that views all staff members of the cooperative as trustees who manage the platform for its beneficiaries, the body of members as a whole...Staff self-manage using an internal governance and operational model such as Holacracy or sociocracy, which distribute power among staff... In a staff trusteeship cooperative, the board of directors is still elected, but it takes on a role that is more akin to that of a guardian, overseeing the activities of the organization and ensuring that the staff are tuning in to members in every possible way.

**Comment by dcwalk** [comment]
This happened! Followed up from AGM in #307
