### ISSUE TITLE
Create process for managing articles of incorporation

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#103]
Re-ticketed from https://github.com/hyphacoop/organizing/issues/78

## Shared Description

:speaking_head: **Loomio:** https://loomio.hypha.coop/d/cPnZpext/articles-of-incorporation-submission (until clarity on better place)  
:date: **Due date:** N/A  
:dart: **Success criteria:** We have a known documented process for making legal changes to our articles.  

## To Do

- [ ] get +1 on general approach
- [ ] ...

**Comment by patcon** [comment]
Here's my proposal for what this might entail. Looking for feedback:

## Proposed To Do

- [ ] transpose [current filed articles](https://drive.google.com/file/d/1mBI5uB8dR3u285b5pUFDvbUk-HT2bBXU/view?usp=sharing) into version control within `hyphacoop/organizing`
- [ ] create handbook guide for modifying

**Comment by patcon** [comment]
Seems that in order to update articles, there are two possible proccess:
1. [Change your co-op’s information: "file _Articles of Amendment_"](https://www.ontario.ca/page/start-dissolve-and-change-co-operative-corporation#section-7) ($100)
2. [Combining Articles of Incorporation: "file _Restated Articles of Incorporation without Share Capital_"](https://www.ontario.ca/page/start-dissolve-and-change-co-operative-corporation#section-9) ($100)

At first glance, it seems that option (2) for filing restated articles wholesale is for some reason less onerous than filing amendments (which seem to require statements of solvency). It's likely that "restatement" can't have any new amendments ([example](https://cca.hawaii.gov/breg/faqs/profit-corporations/what-is-the-difference-between-the-articles-of/)), though not sure, because in [docs for federal incorporation](https://www.ic.gc.ca/eic/site/cd-dgc.nsf/eng/cs02718.html): 

> No fee is payable if _Form 7 – Restated Articles of Incorporation_ is **submitted together** with a _Form 4 – Articles of Amendment_.

**Comment by dcwalk** [comment]
Not adverse to what you are proposing, but I also think a lighter touch process will accommodate us just as well :woman_shrugging: (e.g., not version controlled but need-driven iteration and versioned documents)

**Comment by patcon** [comment]
Ah maybe i jumped the gun -- guess it didn't cross my mind that storing on github might be too heavy

**Comment by dcwalk** [comment]
Discussion on `2020-03-11` governance meeting: we see these articles as static and unlikely to change after our planned amendment. We'd like to close at this time but keep in mind a move to `organizing-private` (so as to preserve a full version of our articles) during the amendment process in #104.
