### ISSUE TITLE
Amend our articles to better align with our not-for-profit status

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#104]
Re-ticketed from #103 

## Shared Description

:speaking_head: **Loomio:** N/A  
:date: **Due date:** end-September 
:dart: **Success criteria:** ~~We are in a position to apply to CRA for not-for-profit status~~ We have updated our objects within our articles. 

UPDATE: We are **already a not-for-profit**, but our articles seem to have been curiously approved while **missing some recommended provisions**. We **may want to correct** this, esp if we plan to lean on not-for-profit status for tax-exemptions, but this is **non-urgent**.

This will cost us $100, see https://github.com/hyphacoop/organizing/issues/104#issuecomment-713811247

## To Do

- [x] Check with Matt @ Fourth Pig whether amendment is required.
- [x] Seek approval of members to amend -- agreed as an approach
- [x] Draft resolution to amend with language for AGM
- [x] Wrap-up prep from meeting: #307 
- [x] Prepare for submission
  - [x] confirm digital signatures? See: https://github.com/hyphacoop/organizing/issues/104#issuecomment-701484059
  - [x] decide submission process (online: companiesfilings@ontario.ca)
- [x] @patcon: review documents (in gdrive) [doc](https://docs.google.com/document/d/1nMridbObBGWNz1dxUYRtSAmlhpNwSsULzMUXQz5ii-M/edit?usp=drive_web&ouid=117169981156567015860)
- ~@dcwalk: Submit amendment **within 6 months** of resolution from June 13, 2020 (at AGM) -- December 13 the latest~
  - [x] compile package and send out for sigs
  - [x] sigs @benhylau and @YurkoWasHere 
  - [x] @dcwalk submit
- [x] New resolution: https://github.com/hyphacoop/organizing/pull/447
- [x] Prepare for submission
  - [x] compile package and send out for sigs
  - [x] sigs @benhylau and @YurkoWasHere 
- [ ] @dcwalk: Submit amendment
  - [x] @dcwalk submit
  - [x]  @dcwalk pay

**Comment by dcwalk** [comment]
First couple to-dos should be to verify whether our current articles _are_ a blocker

**Comment by patcon** [comment]
Looking at the [sample articles](https://drive.google.com/drive/u/0/folders/1r7b2Kh2-In1wyS-ANpmkWt_xdHjjRrPJ) we've received from Fourth Pig and Refocus (two Ontario not-for-profit [worker] co-operatives without share capital), it seems we're missing these clauses:

## Fourth Pig

> - The co-operative shall be carried on without the purpose of gain for its members and any profits or other accretions to the corporation shall be used in promoting its objects.
> - The directors shall serve as such without remuneration and no director shall directly or indirectly receive any profit from their positions as such, provided that directors may be paid reasonable expenses incurred by them in the performance of their duties.
> - Upon the dissolution of the co-operative and after payment of all debts and liabilities, its remaining property shall be distributed or disposed of to non-profit co-operatives or charities.
> - The Co-operative's primary objective is to provide employment to its members.
> - It is a condition of membership in the Co-operative that, except in certain circumstances prescribed by the regulations under the Co-operative Corporations Act, a member must be employed by the Co-operative.

**Comment by patcon** [comment]
This also makes me think we've missed something:

https://ontario.coop/sites/default/files/STR06_For%20Profit%20and%20Not%20for%20Profit%20Co-ops.pdf

> In the case of co-ops, there are certain statements that will have to be included in your Articles of Incorporation. You will have to indicate in the ‘special provisions’ section that (1) **the co-op is carrying on business without the purpose of gain for its members** and that (2) **any profit or surplus that the co-op earns will be used for the purposes of promoting its objects**. This will indicate to the Canada Revenue Agency that the co-op meets the criteria to be considered not-forprofit and is therefore income tax exempt.

**Comment by patcon** [comment]
So it seems at the very least we should be adding two parts, and there might be some other things we want to take, common from the other by-laws. (Come As You Are, a for-profit worker co-op, does not mention these other two things, which don't seem strictly required.)

**Comment by patcon** [comment]
Correction from Matt @ Fourth Pig (key summary phrases in bold):

> CRA doesn't review your application [or objects/articles]  - the province does. If you are a co-op without share capital then the CRA recognizes your non-profit status. [...] You aren't charitable so no need for them to review what you do to make sure you abide by those laws.

When I pointed out that we had been allowed to incorporate without certain seemingly-important objectives advised by OCA (pointing him to this thread), he advised:

> the CRA does determine the criteria for non-profit and the criteria in this case is that you are incorporated w/o shared capital - they recognize that as a non-profit - that is established. We have never been challenged by the CRA on our status. A co-op without share capital is a non-profit under current law. To my understanding this isn't a debate but is something generally accepted. So **if you are incorporated without share capital you are a non-profit in the eyes of the CRA**. This is very different than charitable status in which case the CRA definitely wants to see pretty much every thing you do.
>
> It seems to me that there are some contradictory views around surplus but **if non-for-profit status is of primary importance [...] then it may be prudent to amend the articles.**

**Comment by patcon** [comment]
So it seems that: WE ARE ALREADY A NOT-FOR-PROFIT

And so changing the articles is low-urgency, but something we might want to deal with when we're otherwise updating our articles -- esp if we want to do work that is mission-related (ex: education or community capacity-building workshops, according to Matt) for which we'd want to take advantage of tax-free status.

**Comment by patcon** [comment]
Further evidence that it's up to us to amend: (we're missing the recommended objects that this section says are required for compliance)
https://www.canada.ca/en/revenue-agency/services/forms-publications/publications/it496r/archived-non-profit-organizations.html#P95_16394

And further, mentioned here: https://www.cof.org/content/nonprofit-law-canada

> ### Not-for-Profit Organizations (NPOs)
>
> [...] Also, because the _Income Tax Act_ does not require registration of NPOs, they essentially self-assess their status.

The above aligns with my understanding from OCA fact sheet STR006, that tax-emempt status is under separate jurisdiction of CRA's act, NOT the _Ontario Co-operative Act_. I think we're technically able to say we're NPO right now, but that our objects (i.e. special provisions) somehow skimmed under Service Ontario radar. This was perhaps possible due to co-ops being newly under their watch, after migrating from FSCO jurisdiction [as of Oct 29 2018](http://www.fsco.gov.on.ca/en/coops/Pages/default.aspx).

**Comment by dcwalk** [comment]
It seems like we're okay to not rush this, can we update the TODOs/main issue to reflect that @patcon ?

**Comment by patcon** [comment]
Does the current main issue look ok dc?

**Comment by benhylau** [comment]
Let's do this in September and submit it with bylaws for lawyer/accountant to review.

**Comment by patcon** [comment]
We can sign and file digitally due to covid (seemingly just temporary to be able to use email, 180 days after end of emergency period):
https://www.ontario.ca/page/covid-19-changes-meetings-and-business-operations

Plain language and links to this notice:

[Notice - Filing Methods and Requirements](http://www.forms.ssb.gov.on.ca/mbs/ssb/forms/ssbforms.nsf/FormDetail?OpenForm&ACT=RDR&TAB=PROFILE&ENV=WWE&NO=ON00085E)

>  This Notice of Filing Methods and Requirements is made by the Director and Registrar under the Alternative Filing Methods for Business Act, 2020 and amendments to the following business statutes (the “business statutes”):
> [...]  
> 3. Co-operative Corporations Act
>
> [...]
>
> ## Temporary Filing Methods - E-Filing
> For the purposes of section 3 of the Alternative Filing Methods for Business Act, 2020, if a business statute requires or permits a document to be filed by in-person delivery or mail with the Minister, Director or Registrar, a person or entity may instead file the document by **email or fax in accordance with this Notice**, until further Notice is provided. The document must be a legible electronic copy.
>
> Documents filed by email or fax must be received together with all other required documents executed as required and the required fee by the Ministry during business hours (Monday – Friday, 8:30 am to 5:00 pm, except holidays), on or prior to the requested effective date. Documents and fees received outside these times are deemed received on the next business day. The business statutes and regulations continue to apply except as set out in this Notice.
>
> Specific requirements for filing documents and search requests by email and fax are set
out below.
>
> ### i) Sending documents or search requests by email
> Legible PDF electronic copies of documents may be filed at the following email address: companiesfilings@ontario.ca. Duplicate copies are not required. The prescribed, required or approved form under the applicable business statute for filing by in-person delivery or mail must be used, and the prescribed or required accompanying documents must be included, **together with the fee (in the form of contact information** as set out below to permit fee collection). No specific form is required for a search request.
>
> For your security and protection, credit card information cannot be provided by email. Please provide a **daytime contact phone number as part of your cover letter**. After your email is received, you should receive a **phone call from staff within about five (5) business days** to collect credit card information (e.g. cardholder name, number, expiry date, etc.) and payment will be processed at that time.
>
> Do not include credit card information in an email.
>
> Any email containing credit card information will be deleted to protect your information and maintain compliance with credit card industry protocols. Your application will not be processed and you will need to email it again without the credit card information included.
>
> All emailed documents will be handled the same as mailed in documents and service standards for mailed in documents will apply. The Acts continue to govern in all respects, including effective dates. This will not be immediate fulfillment.
>
> A cover letter should include the **contact name, return address, daytime telephone number and a future date (up to 30 days ahead) if requested** for corporate documents. The **total number of pages** contained in the attached document should be indicated in the cover letter

**Comment by patcon** [comment]
This hasn't been mentioned in here yet, but the cost of amending our articles is $100:
https://www.ontario.ca/page/start-dissolve-and-change-co-operative-corporation#section-7

Not sure if that changes anything, given our slim margins right now.

**Comment by patcon** [comment]
Looks great! Left small comment, but submit at will! Thanks dc!

**Comment by patcon** [comment]
Added suggestion for incl daytime phone number for payments, as I suspect that's not our main number.

Also, we need to state number of pages in cover letter. (added)

**Comment by dcwalk** [comment]
Initiated signing process!

**Comment by dcwalk** [comment]
Submitted 2020-12-09 by efiling, waiting to pay with Hypha CC.

**Comment by dcwalk** [comment]
Followed up by email 2020-12-16, haven't heard anything
Called ServiceOntario 2020-12-17 13.07, spoke with Guy, will send email to org asking them to call me "within 2 business days" :face_with_head_bandage:

**Comment by dcwalk** [comment]
Received follow up call from Kathy cppsb on 2020-12-21 12.48 (and previously 2020-12-18), confusion over pgp digital signatures and update on timeline: 35 business days for co-ops, even efilings. I asked whether this would impact them being accepted, answer seems to be "maybe, probably not".   Will send response to clarify

**Comment by dcwalk** [comment]
Email response:
~~~

 We are unable to proceed with the processing of the above-mentioned due to the following:

    The Resolution provided must be signed.
    An Affidavit of Solvency is required for each signatory indicated on page 2 of the Articles.
    The encrypted page is not acceptable as it is not legible for our public records.
    The processing fee of $100 is required. 
~~~

**Comment by dcwalk** [comment]
Called Wendy, she is confirming whether the signatures will work, will inform us if she needs to speak to policy (if that is the case will be quicker for us to resign them.)

**Comment by dcwalk** [comment]
Re-sumitted with visual e-signatures

**Comment by dcwalk** [comment]
They took payment so I think that means the 2nd attempt will be processed!

**Comment by dcwalk** [comment]
Amended articles uploaded to drive by @YurkoWasHere ! Closinggggggggg :rocket:
