### ISSUE TITLE
Host informational interview with Brierwood Co-op (RIP)

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#106]
Re-ticketed from https://github.com/hyphacoop/organizing/issues/70

## Shared Description

:speaking_head: **Loomio:** N/A  
:date: **Due date:** N/A  
:dart: **Success criteria:** Host a call and share-back notes.  

## To Do

- [ ] ...

**Comment by dcwalk** [comment]
Closing at `wont-do` given the age of the ticket
