### ISSUE TITLE
Research open source financial accounting systems

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#107]
Re-ticketed from https://github.com/hyphacoop/organizing/issues/89

## Shared Description

:speaking_head: **Loomio:** N/A  
:date: **Due date:** Aug 3, 2020 (in gcal)  
:dart: **Success criteria:** We have researched an open source accounting solution, and made a collective go/no-go decision.  

## To Do

- [ ] test Odoo (financial components) https://github.com/hyphacoop/organizing/issues/96
- [ ] ...

**Comment by patcon** [comment]
For (much) later: https://github.com/gratipay/inside.gratipay.com/issues/954#issuecomment-269993179

**Comment by garrying** [comment]
Closing this for now. Will create a new issue/milestone to reflect this initiative.
