### ISSUE TITLE
Set up Service Ontario account

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#110]
Re-ticketed from https://github.com/hyphacoop/organizing/issues/99#issuecomment-531736447

## Shared Description

:speaking_head: **Loomio:** N/A  
:date: **Due date:** N/A  
:dart: **Success criteria:** Account is created and documented.  

## To Do

- [x] Set up [Service Ontario account](https://www.appmybizaccount.gov.on.ca/wps85/portal/osb/!ut/p/z1/hZBPb4JAEMU_iweOZQaw_OkNqCKtlqYElb2YxWxXGrqQXYT023eN6cFG49xm5vfevAwQ2AIRdKg57etW0Eb3JXF3a2_hv2eZayXP_gzDRRwUc_TtZOXAGjb3EKLXeKNC1HpyRpZRXuByaiVpOsO0CIL4bbpyglfrD_injD7syEFMMvsqcHGk1CG9myE9F_KTR0MFh5IJyJnYxSG8AOFNW53_EIrK8TkQyT6ZZNI8Sj0-9H2nngw0cBxHsxU9lXVr7qmBHeXMwOqoasGUelBMDvWeqWtOh1b1sL00gO57HqRfj90w_jgNn0x-Af_rx0o!/dz/d5/L2dBISEvZ0FBIS9nQSEh/) [ℹ️ info](https://www.ontario.ca/page/set-up-serviceontario-ministry-account)
  - [x] create account
  - [x] add to link.hypha.coop/inventory
  - [x] add to link.hypha.coop/passwords

**Comment by patcon** [comment]
@dcwalk you said in chat that you wanted to handle this, right?

**Comment by dcwalk** [comment]
Yes I can

**Comment by dcwalk** [comment]
Hey so, this is set up, but I'm actually not sure it _does_ what it said it did. The services available are much more limited than the Service Ontario page describes.

Should we just sit on it for now and... wait to see if we use it?

**Comment by patcon** [comment]
@dcwalk was curious what it offered, and so tried to find password in https://pass.hypha.coop, but I'm not seeing it. Did you share it with infra group in the "sharing" tab of the  service? (If not, then I think it's only visible to your user)

**Comment by dcwalk** [comment]
Uhhhh, I can only use passbolt as a browser extension, I still have the issue where I'm unable to log in (this has been the case for more than a few weeks, have not been able to resolve). 

So I've tried to share but I can't edit the password because I can't actually log in to change it.

**Comment by dcwalk** [comment]
Okay, resolved my passbolt issue (sorta... not), and should be properly shared @patcon

**Comment by patcon** [comment]
@dcwalk Worth documenting in a handbook guide? e.g., "Adding shared passwords" cc: @YurkoWasHere

**Comment by patcon** [comment]
Should we add a "Business account service" and see what's in there? Feels like it might be relevant

> Business accounts service allows you to view your business account information from various government programs (e.g. Employer Health Tax, Retail Sales Tax) that have adopted the Business Number. You will be able to view a summary of your existing business information in a single view within your ServiceOntario account. In order to access this service, you will need to complete an authorization process, using one of your Ministry of Finance Business Number (BN15).

They mention a few specific programs, but the language makes it seem like it's a list that will expand as systems get integrated with the BN.

Also, assuming services are expanding, wondering if we might want to enable this in "Account setting":

> - [ ] I would like to receive email notifications for general information, including new services, programs and incentives available for my industry or sector.

**Comment by dcwalk** [comment]
Yeah, none of the current services are relevant to us and as a result, none can be added. I'm not sure if we need to care about the email notifications and I'm thinking we might as well wait until something happens on our end to initiate us re-engaging with the service

**Comment by benhylau** [comment]
Agree to not enable notifications. Even if we do it should only notify with a specific WG scope.

**Comment by patcon** [comment]
We can each have delegate accounts here, so can self-manage. I'm thinking I'll turn it on for me -- i can let others know if anything useful is sent, or disable if not. Any objection to my adding a delegate account, @dcwalk ?

**Comment by dcwalk** [comment]
I think it may be over complicating something we won't wind up using, but if you'd like to pursue it  I have no objection.

**Comment by dcwalk** [comment]
This is set up! closing
