### ISSUE TITLE
Set up CRA MyBusinessAccount

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#111]
Re-ticketed from https://github.com/hyphacoop/organizing/issues/99#issuecomment-531736447

## Shared Description

:speaking_head: **Loomio:** N/A  
:date: **Due date:** N/A  
:dart: **Success criteria:** Account is set up for all authorized users, documented appropriately, and accountabilities related to the account are understood.   

- **Instructions** for setting up new directors/owners: https://github.com/hyphacoop/organizing/issues/99#issuecomment-530122928

## To Do

- [x] ~~Register an HST number with CRA~~ `deferred`
  - Accountant corrected that our business number (BN) _is_ our HST number. We'd just enable HST payments in CRA portal. We have some research to do, re: non-profit status and HST.
  - [x] reticket HST research task from [kickoff meeting notes](https://hackmd.io/@patcon/ryMxS3okB/https%3A%2F%2Fhackmd.io%2F716xTfHcQ-CSzwmcYgmtjw%3Fview?type=book). done: https://github.com/hyphacoop/organizing/issues/120
- [x] sign up for www.cra.gc.ca/mybusinessaccount
  - [x] troubleshoot registration: call 1-800-959-5525 (wait > 1 > 2 > wait > 0)
  - [x] discuss how we want to manage access
  - [x] add all directors as "owners"?
    - [x] patcon 
    - [x] ben
    - [x] dc 
    - [x] yurko
  - [x] ~~add other member-owners as "employees"? udit, garry, asotnetwork~~ `wont-do`
    - Our accountant advised against giving this away liberally
  - [x] add to link.hypha.coop/inventory#CRA-My-Business-Account
  - [x] ~~add to link.hypha.coop/passwords~~ individual logins

**Comment by patcon** [comment]
@benhylau and I discussed, and he's going to call in to add himself and others, if they're interested. He will phone @dcwalk and @YurkoWasHere and get SIN-bday details, if they would like.

**Comment by benhylau** [comment]
Called CRA to add @YurkoWasHere and myself. Also answered a bunch of questions about the nature of the business as they need to put us into a category. Now we just need @dcwalk to call and we're all set on that front. Already those verified can access the business account through https://www.canada.ca/en/revenue-agency/services/e-services/e-services-businesses/business-account.html

**Comment by patcon** [comment]
updated instructional comment for new director setup (based on ben's experience), and linked to them in OP of this issue.

**Comment by dcwalk** [comment]
Hmm, some portion might be useful for adding folks later, can we make a parking lot /graveyard for notes rn, just chuck in it?

**Comment by dcwalk** [comment]
PS -- forgot to mention @patcon , I'm added as owner, we're almost done!

**Comment by patcon** [comment]
> can we make a parking lot /graveyard for notes rn, just chuck in it?

Good idea! You thinking like a long-running issue in `hyphacoop/handbook` or something else?

**Comment by patcon** [comment]
@benhylau after accountant meeting, do you feel we have decent footing on managing portal access? I'm thinking we're good enough to now, and it will be in finances roles where we'll get more specific. aka, I think that _discuss how we want to manage access_ is done?
