### ISSUE TITLE
Schedule a weekly bizdev cowork day

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#116]
Re-ticketed from #85 

## Shared Description

:speaking_head: **Loomio:** N/A  
:date: **Due date:** Thu, Oct 3 (before end of first cowork)  
:dart: **Success criteria:** Run first cowork.  

There was an _epiphany_ in the business plan writing meeting where we realized that we all need to get together in a room regularly and learn how to full up our pipeline with projects, and seek opportunities.

(h/t @netolic500 of camba.coop for inspiring us with the story of their co-op launch process)

cc: @hyphacoop/business-planning-wg 

## To Do

- [x] figure out locations
    - @dcwalk's apartment every 2 weeks
    - @uditvira's workplace (Free) every 2 weeks
- [x] create new when2meet and migrate old https://link.hypha.coop/schedules
- [x] create a check-in for updating when2meet
- [x] lock in a specific time for first meeting (in gcal)
- [x] decide permanent weekly timeslot
- [x] run first meeting

**Comment by patcon** [comment]
Can someone refresh me on our restrictions? I recall:
- @uditvira can finish the day around 4pm if needed...?
- @dcwalk could do early morning, but evening-brain was bad?

anything else that was informing this on-the-street convo?

**Comment by dcwalk** [comment]
I'm closing this as it is marked as done
