### ISSUE TITLE
Determine scope of involvement in annual CWCF conf

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#117]
Re-ticketed from https://github.com/hyphacoop/organizing/issues/115#issuecomment-536089295

## Shared Description

:speaking_head: **Loomio:** N/A  
:date: **Due date:** Thu, Oct. 10 (registration closes) 
:dart: **Success criteria:** We decide how we will be involved, if at all, and close out related actions.

The event takes place Oct 24-26 (Fri-Sun) in Tatamagouche, NS. The event also includes the AGM for CWCF, in which Hypha's now a member! :tada: (https://github.com/hyphacoop/organizing/issues/67)

- Kaye (CWCF) recommended we attend in RFP followup call.

## To Do

- [x] Discuss at all hands meeting.
- [ ] ...

**Comment by patcon** [comment]
- :mag: My family lives nearby, near Saint John, NB.
- :mag: I've been planning to visit my Mom soon anyhow.
- :bulb: I can likely borrow the family car.
- :mag: There's room for others in any accommodations, if desired.
- :mag: Drive times to Tatamagouche:
  - 3h drive from my home.
  - 1h 50m from my family cottage in beautiful Shediac, NB.
  - 1h 15m from Sackville, NB.
- :mag: Sackville is the university town for Mount Allison University.
  - :mag: It has a pretty vibrant co-op scene for a small town.
  - :mag: I've been in touch with some folks
    - :heart: I feel I could arrange a billet.
- :heart: I feel that we could treat this as a business development opportunity.
- :mag: [Ticket prices](https://www.gifttool.com/registrar/ShowEventDetails?ID=1894&EID=27409) for 3-day event range from $125 (subsidized) to $195.
  - :mag: individual days and after-hour tickets are possible if not staying full time.
  - :mag: Subsidized rate also applies to 2nd and 3rd attendees
  - :heart: I would feel alright asking for subsidized rate for myself.

**Comment by dcwalk** [comment]
@patcon this happened, can you close out/update as appropriate?

**Comment by patcon** [comment]
- I arrived Fri late night (2nd of 3 days)
- folks had left early, so after telling them about getting there, organizers said it was fine to join as participant under someone else's ticket at no cost.
- they gave me a room that had emptied
- everyone was generally wonderful and hospitable
- I took notes and dropped them in https://link.hypha.coop/meetings

**Comment by patcon** [comment]
Also, two fellow member-owners helped me get there through personal loans totalling CAD$150. There was some partial downplay of returning the payment, but I'd still love to offer something back, either myself or through org ledger.

Wondering if we could discuss whether this stays outside co-op, or whether any of this could be expensible. (I kept my receipts for bus tickets and meals, which should come near the amount loaned.)

Perhaps we could repurpose this ticket into a wrap-up that includes that conversation. (Could retag as finance.)

Not urgent though. Thoughts welcome.

**Comment by dcwalk** [comment]
Closing as no further action needed

**Comment by patcon** [comment]
@dcwalk what are your personal thoughts on whether it's worth filing bus tickets as expenses to be reimbursed to people who provided financial resources? (CWCF waived the ticket/room costs for me, so was mostly just bus price.)

**Comment by dcwalk** [comment]
@patcon as someone who offered but did not end up personally contributing I don't think it's my purview to decide. I would say that personally I would not have expected my contribution to be reimbursed and it seems like a cost that we don't have enough income to support as the co-op rn, so I'd rather eat it personally.
