### ISSUE TITLE
Meet Reba Plummer of Urbane Cycle

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#118]
Re-ticketed from https://github.com/hyphacoop/organizing/issues/115#issuecomment-536089295

## Shared Description

:speaking_head: **Loomio:** N/A  
:date: **Due date:** N/A  
:dart: **Success criteria:** We have a meeting/call with Reba.  

Reba is very active in Canadian co-op community, and is:
- President & Ontario Director, CWCF
- Co-Executive Director, Urbane Cycle

Peter (OCA), Matt (Fourth Pig), and Kaye (CWCF) have all recommended we should meet her.

## To Do

- [x] Discuss at all hands
- [x] Reach out to Reba?
- [x] meet!

**Comment by dcwalk** [comment]
I just met her at the `2020-05-13` ontario regional CWCF social. Closing :tada:
