### ISSUE TITLE
Set up a CRM platform

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#119]
Re-ticketed from https://github.com/hyphacoop/organizing/issues/116

## Shared Description

:speaking_head: **Loomio:** https://loomio.hypha.coop/d/5U0K81Jh/tool-talk-customer-relationship-management-crm-  
:date: **Due date:** N/A  
:dart: **Success criteria:** We have set up and configured a CRM to our liking, populated with existing leads.  

At the bizdev meeting, we decided that it would be helpful for us to have a true CRM to use for the time being. The rationale being partly that it will help us learn best-practices that our current custom spreadsheet might not. https://link.hypha.coop/leads or [direct](https://docs.google.com/spreadsheets/d/1LyElXvLj7ASclSPQqcgOnuEWqBWBStilEfOhIosZzhA/edit#gid=0)

## To Do

- [x] Decide on tentative CRM amongst @hyphacoop/business-planning-wg: HubSpot
- [x] ~~solicit feedback from @hyphacoop/infra-ops-wg~~ `wont-do` (see: 2019-11-19 notes)
  - [x] Create calendar event to revisit tool decision in 12 months -- @patcon https://github.com/hyphacoop/organizing/issues/96#issuecomment-528145669
- [x] Create Hubspot account with members@hypha.coop
  - [x] Add password to https://link.hypha.coop/passwords (infra group)
- [x] Add service to https://link.hypha.coop/inventory
- [x] send invites to @hyphacoop/business-planning-wg
- [x] request beta access to "related companies" feature. [link](https://community.hubspot.com/t5/HubSpot-Ideas/Associate-one-contact-to-multiple-companies/idi-p/19236)
  - [x] confirm enrolment in beta
- [ ] first-pass configuration of platform
  - [ ] discuss using [a specific spreadsheet](https://docs.google.com/spreadsheets/d/1D27I7edzwpDMpw8R0XIrgz-u_O6kyCRGl8cbmG7x1IE/edit#gid=0) to track addresses/phone/logos attached to platforms
- [ ] add lead/contacts from [first bizdev meeting](https://hackmd.io/@patcon/ryMxS3okB/https%3A%2F%2Fhackmd.io%2FqnEbmWSVRgqaWSA34dQKCg%3Fview?type=book)
- [x] add leads/contacts from https://link.hypha.coop/leads 
  - [x] update https://link.hypha.coop/leads shortlink https://github.com/hyphacoop/shortlinks/pull/4
- [ ] ...

**Comment by patcon** [comment]
Is it alright if I adopt this issue? (Speak up if you'd like to own it.)

**Comment by benhylau** [comment]
I feel WG-specific tool decisions should be decided by WG, and Infra should only care if there are major concerns (e.g. the tool has security problems) and that we record the use in our service inventory, any password used is granted appropriate access, etc. Same as with Finance, that would need to be informed only if there is a budget implication.

So if @hyphacoop/infra-ops-wg has no concern about this particular tool, they can just check the box for:

>- [ ] solicit feedback from @hyphacoop/infra-ops-wg

**Comment by patcon** [comment]
Also related, for @hyphacoop/business-planning-wg : does 6 months feel like a fair time to revisit tool choice?

**Comment by patcon** [comment]
Downside of hubspot: rigidly only allows one "company" per contact.

Since we are fuzzing company to be "associations", "communities", "peer groups", this gets a little awkard. If there is a lead through someone associated with "dweb community", then associating them with a community boots the attachment of their employer from the contact. This hides the relationship.

There's a beta workaround for adding "related companies" to contacts (this already exists in prod for "related companies" of "companies"). I've just signed up for us via the form:
https://community.hubspot.com/t5/HubSpot-Ideas/Associate-one-contact-to-multiple-companies/idi-p/19236

**Comment by patcon** [comment]
at bizdev cowork today, we all set up leads together.

## Emergeing Conventions

that are assuredly _not_ set in stone.

- :mag: we're leaning toward using "companies" to track much "looser" ideas -- groups of people, communities, ad-hoc collaboratives
- :mag: we're avoiding entering contact email addresses
  - :heart: it might be useful later (see below)
- we each have our own login
- we are creating "contacts" for Hypha members, so that we can indicate that "X was present in the meeting", regardless of who logs the activity (e.g., "email was logged by ben", but maybe other ppl were in meeting)
- :mag: we're not leaning hard on using email marketing tools of hubspot rn
  - :heart: we should perhaps discuss before we do
  - :mag: email marketing is enabled by auth'ing gmail api access per-user
    - :mag: hubspot uses your gmail to send, and also watched for replies and emails sent from gmail by you (it logs them, and auto-connects "contact" entities, using email addresses of contacts)
- :mag: "deals" are hubspot's term for singular entities that move from "lead > prospect > opportunity" etc
  - we seem to be using deals liberally for things we might pursue
- :mag: each contact/company/deal can have an "owner"
  - we're leaning toward most things getting "no owner" by default, an "owner" conveying that someone is claiming firm jurisdiction on a relationship (and it should be cleared before cold-entering the relationship)
- :heart: the pipeline kanban categories probably need to be tweaked
  - :mag: the first category by default is "appointment scheduled"
- :mag: there was minor disagreement on how to approach dollar values in the "Amount" field of Deals
  - :heart: one view was to add dollars ASAP to make board view more useful
  - :heart: one view was to wait until a few people could qualify or validate the value. putting a value early biases that conversation
  - **Suggested compromise:**
    - Created new field on "deal" for "Funding Confidence", to qualify the existing "Amount" field.
    - Current values of "Guess", "Validated" or "Locked"
      - Guess = one person's quick estimate of valuation
      - Validated = run by some people
      - Locked = a known, firm valuation
- :mag: Deals can only have one Company attached
  - :bulb: if a collaborative opportunity (aka Deal) involves more than one org, can choose the main one as Company.
  - :mag: Deals can have multiple contacts attached.
    - :bulb: we can add contacts from each org, and the contact entries display who people work with. E.g., Jane Cavuto, Director at Some Company Inc.

## Misc

Hubspot is geared for sales. Seems like we'll need to tweak it for grants or even for our personalized way of running a pipeline. We could learn by demo'ing this software, which was created specifically for tracking grant application:
https://www.neoncrm.com/grant-management/

cc @dcwalk @benhylau (pls gutcheck me on any of this, and edit my post as you feel appropriate)

**Comment by patcon** [comment]
> There's a beta workaround for adding "related companies"

We're now in the beta, which will support our weird workflows better.

**Comment by patcon** [comment]
Infra has no comment. removing label.

**Comment by patcon** [comment]
These are the current columns/stages in the sales pipeline (kanban for hubspot "deals"):

| # | Current | Proposed |
|----|-----------|--------------|
| 1 | Appointment Scheduled | ? |
| 2 | Qualified to Buy | ? |
| 3 | Presentation Scheduled | ? |
| 4 | Decision Maker Bought In | ? |
| 5 | Contract Sent | ? |
| 6 | Closed: Won | _no change_ |
| 7 | Closed: Lost | _no change_ |

1. **Anyone have any suggestions on what we could change/modify to better-suit our aspirational pipeline?** What should definitely be removed? What could be added? What could be tweaked?
1. **Is the pipeline drastically different for grants (e.g., distributed press) vs external clients?**
  - :mag: We can only have one pipeline in the free version.
  - :mag: We can rename the columns.
  - :bulb: We could uses slashed stage names to fit multiple pipelines into one. ![image](https://user-images.githubusercontent.com/305339/69889195-b1d70880-12bd-11ea-80ee-06af02ec1fdf.png)
  - :bulb: We could give the columns numbers, and define each differently in our own docs. 
![image](https://user-images.githubusercontent.com/305339/69889320-49d4f200-12be-11ea-95d3-1807b43d9c3e.png)

1. @benhylau what new phase would you say would describe the status of distributed press?

- :heart: I'd love to have a minimum default pipeline that at least partially describes our opportunities.
- :heart: I feel there should be a gate for internal buy-in or at least presentation/sharing
- :mag: We've said that we want a rubric to evaluate, but it doesn't yet exist.
- :heart: I feel a preliminary research stage is helpful, but mainly for internal projects/grants, not external clients.
- :heart: I feel that we shouldn't block all external convo before internal buy-in.
- :heart: I feel that we should be empowered to push proposals forward without group input, up to a point.
- :heart: I feel that we should ensure we have clear external language so that prospective clients knows that internal buy-in is a future step, and we're not committed yet.
- :mag: [Camplight Co-op](https://camplight.net/) in bulgaria _always_ runs a 1-2 week trial sprint (for both client and co-op), and so their threshold for moving forward with an opportunity can be lower.

**Comment by patcon** [comment]
- :bulb: I propose a first column of "Backlog" to capture things that don't yet have any appointment scheduled.
  - :heart: I feel we can invent a more descriptive name later.

**Comment by patcon** [comment]
#todo review and re-ticket CRM tasks -- @patcon
