### ISSUE TITLE
Formally initiate engagement with accountant

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#124]
Re-ticketed from https://github.com/hyphacoop/organizing/issues/70#issuecomment-538146143

## Shared Description

:speaking_head: **Loomio:** N/A  
:date: **Due date:** June 30, 2020  
:dart: **Success criteria:** We have a signed engagement agreement with Hema, our new accountant, and she has everything she needs from us  

On meeting with Hema, Ben and I were informed that nothing about our engagement agreement is required until it comes time to do end-of-year submission. Before then, we'll need to do the following.

(Hema is **very busy until early November**, and requested that we try to hold all but our most urgent requests until after that time.)

## To Do

- [x] Write our by-laws https://github.com/hyphacoop/organizing/issues/101
- [x] Submit our bylaws and mission to Hema
- letter of engagement
  - [ ] request updated copy of letter of engagement. MID-NOVEMBER
  - [ ] finance WG review [letter of engagement](https://drive.google.com/file/d/0B2riIxpG2GHEd21fSTBrOVJTSWdUZUJUM2Z5U1IwMHBuSElZ/view?usp=sharing) :lock:
  - [ ] sign and submit letter
  - [ ] store in gdrive
- [ ] ...

**Comment by benhylau** [comment]
Our arrangement with the accountant works for now.
