### ISSUE TITLE
Pilot self-hosted instance of Jitsi Meet video conferencing

### ISSUE THREAD

**Issue by ASoTNetworks** [hyphacoop/organizing#127]
## Shared Description

:speaking_head: **Loomio:** N/A  
:date: **Due date:** N/A  
:dart: **Success criteria:** We have our own Jitsi instance and it have been working nicely for our last two meetings.  

## To Do
- [x] set up jitsi service
- [x] configure SIP call-in
- [x] Update meeting links to https://jitsi.hypha.coop/hyphacoop in the following documents and services:
  - [x] Google Calendar
  - [x] Meeting Templates (Template: All Hands and Template: Standups)
  - [x] Update https://link.hypha.coop/calls https://github.com/hyphacoop/shortlinks/pull/9 -- patcon
    - [x] force shortlink update via re-running circleCI job at https://link.hypha.coop/logs -- patcon
  - [x] Add self-hosted Jitsi to inventory doc
- [x] document how to use mobile app hyphacoop/handbook#23
  - [ ] related spin-off: [`jitsi/jitsi-meet#4801` Follow redirects in android app when providing room URL](https://github.com/jitsi/jitsi-meet/issues/4801) -- patcon
- [ ] check-in on whether it is working

**Comment by patcon** [comment]
Thanks @ASoTNetworks! But if we're moving to using https://link.hypha.coop/calls for our call link, then I think the calendar isn't actually updated and reflecting that? Does using https://link.hypha.coop/calls everywhere feel like an ok tactic?

(The idea being that no matter what video platform we're using, https://link.hypha.coop/calls will always point there, and no more updating various docs if we move to another conferencing platform temporarily or permanently.)

**Comment by ASoTNetworks** [comment]
I agree on using just the https://link.hypha.coop/calls link.

**Comment by patcon** [comment]
ok, what are your thoughts on adding these as in-scope:

- [ ] document how to use mobile app with custom server? cc @dcwalk 
- [ ] confirm SIP number as final number
  - [ ] document where this lives, how to access, who pays, etc etc
- [ ] log any ongoing costs. cc @hyphacoop/finance-wg 
- [ ] meeting 1 full trial
- [ ] meeting 2 full trial
- [ ] final discussion in all hands meeting
  - [ ] seek final feedback
  - [ ] lock in new platform as our choice

Thoughts on these @ASoTNetworks? Anyone have other thoughts on what should be done before closing this out?

**Comment by YurkoWasHere** [comment]
@patcon

> document how to use mobile app with custom server? cc @dcwalk

I used it without a second thought.  I just went to the website on my phone and click the use app link. It just worked for me.  Is there another method your thinking. (For example it could just be an extension off our main line number).

> confirm SIP number as final number 

This is a longer discussion on what we want the telephone experience to be beyond a voicemail.  This conversation will illuminate what options we have for Jitsi. However i do not think we are at a stage that we could answer these question and/or need to even.

I think @ASoTNetworks has just used one of his numbers to test with the service.

> log any ongoing costs.

For now its been donated resources (IE I provided the SERVER/IP while elon has hacked in his own freepbx server for SIP). I think until we decide that this is actually better then the public jitsi instance there is no point incurring additional costs.

> Bus Test

This is also a longer conversation.  Right now there are several points in our infra that is single point of failure. Even though we have access to some resources those resources would become inaccessible if the owner of them was incapacitated.

The problem with this is that to do this "right" it costs money which we dont have.  So although it would be a good idea to try to diminish this as much as possible there are some infra that is more mission critical then others. And some can easy by swapped out with little to no notice and or impact (ie jitsi private to public)

**Comment by ASoTNetworks** [comment]
This is what we need to lock down the Jitsi instance:
https://github.com/jitsi/jicofo#secure-domain

Should I continue to set that up so I can make a full documentation with all the steps for Jitsi?

**Comment by darkdrgn2k** [comment]
> confirm SIP number as final number

We setup a FPL number for now not to incur  any costs.

**Comment by darkdrgn2k** [comment]
> It is possible to allow only authenticated users for creating new conference rooms. Whenever new room is about to be created Jitsi Meet will prompt for user name and password. After room is created others will be able to join from anonymous domain. 


Are we ok with passwording our jitsi instance for new rooms?

**Comment by YurkoWasHere** [comment]
> It is possible to allow only authenticated users for creating new  conference rooms. Whenever new room is about to be created Jitsi Meet  will prompt for user name and password. After room is created others  will be able to join from anonymous domain.  

Are we ok with passwording our jitsi instance for **new** rooms?
--

**Comment by benhylau** [comment]
Do we really care if other ppl use it? It's unlikely they will incur significant traffic.

**Comment by ASoTNetworks** [comment]
I am worry about if bots will use it to make spam calls or something.

**Comment by patcon** [comment]
> I just went to the website on my phone and click the use app link.

Case in point: I had never known to do this, and was instead manually opening the app, changing settings in app each time I needed to join a public vs private server room.

Your way is better, and now i know that, since someone explicitly said it somewhere :) You can still opt not to doc, but this stuff isn't always as obvious as it might first appear

**Comment by benhylau** [comment]
I also just clicked the link and it opened the app, but that's definitely not an obvious flow since ppl usually start by opening the app. There also is a way to set a custom server in the app. I think docs should describe both methods.

**Comment by ASoTNetworks** [comment]
In the mobile app you can also enter the full link of the channel like https://jitsi.hypha.coop/hyphacoop into the "Enter room name" bar without changing default server.

**Comment by patcon** [comment]
Hm. Seems changing default server is the hardest and least practical way. Inclined to suggest we just doc "visit the call link" (and maaaaybe "copy call link into app home screen").

Happy to just decide on which is simplest, and ignore others as "off-road" :)

**Comment by patcon** [comment]
Also, option for laaaaater-later: Using a pass-through screen to visibilize and hint at infrastructure/process choices, instead of putting them deep in handbook pages. (e.g. if we start recording calls, or if we want call participants to understand/consent to our note-taking practices)
http://edgi-video-call-landing-page.herokuapp.com/

Since it's our own little one-page app, we can evolve it to our liking (as opposed to app interfaces like jitsi, which we just have to live with)

**Comment by patcon** [comment]
> [re: bus factor. Even though we have access to some resources those resources would become inaccessible if the owner of them was incapacitated. -- @YurkoWasHere

What about just mapping out what would make this "done-done" (which is agile-speak for done "right" to the shared understanding of everyone, used without judgement). We don't need to do it now, but it's perhaps helpful to practice mapping out what "done-done" things look like, even if we kick the can down the road for now.

Thoughts?

**Comment by dcwalk** [comment]
Discussion on Nov 13 call: feels blocked on whether or not to lock down service now to only us

**Comment by dcwalk** [comment]
@ASoTNetworks I think you were going to update this issue per last standup, is this current? are we closer to closing out?

**Comment by ASoTNetworks** [comment]
We decided to keep using it until we move to something else.
