### ISSUE TITLE
Verify that message within digital signatures matches resolution

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#128]
Re-ticketed from https://github.com/hyphacoop/organizing/pull/113

## Shared Description

:speaking_head: **Loomio:** N/A  
:date: **Due date:** N/A  
:dart: **Success criteria:** We are sufficiently confident that our digital signatures match the current version of any resolution.

Some folks raised concerns about the signatures for resolutions not matching the resolutions themselves. For example, if yurko signs one version of a resolution, and then dcwalk makes a change, it would become confusing. This is because yurko's _old_ signature technically still signs a a very similar message, but the message it has signed isn't the newest version.

We can mitigate this through CI or automation if/when we feel like it.

## To Do

- [ ] write script
- [ ] enable CI on this repo
- [ ] test
- [ ] document (re: https://github.com/hyphacoop/handbook/issues/21)
- [ ] ...

**Comment by patcon** [comment]
Not quite generalized check in bash:

```sh
$ ls resolutions/resolution-001.md.*.asc \
    | xargs -I {} sh -c "gpg --yes --output resolutions/resolution-001.md --verify {} \
        && git diff --quiet \
        || exit 1"
```

Or alternatively if we know our director usernames:

```
$ DIRECTORS="benhylau dcwalk patcon yurkowashere" echo $DIRECTORS \
    | xargs -n 1 -I {} sh -c "gpg --yes --output resolutions/resolution-001.md --verify resolutions/resolution-001.{}.asc \
        && git diff --quiet \
        || exit 1"
```

For the above, it should error out if:
- a key for a director is missing
- the key doesn't match one in the keychain
- the content in sig changes that overrides file is bit-for-bit the same (no dirty diff)

Pre-requisites:
- install pgp on CI instance
- import keys into pgp keychain from keybase

The script probably wouldn't need to be clever and recognize which resolution the issue was about -- it could just find an resolution-*.md, and insist a key for each user verifies against the original content.

**Comment by garrying** [comment]
Closing for now given the current signing flows in the org.
