### ISSUE TITLE
Migration of Bank Account to Dejardins

### ISSUE THREAD

**Issue by YurkoWasHere** [hyphacoop/organizing#130]
Re-ticketed from #65

## Shared Description

:speaking_head: **Loomio:** N/A  
:date: **Due date:** N/A  
:dart: **Success criteria:** Start using Dejardins for day to day banking 

## To Do

- [x] Confirm account services
  - ~Interact e-Transfer~ (not implemented as of Nov 13, 2019)
  - [x] Remote Deposit
- [x] Receive Interact E-Transfers
- [x] Move money to Dejardins from Temporary account.

**Comment by YurkoWasHere** [comment]
Spoke with agent today

- Remote Deposit available vis Dejardins app
- Interact E-Transfer coming in the next few weeks
- Receive e-transfer available now

Alternative way of moving money

**PERSONAL PROVIDER SERVICES**
Power to send money to any bank using their bank information - transit and account number

**Comment by benhylau** [comment]
I wonder what is the best way to subscribe to services. For example, our QuickBooks subscription. Shall we use a personal credit card and reimburse?

**Comment by darkdrgn2k** [comment]
We can also look at getting a corporate credit card.  

From past experience with corporation the sooner the better so we can start building up credit for the CORP.

**Comment by YurkoWasHere** [comment]
Might be worth while looking into a credit card early one

CC Issue created #134

**Comment by dcwalk** [comment]
Waiting on bank for implementing interac, will not treat as blocked per Nov 13 call
