### ISSUE TITLE
When to use which communication tool

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#132]
## Shared Description

:speaking_head: **Loomio:** https://loomio.hypha.coop/d/p0A2fXia/when-to-use-which-communication-tool  
:date: **Due date:** N/A  
:dart: **Success criteria:** Have documented guidelines and shared practice of using our comm tools  

## To Do

- [x] Gather member preferences on Loomio thread
- [x] Send PR to handbook
- [ ] Get consensus to adopt practice
- [x] Merge PR

**Comment by patcon** [comment]
Might suggest using the practice together for some time period before documenting in handbook, but sounds good generally.

**Comment by benhylau** [comment]
![hyphacoop-mentions](https://user-images.githubusercontent.com/2261308/69043409-a2bda400-09fb-11ea-95d0-95829a7fff6a.png)

I have set up my bookmarks to filter out my hyphacoop mentions, and will be checking these daily to make sure I am not blocking tasks of other members.

@hyphacoop/member-workers I created this vote for all to agree/disagree on adopting this practice: https://loomio.hypha.coop/d/p0A2fXia/when-to-use-which-communication-tool/10

**Comment by benhylau** [comment]
Now I will stop looking at my subscriptions, since most of them I don't really care about. I trust that when my involvement is needed in a task, the member assigned the task will @benhylau or one of my groups, and then I will respond in a 1-2 working day window.

<img width="736" alt="Screen Shot 2019-11-18 at 12 29 07 PM" src="https://user-images.githubusercontent.com/2261308/69045262-2e84ff80-09ff-11ea-81e8-a70cab110a11.png">
