### ISSUE TITLE
Upgrade our Loomio instance to latest version

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#135]
Re-ticketed [from chat](https://matrix.to/#/!wvFLvXHaNrxWWwFOKj:tomesh.net/$1571778288596Cjmzs:tomesh.net?via=tomesh.net&via=matrix.org&via=elon.li)

## Shared Description

:speaking_head: **Loomio:** https://loomio.hypha.coop/d/jFvE4TIW/tool-talk-loomio
:date: **Due date:** N/A  
:dart: **Success criteria:** We've upgraded Loomio and ensured its infra docs exist / are up-to-date.  

Our instance is about a year behind, and we're missing at least a few helpful bugfixes (including one very noticeable one to fix scrolling in the popup when editing a post).

## To Do

- [x] Create a snapshot of the droplet
- [X] Follow update Loomio to the latest image [here](https://github.com/loomio/loomio-deploy#if-something-goes-wrong)
- [X] Remove droplet snapshot after a week when there are no issues

cc: @hyphacoop/infra-ops-wg

**Comment by patcon** [comment]
Hey @ASoTNetworks, if you're still open to taking this one on, please do self-assign :)

Also, any thoughts on what the scope of this might be before we can close it out. Like as you think though how you'll do it, if there are any steps someone else wouldn't know (or be able to do), than maybe worth noting those here, and I can help write docs before we close out the issue. Would that be a decent approach? (Feel free to edit my original message -- you should be able to as github org owner!)

Thanks man!

**Comment by patcon** [comment]
Questions I might ask myself to uncover potential todos (up to you whether to consider this in scope):
- is it helpful to skim the changelog and summarize changes for others? would this help us make best use of new features together?
- if so, should this be done before or after upgrade?
- is the above within scope of infra tasks generally?

**Comment by ASoTNetworks** [comment]
There was a lot of changes that they didn't even list on their release page since our version  https://github.com/loomio/loomio/releases

But it looks like they are doing more releases regularly now so we can include what changed in future updates.

The latest release includes a security fix which we need to update to fix:
>This fixes a security problem, where-by you could gain access to someone's account if you had a copy of a Loomio notification email to that person.

**Comment by ASoTNetworks** [comment]
Our Loomio have been updated to the latest version.

**Comment by benhylau** [comment]
I enabled Beta UI for myself and I encourage y'all to do it, threads come up faster and the UI is generally better

**Comment by patcon** [comment]
Are there any documentation steps that could be shared here? We don't need to commit to doing all the docs here and now, but having just done some work, the outline of the work is fresher than it'll ever be :)

E.g., If I'd like to be able to do the next loomio upgrade, what should i know?

**Comment by patcon** [comment]
Thanks @ASoTNetworks! Can we do a call before closing this out?

I'd love to do this upgrade next time, so knowledge gets distributed, so before closing, i'd love to rubberduck it with you, if you're down for that. i can jot down anything that feels non-obvious to me (a second brain) about what was done! Better the two of us, I feel like we could make this task so anyone could do it next time :)

**Comment by ASoTNetworks** [comment]
This is Done
