### ISSUE TITLE
Develop hypha introduction deck

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#136]
## Shared Description

:speaking_head: **Loomio:** N/A  
:date: **Due date:** ~~Feb 7, (mid-Jan First-pass; end-Jan Feedback period closes)~~ March 7  
:dart: **Success criteria:** have a deck that introduces hypha and our offerings

This was mentioned as a task by @uditvira in the `2019-10-23` standup notes as potentially be useful for pitching to leads

## To Do

- [x] draft outline [planning doc](https://docs.google.com/document/d/1YVwxJ7mfrXgHBxvwPTRLuk8pBenY1QQpPzPthqWRnkg/edit) :lock:
- [x] run brainstorm session -- MID-JAN
- [x] collect project details
- [x] draft [introduction deck](https://docs.google.com/presentation/d/1y8Mnyw147rsX1n5NsDek6dJHl9PWU3cwG-_QXBMfY98/edit#slide=id.g7d108645b5_0_80) :lock:
- [x] review/feedback on intro deck
- [x] integrate final feedback on deck -- did so at `2020-02-27` bizdev meeting
- [x] confirm image rights for distribution
  - [x] identify creators
  - [x] decide approach
  - [x] obtain rights/permission (opted for Unsplash imagery with attribution text)
- [x] finalize intro deck (huzzah!)

### Related Meetings
- [`2020-01-15` Governance](https://hackmd.io/@patcon/ryMxS3okB/https%3A%2F%2Fhackmd.io%2FVqFigBj0Sp-7c7swllzoug%3Fview?type=book)
- [`2020-01-08` Governance](https://hackmd.io/@patcon/ryMxS3okB/https%3A%2F%2Fhackmd.io%2FI9hJLc3VRCCk6LQjmcaX4g%3Fview?type=book)
- Various business planning in [`organizing-private`](https://github.com/hyphacoop/organizing-private)

**Comment by patcon** [comment]
Outline for deck udit is working on: https://docs.google.com/document/d/1YVwxJ7mfrXgHBxvwPTRLuk8pBenY1QQpPzPthqWRnkg/edit :lock:

**Comment by benhylau** [comment]
We briefly discussed our core skill sets and relevant past projects at our last biz dev meeting of 2019. Putting some thoughts here for us to pick up in 2020.

1. Consulting and building custom networks for communities and events
    - DWeb Camp 2019 participatory mesh network, Internet Archive
    - LoRa network, Steamlink
    - Infrastructure management, Toronto Mesh
    - Technical advisory, HBO Silicon Valley S6
2. Development and deployment of self-hosted / peer-to-peer software
    - Software development, Aether Pro
    - IPFS live streaming development and publishing, Our Networks 2018 and 2019
    - Matrix hosting with cjdns & yggdrasil integrations, Toronto Mesh
    - Meshnet and DWeb prototype on Raspberry Pi, Toronto Mesh
    - Terraform provisioning developments, Matrix and IPFS live streaming
3. Digital coaching and drafting practices for team collaboration
    - Digital coaching, Primal Glow
    - Open-source event organizing, Our Networks
    - Digital tools + services inventories, CivicTech Toronto + Our Networks + DWeb Camp
4. Workshop development and facilitation
    - Building the Peer-to-Peer Internet workshop series, Toronto Public Library
    - [ Dawn + Udit has a bunch to add ]

**Comment by dcwalk** [comment]
I moved the notes from our 2019-01-09 meeting on brand timeline into #77 and just updated the deadline listed in this issue.

**Comment by benhylau** [comment]
I would like to send this to a couple potential clients before end-Feb.

@uditvira can we finalize this at our Thursday bizdev meeting? Do we need any input from @garrying beforehand?

**Comment by benhylau** [comment]
Taking over for @uditvira while he's away. Hopefully will be finalized this week!

**Comment by benhylau** [comment]
It seems @dcwalk @garrying and myself have expressed opinion on how to move forward with image assets. Can everyone leave final thoughts by end of day (Tuesday), and I suggest @garrying take lead on how to proceed based on comments?

I have updated the issue to have **March 7** as the new deadline. Whatever the decision, I would like a backup plan by March 7 even if that means stripping out all the images from the deck.

**Comment by garrying** [comment]
A few points to close this issue off:
- Ideally, duplicate the deck and remove/unhide slides as needed
- I've added a PDF called `Hypha_Offerings_Jan2020 (Archived).pdf` as a reference of where we started with imagery
- Original images are in a folder called `unsplash images`

**Comment by benhylau** [comment]
Thanks @garrying this seems done. Closing.
