### ISSUE TITLE
Schedule an in-person meetup with Nomadic Labs

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#137]
Re-ticketed from https://github.com/hyphacoop/organizing/issues/77#issuecomment-547519842

## Shared Description

🗣 **Loomio:** https://loomio.hypha.coop/d/XKgh58Za/establish-identity-and-initial-elements-of-co-op-look-and-feel
:date: **Due date:** Fri, Nov 8, 2019  
:dart: **Success criteria:** We've met up and decided next steps in collab, and tasked out those next steps to be done before Luisa leaves Toronto.  

Hypha weekly standing availability: https://link.hypha.coop/schedules

## To Do

- [x] schedule a casual hangout (early in trip: Wed Oct 30 - Fri Nov 8)
- [x] decide/commit to running branding exercise with @luluissaa 

cc: @nomadic-labs @s-kennedy @luluissaa

**Comment by patcon** [comment]
Some comments on developments -- :mag: facts, :heart: feelings, and :bulb: ideas:

- :mag: @garrying and I spoke after last week's [`2019-10-23` standup](https://hackmd.io/@patcon/ryMxS3okB/https%3A%2F%2Fhackmd.io%2FHz8LjvJTSwaoxCCb1DFCBg%3Fview?type=book), about the convo he'd missed during our [`2019-10-16` all hands](https://hackmd.io/@patcon/ryMxS3okB/https%3A%2F%2Fhackmd.io%2FRsEK1pJUSIaLddUT6G9YpQ%3Fview?type=book).
- :mag: Partners of @nomadic-labs (Luisa Ji & @s-kennedy) as well as hypha members are interested in a low-stakes collab.
  - :mag: Luisa's main personal offerings are design & strategy skills.
  - :heart: I feel curious to learn more about worker co-ops. (@nomadic-labs)
- :bulb: Luisa suggested facilitating a branding exercise for hypha.
  - :mag: She said direct payment wouldn't necessarily be required, as she could imagine it as an investment in future collabs.
  - :heart: I feel Hypha members were a little cautious around not paying for labour. (patcon)
  - :mag: @dcwalk @uditvira @patcon @benhylau were in favour of premise.
  - :mag: Garry is our main design resource, but has limited capacity due to his full-time day job.
    - :heart: I feel this might be a good opportunity, given design capacity issues (@hyphacoop)
  - :heart: I feel we should check in with @garrying, since he's been "owning" the branding task. (@hyphacoop) 
    - :mag: @garrying is a-ok with the premise
    - :mag: Luisa doesn't live in Toronto.
      - :mag: **Luisa is visiting Toronto Wed, Oct 30 - Fri, Nov 8**.
        - :mag: @benhylau and @patcon are away during this time (UK & NB)
    - :heart: I feel there is a manageable cost to involving remote participants. (@garrying)
  - :bulb: Let's schedule an informal convo early in Luisa's visit, during which people can talk about possibilities, and get to know one another. (patcon)
    - :bulb: Maybe remote people can join somehow.
    - :bulb: If things go well, we could schedule a branding/design exercise before Luisa departs. (patcon)
    - :heart: I don't feel the need to participate in convos it's too much trouble. (patcon)

**Comment by patcon** [comment]
Here's a suggestion, looking at our availability:
- :mag: We're all available from 5:00pm ET onward Wednesday
- :mag: We're highly available from 2-4pm ET Saturday.
- :bulb: Let's do a **casual hangout (tomorrow. eek!) on evening of Wed, Nov 1** during/after our all-hands call (ends at 6pm ET)
- :bulb: Let's block off space for maybe doing a **facilitated branding exercise Sat, Nov. 2-4pm ET** during our high-availability HOLD.

**Comment by dcwalk** [comment]
Unfortunately I'm not available on such short notice for Wednesday, also
unclear if these are remote or in person?

**Comment by patcon** [comment]
I was understanding that remote was a last-resort for maybe Ben & I, but everyone else would likely need to be in-person for this to be worth it.

**Comment by benhylau** [comment]
I can't do Wed, and only after 3 pm on Sat.

I have a new biweekly on our HOLD slot, and have updated availability just now.

**Comment by patcon** [comment]
At all hands call, Udit suggested doing the following meetups:
- A casual unscheduled whatsapp call with udit+patcon+luisa in advance, and
- Saturday, Nov 2nd (1-4pm ish?) for a more structured branding exercise at Luisa's discretion, for everyone who can make it in-person (considered high-value convo by majority in all hands call). At least 3 people to be worth it.
  - Bonus for remote people calling in.

Will call luisa tomorrow and check in to see if this is still workable :)

**Comment by patcon** [comment]
@patcon  has action to re-open comms with Luisa

**Comment by luluissaa** [comment]
Hi!!!
I meant to follow up actually! Let’s resume the design stuff Jan/Feb? (maybe march when the snow starts to melt?)

**Comment by patcon** [comment]
Thanks @luluissaa! omg, even the idea of snowmelt gets me excited

i believe @garrying will be taking on coord of the larger branding tasks, so we'll poke you in new year after holidays! hope you have a chill one :)

**Comment by dcwalk** [comment]
We wound up going through an internal branding process for the first term (captured in #77), I'm going to close this for now. But I think a future collaboration with Nomadic Labs has to be in the stars :sparkles: :green_heart:
