### ISSUE TITLE
Make minimum set of labels available across repos

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#145]
Re-ticketed from https://github.com/hyphacoop/organizing/issues/132

## Shared Description

:speaking_head: **Loomio:** N/A  
:date: **Due date:** N/A  
:dart: **Success criteria:** We have an appropriate set of labels available in each repo we want them in.  

I've run up against labels being missing from repos that are only in `hyphacoop/organizing`. @dcwalk and I have worked on a project (EDGI) with multiple repos, where keeping them in sync was nice. ([see here](https://github.com/edgi-govdata-archiving/overview/pull/230/files?short_path=b8330c6#diff-b8330c648c0fc5041055a6ff8a040c92))

**Proposed labels:** See comment below.

**Proposed repos:** All repos. why not! (to keep it simple, even if some will be almost guaranteed unused)

- :mag: ~~@dcwalk and @patcon have used this: https://github.com/edgi-govdata-archiving/overview/pull/230/files?short_path=b8330c6#diff-b8330c648c0fc5041055a6ff8a040c92~~
- :mag: GitHub orgs [can have default labels](https://help.github.com/en/github/managing-your-work-on-github/about-labels#using-default-labels).
  - :mag: These defaults are useful for new repos, but less so for existing ones and ongoing synchronization.
- :bulb: Let's decide the labels we want.
- :bulb: Let's sync labels ~~like EDGI did.~~
- :bulb: Let's sync labels from one repo to rest using `github-sync` tool and github actions (see https://github.com/hyphacoop/organizing/issues/145#issuecomment-554188198 below).

cc: @hyphacoop/infra-ops-wg 

## To Do

- [x] create [new low-access team for robots](https://github.com/orgs/hyphacoop/teams/robots/members)
  - [x] give team `write` permission for [all required repos](https://github.com/orgs/hyphacoop/teams/robots/repositories)
- [x] set [org-wide base permission](https://github.com/organizations/hyphacoop/settings/member_privileges) from read => none
- [x] agreement that `hyphacoop/organizing` labels work for now
- [x] agreement on repos to sync to (see attached PR)
- [x] Write config file https://github.com/hyphacoop/organizing/issues/146
- Document how to update => https://github.com/hyphacoop/handbook/issues/39
- [x] Enable syncing
- [x] Test it

**Comment by patcon** [comment]
Or instead of defining a yaml and making a sync process, we could just choose a canonical repo to base the labels off of, and have this script run to generate a config, then run it on every other repo #zeroconfig style :)
https://github.com/popomore/github-labels#export-from-github-website

GitHub Actions can even trigger the script to run every time the labels are editted/created/deleted:
https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#label-event-label

**Comment by patcon** [comment]
Exported, in case we want to use this: `label-config.json`

```js
[
  {
    "name": "blocked",
    "color": "d73a4a"
  },
  {
    "name": "[priority-★★★]",
    "color": "ff7f00"
  },
  {
    "name": "[priority-★★☆]",
    "color": "ffaa00"
  },
  {
    "name": "[priority-★☆☆]",
    "color": "ffd400"
  },
  {
    "name": "proj:aether",
    "color": "8540ad"
  },
  {
    "name": "proj:primal-glow",
    "color": "8540ad"
  },
  {
    "name": "proj",
    "color": "8540ad"
  },
  {
    "name": "wg:business-planning",
    "color": "bfd4f2"
  },
  {
    "name": "wg:finance",
    "color": "bfd4f2"
  },
  {
    "name": "wg:governance",
    "color": "bfd4f2"
  },
  {
    "name": "wg:infra-ops",
    "color": "bfd4f2"
  }
]
```

**Comment by patcon** [comment]
Ok quick demo set up in `hyphacoop/demo-repo`.

Just change the labels here (color or rename):
https://github.com/hyphacoop/demo-repo/labels

And it will create/delete or modify colors of labels here:
https://github.com/patcon/archive-demo/labels
https://github.com/patcon/label-sync-demo/labels

This is done via:
https://github.com/hyphacoop/demo-repo/blob/master/.github/workflows/label-sync.yml#L16-L17

Using the [`github-sync` command](https://github.com/vanilla/github-sync), which has a clever "prune" variant of strict label syncing: this will delete labels from target repo that are missing from source repo, but _only_ if the target label is unused.

**Important:** Renaming a label that's _in-use_ (the vast majority use-case outside a demo) would be a **two-step process**:
1. Rename label in `organizing` (canonical repo), e.g. `label old` => `label new`
    - tool goes to work creating `label new` in the target repo, and it _would_ remove `label old`, but won't right away, since it's in-use.
2. Then in the [target repo issue listing](https://github.com/patcon/archive-demo/issues?q=label:%22label+old%22), user can do a 4-click edit: (1) click label to filter for `label:"label old"`, (2) click to select all, then (3&4) click twice in the _"Label" action drop-down_ to bulk edit to remove `label old` and removing `label new` on every issue at once.

![Screen Shot 2019-11-14 at 10 55 13 PM](https://user-images.githubusercontent.com/305339/68913521-f1381d80-0731-11ea-9db5-d3740eb65958.png)

**Comment by benhylau** [comment]
This sounds fine to me as a starting point. In the future it's possible we'd want one repo to have more labels, but I think we shouldn't worry until that happens. Right now, `organizing` has the best set of labels.

**Comment by dcwalk** [comment]
Chatted 2020-01-29 gov / ops, will closeout last todo in handbook issue, in comment at top
