### ISSUE TITLE
Small tasks: General

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#147]
The point of this task is to help get one-off small tasks that arise from other convos (PR review comments, chat, etc) into our task tracker.

This issue is intended to move between "To Do" and "Doing" in our tracker, never "Done". There shouldn't be a need to close it, even when all todos are temporarily fully checked off. It could be labelled and assigned as appropriate to the active tasks.

One-offs could be upgraded to full issues if desired. Also, multiple "small task" issues might be useful in the future, e.g., "Small tasks: Finance"

(Meta comments are welcome here on this proposed use of an eternal issue.)

# To Do

- Cultivators for 2021
  - [x] Jan @uditvira 
  - [x] Feb @patcon 
  - [x] Mar @YurkoWasHere 
  - [x] Apr @dcwalk 
- [x] All-hands cultivators until AGM 2020
  - [x] Jan @uditvira 
  - [x] Feb @patcon 
  - [x] Mar ~~@dcwalk~~ @benhylau
  - [x] Apr ~~@benhylau~~ @dcwalk
  - [x] May (first 2 weeks) @YurkoWasHere 
  - [x] May (last 2 weeks) @garrying 

- [x] el to revise due dates and scope of each task on here https://github.com/hyphacoop/organizing/milestone/1

# Done

- [x] finance: bank management
  - [x] ~~set $200 threshold on Desjardin multisig requirement https://github.com/hyphacoop/handbook/pull/22#discussion_r338448162 -- @yurkowashere~~ https://github.com/hyphacoop/organizing/issues/147#issuecomment-555644337
  - [x] call in to update Disjardins info
    - [x] Add `RD`
    - [x] `BUREAU` => `UNIT`
    - [x] `INC` => `INC.`
    - [x] add space into `UNIT1234` (no priority)
- [x] update hypha.coop WHOIS from `Hypha Workers Cooperative Inc` to `Hypha Worker Co-operative Inc.`
  - contacted nic.coop, who says [our registrar](https://link.hypha.coop/inventory#Hover) should be the ones to update this
  - needed to do update over Hover's support chat
  - [x] update https://link.hypha.coop/migrations to reflect current state
- [x] ~~finance: set up TransferWise~~ (re-ticketed to https://github.com/hyphacoop/organizing-private/issues/4)
  - [x] create business profile -- @benhylau 
  - [x] create personal profile: benhylau 
  - [x] create personal profile: patcon
- [x] update DigitalOcean billing address -- @patcon 
  - [x] updated field in [settings](https://cloud.digitalocean.com/account/billing?i=9f28a7)
  - [x] added record to https://link.hypha.coop/migrations spreadsheet
- [x] added "feedback required" column to task board -- @patcon 
- [x] dc email: [Investment Readiness Program](https://irp-ppi.ca/en) >> Co-op developers should also register as expert-service providers. 
- [x] send account information to Stripe @benhylau  
- [x] add Paypal and Stripe to [inventory](link.hypha.coop/inventory) @benhylau  
- [x] set up [CRA My Business auto-deposits](https://accesdc.mouv.desjardins.com/web/oel/v1/inscriptions-depot-direct-entreprise-arc/instructions)
- [x] increase credit card limit to $3,000
- [x] pay Oct NL bill with credit card
- [x] @hyphacoop/finance-wg update TW banking info for USD
- [x] @hyphacoop/finance-wg submit 2020 year-end forms through Wagepoint (before Feb 14)
- [x] @hyphacoop/finance-wg remit Q4 2020 HST
- [x] @hyphacoop/finance-wg report TWS 10%
- [ ] @hyphacoop/finance-wg missing journal entries for StART project in QB (ping Rodica)

**Comment by patcon** [comment]
Added something to update desjardins address info

**Comment by patcon** [comment]
@YurkoWasHere should this be your ticket? Feel free to self-assign, but if it's something I can do now, just lemme know! cc @hyphacoop/finance-wg

**Comment by YurkoWasHere** [comment]
- Address and name fixed
- I was told i CANNOT set a threshold for multisig 😒
- CC still Pending to early to tell.
- $5.00 transfer was to buy shares in the credit union. Returned when we close the account.

**Comment by patcon** [comment]
Re-ticketed multi-sig elsewhere, since an accountant told us about other solutions, for when this becomes important. We can move any convo there: https://github.com/hyphacoop/organizing/issues/151

**Comment by benhylau** [comment]
@hyphacoop/directors in setting up TransferWise, I need to provide name and date of birth of all directors. Is there a place we keep those and can I submit it?

**Comment by patcon** [comment]
Not that I'm aware of. Just to have a place, added an "employee database" here:
https://docs.google.com/spreadsheets/d/1LyElXvLj7ASclSPQqcgOnuEWqBWBStilEfOhIosZzhA/edit#gid=1143164818

Happy to migrate it elsewhere as soon as we determine where that should be!

**Comment by dcwalk** [comment]
added!

**Comment by patcon** [comment]
@benhylau re: TransferWise. Created my personal profile and awaiting invite for patrick.c.connolly@gmail.com

Thanks!

**Comment by benhylau** [comment]
Great @patcon let's go thru the invite process at the meeting today

**Comment by benhylau** [comment]
Couple small tasks that came up over last week:

- [ ] enter opportunities discussed in chat into CRM
- [ ] file nil RP remittance to CRA
- [ ] handling of work done over stat holiday
- [ ] summarize member bios

**Comment by benhylau** [comment]
From finance meeting:

- [ ] research legal requirements for expense coverage and how to pay them out
- [ ] handle Feb's nil payroll
- [ ] make sure we have all employees set up in wagepoint and have their SIN + TD1/TD1-ON
- [ ] work with projects to do timesheets and enter appropriate pay amounts
- [ ] polish Financial Planning sheet
-  [ ] email Rodica and WagePoint for advice on above

**Comment by benhylau** [comment]
@dcwalk @uditvira @patcon I want to work help y'all get timesheets in and invoices out. Can you ping me in Finance chat asap and plan to spend 30 min together?

**Comment by benhylau** [comment]
Our Twitter account currently has `opportunities@` when passbolt record says `members@`, and the login verification asked me to enter a number that is @patcon's personal number. I don't know if the latter is intentional because of SMS limitations with office number. Logging these here for Social Media role:

- [ ] Match Twitter email with record in passbolt
- [ ] Change Twitter phone number to office number?

@dcwalk we can probably wait till @patcon comes back for these.

**Comment by dcwalk** [comment]
@benhylau I don't think we can change twitter number to office VOIP -- usually needed for SMS verification

**Comment by benhylau** [comment]
From _2020-04-09 Hypha Worker Co-op: Business Planning_:

- [ ] @dcwalk: register us as IRP expert-service provider
- [ ] @dcwalk: join CWCF loomio

**Comment by ASoTNetworks** [comment]
- [ ] @YurkoWasHere Make a phone call with our VoIP number account

**Comment by benhylau** [comment]
For @benhylau from @hyphacoop/finance-wg, see: https://meetings.hypha.coop/2020-04-22-call-with-accountant.html

- [ ] Fix our payroll period
- [ ] Fix our payroll process docs

**Comment by benhylau** [comment]
From https://meetings.hypha.coop/2020-04-23-business-planning.html
- [ ] @uditvira do first pass of adding contacts
- [ ] @hyphacoop/business-planning-wg discussion on db/crm at upcoming meeting
- [ ] @benhylau put opportunities into hubspot
- [ ] @dcwalk investigate OpenCollective (as host and/or as org to recieve money)
- [ ] @hyphacoop/business-planning-wg joint bizdev and infra call
    - [x] @benhylau invite infra 30min call for honing product plan
    - [x] @dcwalk hold in calender
    - [ ] @dcwalk dig up template on money

**Comment by ASoTNetworks** [comment]
- [ ] @benhylau change Hubspot email to opportunities@

**Comment by benhylau** [comment]
From meeting with hank:
- [ ] @benhylau provide agreements for review

**Comment by benhylau** [comment]
From @hyphacoop/operations-wg call:
- [ ] @benhylau HST charged by subcontractor, how to handle?
- [ ] @benhylau dc asked to purge chat logs beyond certain point (purge 3mths?) bl to bring to @hyphacoop/infrastructure-wg 
- [ ] @dcwalk invite NL to C4C Slack
- [ ] @dcwalk update Hypha client agreement (with statement similar to NL's)
- [ ] @dcwalk: update independent + IP agreement (once working open statements is revised)

**Comment by benhylau** [comment]
For @hyphacoop/infrastructure-wg to discuss:

<img width="618" alt="Screen Shot 2020-05-12 at 9 04 30 AM" src="https://user-images.githubusercontent.com/2261308/81648869-afadd400-942f-11ea-9314-3d89ce56b292.png">

Can we switch to using @hyphacoop-bot to do these automated pushes rather than use someone's personal token? Seems odd :)

**Comment by dcwalk** [comment]
I'm finding it really hard to track small tasks inline, rather than if they are bubbled up to the top. I'm also finding things in here duplicated elsewhere (I'm pruning) or ones that should be spawned at a separate issue.

**Comment by benhylau** [comment]
@hyphacoop/finance-wg:
- [ ] add task to role about putting monthly bank statement into Drive
- [ ] settle aether invoice
- [ ] file today's meeting pad

**Comment by ASoTNetworks** [comment]
From @hyphacoop/infrastructure-wg call:
- [ ] @benhylau add summary of this to service reliability issue
- [ ] @benhylau email Sebastian to schedule call / over email

**Comment by benhylau** [comment]
- [ ] @ASoTNetworks create two emails:
  - `operations@` -> `operations@hypha.local`
  - `data@` -> `operations@hypha.local` and `infra@hypha.local`

**Comment by benhylau** [comment]
- [ ] @YurkoWasHere set up Paypal account (or find some way) to receive the $500 payment

**Comment by benhylau** [comment]
Finance tasks for @benhylau:

- [ ] update projection sheet before AGM
    - NET (before tax without HST)
    - cross-reference amounts with bank account (end of May balance should match our early-June)
- [ ] update handbook roles with documents that need to be uploaded
- [ ] upload wagepoint docs with ER breakdown
- [ ] ping Rodica about ER and HST reconciliations and May statements
- [ ] May payroll
- [ ] TransferWise USD -> CAD account and handle Aether invoices
- NL invoice
	- [ ] pay invoice by June 16
    - [ ] @YurkoWasHere take care of QB side reconcile
- AGM
	- [ ] financial statements
    - [ ] fiscal projections
 	- [ ] budget for next year
	- [ ] presentation of income/budget for last/next year (base on Rodica's)
	- [ ] @YurkoWasHere review above
- [ ] email CWCF re: CSWI

**Comment by ASoTNetworks** [comment]
- [ ] @YurkoWasHere pull together AGM infra presentation with help from el

**Comment by patcon** [comment]
Re: commits coming from me. https://github.com/hyphacoop/organizing/issues/147#issuecomment-627155167

Dealt with here: https://github.com/hyphacoop/handbook/pull/89

**Comment by YurkoWasHere** [comment]
> increase credit card limit to $3,000

Oct 8, 2020 - asked for cred increase of an additional $2,000 from $1,000 to $3,000 
will take 3-4 business days

Alternative - Overpay the visa by the amount we need, wait 48 hours and then we SHOULD be able to spend CREDIT + overpayment

**Comment by YurkoWasHere** [comment]
> set up CRA My Business auto-deposits

![image](https://user-images.githubusercontent.com/39072689/95476741-8e590180-0955-11eb-9f6e-2e8c666dee53.png)

**Comment by dcwalk** [comment]
this has not be updated in over a year. I am going to do something slightly radical and propose we ~close this~
