### ISSUE TITLE
Fill out survey of Canadian creative/digital co-ops

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#150]
## Shared Description

:speaking_head: **Loomio:** N/A  
:date: **Due date:** Fri, Nov 22, 2019  
:dart: **Success criteria:** ...  

Email:

> Hello Canadian co-operatives,
>
> We need your co-op’s help!
>
> I’m a professor at Wilfrid Laurier University in Waterloo, Ontario researching co-operatives in the cultural, technology, and media industries. You may have already received a survey invitation from a member of our research team. 
>
> Our multi-country research aims to raise the profile of the co-op sector and identify co-operative challenges and opportunities in the arts, media, and technology fields. We want to have a wide cross-section of Canadian co-ops participate so the results better represent the sector. Sharing the survey results with policy makers and co-op associations will inform strategies to strengthen the co-op model.
>
> We would greatly appreciate it if you would complete the survey to ensure your co-op is represented in the results. (The survey will take about 20 minutes to complete.) The survey closes on Friday, November 22, 2019.
>
> You can access the survey here: Co-operatives in Creative Industries Survey
>
> Thank you in advance for your time and support.
>
> All the best,
> Greig 

## To Do

- [ ] confirm no one else working on it
- [ ] Fill out survey: https://wlu.ca1.qualtrics.com/jfe/form/SV_beAGRDc7SAfXPLf

**Comment by patcon** [comment]
Is anyone else working on this?

**Comment by dcwalk** [comment]
The deadline passed for this
