### ISSUE TITLE
Create app to coordinate an org-wide repo subscription/watch strategy

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#152]
Re-ticketed from https://github.com/hyphacoop/handbook/pull/29

## Shared Description

:speaking_head: **Loomio:** N/A  
:date: **Due date:** N/A  
:dart: **Success criteria:** We have a satisfactory way to collectively define repo "watch" norms.

This is so low priority that I'm not sure what to do with it. But parking it here. (Maybe we should have a whole separate repo for these la-la land sorta blue-sky ideas.)

**Problem:**
- :heart: I feel that some people seem overwhelmed by Hypha's GitHub notifications.
  - :heart: I feel that this over-notification makes people unresponsive to the truly important ones.
- :mag: [Repo auto-watching](https://help.github.com/en/github/receiving-notifications-about-activity-on-github/watching-and-unwatching-repositories#watching-all-repositories-that-you-have-push-access-to) makes it so that you automatically watch repos you get push access to.
  - :mag: This feature is an individual setting, as opposed to org-wide.
  - :mag: A repo/org can't directly change as user's watch settings.
  - :mag: Auto-watch is on by default.
  - :heart: People might like auto-watch to be on for other GitHub activity.
- :mag: [The `notifications` GitHub oauth scope](https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/#available-scopes) allows an app to watch/unwatch repos on behalf of user.
- :heart: Centrally setting repo watch policies allows us to collectively consense on a strategy, and not continually pester people to align with it.
  - :heart: We can also change our strategy in the future, and make it more fine-grained than "always watch all new repos" vs "never watch new repos".
- :bulb: Let's create a one-page app for letting all authorized users set a policy on which `hyphacoop` repos are watched/watched amongst themselves, and this would sync between everyone.

## To Do

- [ ] discuss (faraway; no priority)

**Comment by garrying** [comment]
Closing this. infra-wg discussed the implications of an app to help with notifications; gonna revisit in a new issue if this becomes a point of friction.
