### ISSUE TITLE
Consider renaming riot chat rooms

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#153]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** We have channels labelled something that we can all live with.  

Going to try this here, but if someone thinks it would be better in Loomio, just say so.

# Proposal

- :heart: I feel the current names are a bit over-prescriptive, misleading, and side-step a conversation that hasn't had time to be learned through experience.
- :heart: I feel "internal" suggests too broad a scope, and so most internal day-to-day convos end up there by default.
- :heart: I feel that "public" makes it feel like it's intended for talking with some ambiguous public audience.
- :bulb: Let's rename `hyphacoop:public` to `hyphacoop:open`.
- :bulb: Let's rename `hyphacoop:internal` to `hyphacoop:private`.

cc: @hyphacoop/governance-wg 

## To Do

- [x] seek feedback
- [x] renamed `#hyphacoop-internal` => `#hyphacoop-private` ("hyphacoop:private" human friendly)
- [x] renamed `#hyphacoop-public` => `#hyphacoop-open` ("hyphacoop" human friendly)

**Comment by benhylau** [comment]
I would suggest `hyphacoop:public` -> `hyphacoop` but flexible and generally okay with this rename.

**Comment by patcon** [comment]
Sounds good! Note that the "public" suffix was there by design to hint that 1) this wasn't the only hypha channel, and 2) this channel is non-privileged.

I made the change so the the human-friendly name is "hyphacoop", but the slug in the url is `#hyphacoop-open:tomesh.net`

Happy to revisit. Going to close unless other comments come in
