### ISSUE TITLE
Treat staff as full employees (both owners and future non-members)

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#159]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** https://github.com/hyphacoop/organizing/issues/156  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** We understand and can move forward in treating all member-owners as employees.  

This is a place to collect issues and things we'll need to do before we are ready to meet employee standards. Right now, we can consider ourselves "owners", and skirt some of the requirements. [?]

We'll need these in place before we can hire our first non-member employee, but could aspire to put them in place before that point.

## To Do

- Workplace Safety and Insurance Board (WSIB)
  - [ ] research WSIB requirements https://github.com/hyphacoop/organizing/issues/123
  - [ ] register with WSIB
    - must be done within 10 days of hiring first employee [(ref)](https://learn.marsdd.com/article/setting-payroll-ontario/)
- [ ] ...

**Comment by patcon** [comment]
> Right now, we can consider ourselves "owners", and skirt some of the requirements. [?]

gut-check on this, @dcwalk, as I suspect this might be one of the things I keep misunderstanding.

**Comment by patcon** [comment]
Maybe we could treat this as a milestone?

**Comment by dcwalk** [comment]
@patcon Almost positive we don't have to register with WSIB as we're an exempt industry (Soft Dev and Computer Services): https://www.wsib.ca/en/employer-classification-manual/software-development-and-computer-services


So we'd have to decide whether we want to register. A major factor will be consideration of Premiums: https://www.wsib.ca/en/businesses/premiums-and-payment/premiums-and-payment

Also, to be clear having WSIB isn't the same thing as meeting our OSHA requirements, just FAI.

---

> > Right now, we can consider ourselves "owners", and skirt some of the requirements. [?]
> 
> gut-check on this, @dcwalk, as I suspect this might be one of the things I keep misunderstanding.

We're using language of "founding members/employees" per conversations with other co-ops. That means we're not tied to recognition of other means to recognize permanent employee status (this is documented in handbook here https://handbook.hypha.coop/co-operative.html#about-us)

I don't treating us as "owners" has been formalized, and I don't think we've been setting up that way. My understanding of goal is codified in handbook: membership, and employees.

**Comment by dcwalk** [comment]
@patcon also not totally sure about this framing/language of this issue -- we're doing all this as part of set up, but this implies we're not acting on stuff.

**Comment by patcon** [comment]
Closing this, as I was mistaken and didn't realize this was locked in already via handbook page :slightly_smiling_face: 

(I remain unclear how this conversation on employee status progressed. Happy to catch up [much] later to resolve the apparent knots we've both had in our stomachs over this communication breakdown.)

**Comment by dcwalk** [comment]
Moving the WSIB stuff over into #123
