### ISSUE TITLE
Register for Employer Health Tax (EHT)

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#160]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** We are collecting and paying EHT.  

We don't need to do this until we approach the exemption limit of $490,000/yr in payroll.

## To Do

- [ ] gather [required information](https://www.fin.gov.on.ca/en/tax/eht/faq.html#Q1)
- [ ] call the ministry of finance: 1 866 668‑8297
- [ ] ...

**Comment by benhylau** [comment]
When we hit $490,000 we'll revisit.
