### ISSUE TITLE
Monitor our hosted infrastructure

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#172]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** [chat](https://matrix.to/#/!cAjsRgDfbXqdpIHfTt:tomesh.net/$VYpdJwP06AksSEm5e6_MhnEQOZb_hMq7Nc_FXpiETQI?via=elon.li&via=tomesh.net)
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...   

It came up in chat that we eventually should have a way to monitor servers and applications, especially if we're interested in hosting our own services and offering hosted services to others.

## To Do

- [x] Decided on platform

cc: @hyphacoop/infra-ops-wg

**Comment by patcon** [comment]
## Summary from chat convo

- :bulb: Let's use monitoring so we can fix things that break before others are inconvenienced. -- @ASoTNetworks :+1: @patcon 
- :mag: @YurkoWasHere is familiar with **Nagios**, and has written plugins
  - :mag: @ASoTNetworks has used it. @patcon just demo'd it.
  - :heart: Nagios plugin ecosystem is vast.
  - :heart: Very customizable. (@YurkoWasHere)
  - :heart: I feel it's complicated and not very user-friendly. -- @YurkoWasHere 
  - :mag: Initial release: 2002
  - :mag: GitHub: 740 stars | 51 contributors | 285 forks
  - :mag: can be configured via `nagiosql` (@YurkoWasHere)
  - :heart: has nice-looking views -- @YurkoWasHere 
  - :heart: I feel like it's a pain to configure. :+1: @patcon, @YurkoWasHere, @ASoTNetworks 
  - :mag: poll model. [:question:](https://tomeshnet.github.io/p2p-internet-workshop/articles/module-5/presentation/#8)
  - :heart: I feel that Nagios tries to do everything due to its enterprise development pressures.
  - :mag: can do escalating alerts -- @YurkoWasHere 
  - :heart: I like nagios bc you can define what "does not work" means -- @YurkoWasHere 
- :mag: @ASoTNetworks is familiar with **Zabbix**
  - :mag: poll model.
  - :mag: @YurkoWasHere and @patcon have never used it.
  - :mag: GitHub: 684 stars | 2 contributors | 230 forks
  - :mag: Initial release: 2001
  - :mag: Zabbix uses an agent.
    - :mag: @ASoTNetworks has [scripts to install/configure them](https://www.aseriesoftubez.com/files/scripts/zabbix-agentd-4.0_install.sh)
- :heart: Zabbix and Nagios are considered enterprise tools, and are very mature.
- :heart: Newer monitoring tools are built for configuration-in-code philosophy, and state is stored/loaded from readable files.
- :mag: **Prometheus** is a more recent entrant in monitoring space.
  - :mag: poll model. [(but can push too)](https://prometheus.io/docs/introduction/faq/#why-do-you-pull-rather-than-push)
  - :mag: Prometheus was architected from the beginning with configuration management in mind.
    - :mag: configuration is via YAML files.
  - :mag: Used by CoreOS, Docker, DigitalOcean, Soundcloud
  - :mag: [Used by Toronto Mesh.](https://prometheus.meshwithme.online), with [linked grafana instance](https://monitor.meshwithme.online) for pretty data visuals.
  - :mag: Initial release: 2013
  - :mag: GitHub: 28,000+ stars | 423 contributors | 4,200+ forks
- :mag: Some newer platforms are backward-compatible with Nagios plugins.
- :heart: Monitoring does not feel like urgent need -- @patcon @YurkoWasHere 
- :mag: [`crazy-canux/awesome-monitoring`](https://github.com/crazy-canux/awesome-monitoring) is the most comprehensive awesome list for monitoring
- :mag: `dastergon/awesome-sre` has a section for [Monitoring & Observability & Alerting](https://github.com/dastergon/awesome-sre#monitoring--observability--alerting)
- :heart: I feel like Prometheus is the monitoring tool we should eventually use. -- @patcon 
- :mag: Prometheus, Nagios, Zabbix can all do alerts.
- :heart: @ASoTNetworks is a bit mistrustly of "devops" perspectives bc has heard it fails to value security.
  - :heart: @patcon concedes security and access can be at odds in the devops community convos.
- :heart: @YurkoWasHere doesn't care what we use for monitoring.
- :heart: I feel ok to use zabbix, but we'll likely revisit. -- @YurkoWasHere :+1:  @patcon 
- :bulb: Things we could monitor:
  - matrix server load
  - jitsi load and non-hypha usage
  - status of all our circleci/travis/github build jobs

**Comment by YurkoWasHere** [comment]
Added some monitoring with existing Nagios instance

**Comment by YurkoWasHere** [comment]
Continued on issue https://github.com/hyphacoop/organizing/issues/276
