### ISSUE TITLE
Research how to handle out-of-province employees

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#180]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

Unfortunately, due to personal matters, I find myself tentatively considering living outside of Ontario :crying_cat_face: The most likely destination is Saint John, New Brunswick, but USA is also a possibility. This will need discussion on whether it's worthwhile, but I've started doing research and sending some emails.

## Open Questions

- Do any others find themselves in comparable situations of considering out-of-province employment with Hypha?
- Is this complication worth maintaining employment/owner relation through?

## To Do

- [ ] share findings from email conversations
- [ ] ...

cc: @hyphacoop/governance-wg

**Comment by benhylau** [comment]
Revisit when we have need. Out of country folks will start as contractor.
