### ISSUE TITLE
Hypha Personal Inbox

### ISSUE THREAD

**Issue by ASoTNetworks** [hyphacoop/organizing#193]
## Task Summary

🎟️ **Re-ticketed from:** [#131](https://github.com/hyphacoop/organizing/issues/131)  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** All members will have their own email inbox that they can choose how to use them.  

In the January 20th Infra meeting we decided to proceed with making inboxes for all members.

Each member can choose their email handle for their [at]hypha.coop email.

## To Do
- [x] Collect email handles from all @hyphacoop/member-workers
- [x] Create mailboxes
  - [x] benedict@
  - [x] yurko@
  - [x] dc@
  - [x] udit@
  - [x] garry@

**Comment by benhylau** [comment]
`benedict@`

**Comment by darkdrgn2k** [comment]
yurko@

**Comment by YurkoWasHere** [comment]
yurko@

**Comment by dcwalk** [comment]
dc@

**Comment by patcon** [comment]
patcon@

**Comment by uditvira** [comment]
udit@

**Comment by patcon** [comment]
- ben suggests documentation for someone else to set up a mailbox for someone else
  - handbook for non-priv, and private repo for anything sensitive

**Comment by garrying** [comment]
garry@

**Comment by dcwalk** [comment]
@ASoTNetworks are these done? Can we close this issue out?

**Comment by ASoTNetworks** [comment]
Everyone now have their own mailbox.

**Comment by patcon** [comment]
Note that docs are a final piece of this, and @ASoTNetworks and I are working on them here: https://github.com/hyphacoop/handbook/issues/54
