### ISSUE TITLE
Revisit our organizational values

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#234]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** Aug 2020? (one year since incorporation)  
🎯 **Success criteria:** We're reviewed our organizational values and approved changes if appropriate.  

I assume revisiting our values is something we'll do every so often. Started this issue as placeholder for later conversations about values we might want to add, remove or modify.

This might relate to #102 

## To Do

- [ ] ...

**Comment by patcon** [comment]
Potential value to consider/discuss: messiness (or similar)

https://www.econtalk.org/tim-harford-on-the-virtues-of-disorder-and-messy/

**Comment by dcwalk** [comment]
Nice example of translating values to practice: https://weareholon.gitbook.io/handbook/governance/who-we-work-with

**Comment by dcwalk** [comment]
I'm going to close this for now as it is essentially defined as a placeholder initiative. I'm sure we will revisit values, but lets wait until we know when & how to better frame an issue. Reopen if you feel I've closed this in error.
