### ISSUE TITLE
hypha.coop Expiring

### ISSUE THREAD

**Issue by ASoTNetworks** [hyphacoop/organizing#244]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** April 23, 2020
🎯 **Success criteria:** Domain renewed  

hypha.coop is expiring on April 24, 2020 and needs to be renewed.

## To Do

- [ ] Make sure domain is renewed.

**Comment by benhylau** [comment]
Isn't it auto? It really should be.

**Comment by ASoTNetworks** [comment]
I just checked it is set to auto-renew but linked to a Paypal so not sure if it will renew on its own.

**Comment by YurkoWasHere** [comment]
Configured for my paypal account
