### ISSUE TITLE
Improvement to payroll process

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#255]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** July 2020  
🎯 **Success criteria:** Improve payroll process based on feedback  

...

## To Do

- [x] Gather feedback
- [x] Discuss changes
- [x] Implement changes

**Comment by benhylau** [comment]
We haven't implemented proper financial controls yet, so there is currently no standard process to cross-check whether payroll amounts entered by project leads match the invoiced amounts, and this is especially hard for Finance to cross check bc of misalignment of billing vs. payroll cycles.

**Comment by dcwalk** [comment]
I've mentioned in chat before -- as PM for client projects I've wound up doing a lot of what feels like payroll and finance tasks:
- verifying hours in clockify
- calculating invoiced v. payroll amts (many strange formulas)
- preparing invoices

I could see it being easier for a payroll person to do a portion and finance WG to cover the other half. Tapping on a PM to check before the cutoff

**Comment by YurkoWasHere** [comment]
> verifying hours in clockify
Not sure how accounting can be "verifying" this as they have no idea what was worked.
In the future i can see using some API to maybe pull these numbers in a easier manner.

> calculating invoiced v. payroll amts (many strange formulas)

Sheet calculation is `(Amount Billed * -0.25)+Amount Billed`
Which can be simplified to `Amount Billed * (1-0.25)`
Everything else should be automatically calculated.

is there something specific that trips you up?

> preparing invoices

There maybe nuances on how things are reported on invoices that are not straight forward especially when dealing with FIXED RATE PROJECTS as internal hours != invoice hours.

**Comment by benhylau** [comment]
@dcwalk can you let us know where you see Finance may be able to fill in?

>verifying hours in clockify

Finance does not know how the project decides to map `hours -> wage`. For example, StART had some hours that were tracked but not billed in the beginning, and the two members working on Qm has a way of assigning wage that doe not map to hours spent.

We cannot just take Clockify data and make assumptions for payroll.

>calculating invoiced v. payroll amts

The current payroll form asks for two fields from each Member:
- Hours
- Amount Billed

See: _Employees must fill out this sheet (green cells) before the 7th of each month to indicate the hours and amount they have billed in the month prior._

The payroll amount automatically shows up on the same sheet, broken down into [ Regular / Current Pay, Public Holiday Pay, Vacation Pay, Earnings Totals ] as will appear on your pay stub. This is not a responsibility of the PM.

Are you currently doing something manual to arrive at these numbers?

>(many strange formulas)

There is no formula involved at any point of the payroll process that the PM needs to be aware of.

If a member has two (or more) projects, they currently have to _sum_ those two together for both `Hours` and `Amount Billed`. This could be separated out in a future process if it's useful.

>preparing invoices

Projects (e.g. StART, Aether) have their own billing cycle and items on the invoice are quite custom and may change over time. How would you like this information communicated to Finance and approval process for sending?

Note that currently Finance is responsible for monitoring and notifying PMs of invoice collection status, and if foreign currency Finance takes care of moving money around and converting so the money is ready for next payroll. PM's responsibility ends after invoice is prepared and receiving a confirmation from Finance.

**Comment by dcwalk** [comment]
The process I do per INVOICE or INVOICE/PAYROLL cycle:
- Go into clockify and [initially] create and save reports per project per person **this could be done by Finance**
- Generate a clockify report per project and per person, upload it to the gdrive   **this could be done by Finance**
- Add hours to project spreadsheets in prep for Invoicing    **this could be done by Finance**
- Then do the following:  **this seemingly done by PM**
  - ensure rounded total doesn't drift (tho not much of a concern), ensure in line with previous amts/agreement with client, do prep for upcoming payroll if different than monthly, or split hours appropriately
  - if needed, consult with project members
- Create invoice in quickbooks and add information, review and ensure matches above   **this could be done by Finance**
- Send invoice    **this could be done by Finance**
- Add payroll hours/amt to final sheet   **this could be done by Finance**

PM has to be involved but could easily switch to a review process rather than driver of most of these steps, which are touching finance systems.

----

> Projects (e.g. StART, Aether) have their own billing cycle and items on the invoice are quite custom and may change over time. How would you like this information communicated to Finance and approval process for sending?

- I as PM have a list of a number of future invoice dates, currently in a sheet per project, these could be in a single place that the Finance WG maintains.

> The current payroll form asks for two fields from each Member:
> 
>     * Hours
>     * Amount Billed
> 
> See: _Employees must fill out this sheet (green cells) before the 7th of each month to indicate the hours and amount they have billed in the month prior._

- There is no way for members to arrive at this number of projects where multiple people are working without coordinating across those projects (e.g., StART and Qm)

> Are you currently doing something manual to arrive at these numbers?
 
No

> > (many strange formulas)
> 
> There is no formula involved at any point of the payroll process that the PM needs to be aware of.

I'm referring to the work to get to putting those two numbers into the payroll sheet. I think there is a misconception that payroll "begins" from those numbers. It takes work to get to those numbers

**Comment by benhylau** [comment]
>- Go into clockify and [initially] create and save reports per project per person this could be done by Finance

Yes Finance can do this, though it's a one-time setup cost.

These following steps can be automated as @YurkoWasHere mentioned, hitting Clockify APIs to create intermediate assets to assist in PM's job:

>- Generate a clockify report per project and per person, upload it to the gdrive this could be done by Finance
>- Add hours to project spreadsheets in prep for Invoicing this could be done by Finance

Required input would be _invoice cycle_ and _payroll cycle_. Still that doesn't take care of irregular invoice cycles, as in the case of Aether.

I noticed you said "hours" only, which is correct as the mapping from `hour -> wage` is project-specific.

The "project spreadsheets" does not yet exist within the Finance WG domain. This will be a new asset that needs to be created as part of the standard of adding a new project. This also creates a handoff point where "PM awaits project spreadsheet ready" each month, and if it's handled by automation that's fine, but it may create more communication overhead if manual.

>- Create invoice in quickbooks and add information, review and ensure matches above this could be done by Finance
>- Send invoice this could be done by Finance
...
>-I as PM have a list of a number of future invoice dates, currently in a sheet per project, these could be in a single place that the Finance WG maintains.

So the ask here is for Finance to send invoices on behalf of projects according to a schedule set by each project, by referencing the "project spreadsheet" intermediate asset.

I think it's necessary that before we invoice, both the PM and the Finance Steward has a chance to look at the invoice. @dcwalk do you agree? Your suggestion is Finance prepares, then pings PM for review of a preview, then send? I think this is possible if "project spreadsheet" contains all the information necessary to populate the invoice, so perhaps this is the next step for Finance to "expand" its service to.

>- Add payroll hours/amt to final sheet this could be done by Finance
...
>- There is no way for members to arrive at this number of projects where multiple people are working without coordinating across those projects (e.g., StART and Qm)

Yes this was intended for the Member to calculate and populate themselves. PM really should email project members each month, they can individually sum up their numbers and add to the sheet. You are doing it now just bc you happen to PM both projects.

If we have "project spreadsheet", it can output **per person per project** wages for each payroll, then in the payroll sheet it just does summation across all the projects. @YurkoWasHere this would be another pivot table sort of thing.

>- I'm referring to the work to get to putting those two numbers into the payroll sheet. I think there is a misconception that payroll "begins" from those numbers. It takes work to get to those numbers

It don't have that misconception. Finance hasn't seen enough projects yet to centralize that work, we are fully aware that it exists (e.g. calculating that weird offset with StART, having tracked but discounted hours) these are things that we are learning as we go. This is why this ticket is set to due in July, because we need some time to observe the variation across projects.

I think here is a clear proposal, which requires work and has its own risks, and I still believe we need to watch another 2 months for other parts of invoicing / payroll to stabilize (e.g. the new passthru payment for subcontractor that bypasses the clip). Is the July timeline for an improved process of "full service payroll" reasonable to you @dcwalk?

Lastly, is there something Finance can do in the meantime the can be a drastic improvement for your experience?

**Comment by dcwalk** [comment]
> Yes this was intended for the Member to calculate and populate themselves.

I'm telling you this isn't always possible, esp with how we are handling Qm,

> This will be a new asset that needs to be created as part of the standard of adding a new project.

I have already created this to manage the projects I'm PMing, could just adapt that

> This also creates a handoff point where "PM awaits project spreadsheet ready" each month, and if it's handled by automation that's fine, but it may create more communication overhead if manual.
 
I don't think that automating everything is required/desirable. It's payroll and dealing with money, it seems like human overview is important. I'm not sure about communication overhead being an issue and would rather iterate on a process to improve and assess that overhead. Right now we have other communication overhead but it is "directed" the other way, initiated by PM

> It don't have that misconception. 

The comment as recently in the chat listed only steps that happen at the stage of putting numbers into the payroll sheet. So I'm not sure what term is better here if "misconception" is inappropriate, it seems to be something that is not being addressed until now, despite me bringing it up before.

**Comment by dcwalk** [comment]
Picking up this in advance of next cycle:

> Lastly, is there something Finance can do in the meantime the can be a drastic improvement for your experience?

If Finance can handle the invoicing for two projects and ensuring/reviewing the payroll numbers get added once I do the calculations in the project sheets that would cut labour in half. I can ping in chat mid-day June 1 once I have done my parts.

**Comment by benhylau** [comment]
Yup if you give me date to send each invoice, with spreadsheets indicating amounts, and timesheets, I can create the invoices for you to review then send on ^ date

**Comment by benhylau** [comment]
Moving forward, Finance would need as input a sheet with the following headings:

Moving forward, can Finance get a sheet with these as headings:

| Service date | Description | Qty | Rate | Amount | Sales tax (one of HST ON, zero-rated, exempt, out of scope) |
|:---|:---|:---|:---|:---|:---|

I think these can be integrated into the project calculation sheets, but have a block that is colour-coded to `light purple 3` containing those values, and within the invoicing range, that I can directly transfer to the invoice.

Some parts were confusing to me in the previous run:

- in one invoice I take only one row, even though the sprint duration seems to have changed from previous invoices so I wasn't sure if that required further breakdown on my end
- values in the row need to be listed as separate line items in the invoice
- in another invoice I wasn't sure which items are to be included, but that's clear from the previous invoice
- I had to construct the descriptions based on previous invoice
- `qty` being taken from the Notes column in the spreadsheet instead of the highlighted column is counter-intuitive

I think standardizing and colour-coding, but allowing the data to stay on the same project-accounting sheet, will address all these issues without adding much work, so that's my proposal. If there are changes to other things, like payment terms, those can be communicated out-of-band.

**Comment by benhylau** [comment]
@dcwalk pls see above comment. I really need _all_ the above fields in the source document you provide me in order to generate invoices.

**Comment by dcwalk** [comment]
I can't add all those fields exactly to the existing way we track hours (esp. qty) especially for multi-line invoices. I've amended to reflect them in the sheets tho

**Comment by benhylau** [comment]
I think the process now is better than before.

The next step is to break out wages per person per project, as are looking at per project tracking to assign expenses to specific restricted funds such as grants and retainers.
