### ISSUE TITLE
Host design jam x2 to refine internal look and feel

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#272]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** start: after AGM   
🎯 **Success criteria:** Have developed look and feel for our internal spaces. 

Building on #77 and coming out of convo in `1010-04-23 bizdev call`, we wanted to carry the visual look through handbook and chat

## To Do

- [ ] (after AGM) have discussion abt current icons in chat and look and feel 
- [ ] jam on ideas for handbook + chat

**Comment by patcon** [comment]
@dcwalk suggested potential revisit with upcoming addition of blog in Q1

**Comment by patcon** [comment]
`2021-02-25` meeting. Will re-ticket when we have time for this. Closing.
