### ISSUE TITLE
File "2019-02-13 Toronto Workers Co-op: ON Co-op Assoc Call"

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#28]
Add this doc to GitHub: https://hackmd.io/zKOQ2bYNS1qO0vFdmpInug

**Comment by patcon** [comment]
Good call. Since it's external, I'll ping Peter real quick to confirm it's ok. Thinking we could file it in `informational-interviews/` after we merge #42

**Comment by patcon** [comment]
Just sent email now. Waiting to hear back. cc @dcwalk

**Comment by patcon** [comment]
Peter gave it the ok. Will do when I'm on desktop, or pls do beat me to it

**Comment by patcon** [comment]
Closing in favour of #49 PR
