### ISSUE TITLE
Quickbooks Support for Recording Unpaid Bills

### ISSUE THREAD

**Issue by YurkoWasHere** [hyphacoop/organizing#305]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** Decide if we need to be using bill to record payable invoices, if so upgrade QB.

...

> Vendor suppliers that extend credit to you will send you a bill that should be paid by the due date indicated on the bill. In order to stay on top of these unpaid bills, you need to enter them into QuickBooks. By entering bills into QuickBooks, you can stay on top of your accounts payable balances. One of the many reasons why business owners purchase QuickBooks is to gain better control over their expenses.

To keep track of Accounts Payable Liability (What we owe) you usually enter the BILL/INVOICE into quick books when it comes in.

Then when it is paid, it gets marked paid and lowers the Accounts Payable account

The version of Quick Books Online does not support BILLS and requires an upgrade ($15 more per month)

![image](https://user-images.githubusercontent.com/39072689/84459118-a5504700-ac34-11ea-97b9-dc50aeb010ad.png)

---

Questions:

Do we need to keep track of our APs in this manner? Is so we should upgrade.
  - Do we want to
  - Do we have to from accountant's perspective

**Comment by benhylau** [comment]
We should upgrade because for $15 more/month:
- Receive invoices & match outgoing payments (we need it)
- Wagepoint integration -> save us time
- Multi-currency -> USD bills (save us time)
- Now we may also be able to integrate TransferWise with QB

**Comment by benhylau** [comment]
Approved at All Hands. @YurkoWasHere can you take care of upgrading and file the invoices from NL?
