### ISSUE TITLE
Quick books - Receive payment without invoice

### ISSUE THREAD

**Issue by YurkoWasHere** [hyphacoop/organizing#306]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** Confirm how to deal with money received for unvoiced work done ~~and confirm how to handle if the work was done before HST (but entered now)~~

Source:
https://quickbooks.intuit.com/learn-support/en-us/payments/recording-income-without-invoice/00/243021

Enter money as Sales Receipt
- Do we need to enter the customer for 1 offs?
- Services where never invoices
- ~~Collect HST?~~ - This is a Grant - no HST required.
  - ~~Services preformed before HST~~
  - ~~Money received now~~
  - ~~How to deal with HST (do we have to pay it?)~~ 

## To Do

- [x] Check with accountant

**Comment by benhylau** [comment]
This should be treated as a [grant](https://handbook.hypha.coop/finance.html#gsthst-rt) and is not eligible for HST and also not require an invoice. I will email Rodica on how to do QB.

>**Hypha receives a grant from a private company to facilitate a free digital security workshop that is open to public, and spends $100 on materials.**
>
>- HST does not apply, and we do not need to collect or remit GST/HST on the grant amount
>- The $100 materials is not eligible as ITC because the grant is GST/HST exempt (different from zero-rated)

**Comment by YurkoWasHere** [comment]
Being a grant takes care of the HST component, thanks for clearing that up.

**Comment by benhylau** [comment]
In QB, from Rodica:

>You can record it as miscellaneous income with HST- out of scope.

**Comment by benhylau** [comment]
@YurkoWasHere we can discuss this at Finance WG call to make sure everything is clear on this grant/honorarium and for future.
