### ISSUE TITLE
Create a plan for how Hypha will counter anti-black racism and white supremacy

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#311]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** conversation in chat
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** Member sign-off on a plan including concrete actions.  

This comes from a much earlier conversation in [our private chat :lock:](https://matrix.to/#/!JloFJtoONurMdgcZCa:tomesh.net/$1591498566547CWMvx:tomesh.net?via=networkedserver.net&via=tomesh.net&via=elon.li):

> Hi folks, it came up briefly in our last meeting but I've been reflecting on and thinking about anti-Black racism and white supremacy the past few days, I'm sure alongside others here, and in particular focusing on the ways that these operate in technology, open source, and design professions and the ways I am complicit in them as a white woman.
> 
> Given Hypha's values (including anti-racism and anti-oppression: https://handbook.hypha.coop/vision.html) this feels like a topic for more discussion. It feels important to acknowledge these issues on Wednesday and meaningfully engage in **thinking about concrete action we can take to dismantle the racism operating in the our communities.**
> 
> I've been inspired by the #DesignAsProtest call out to designers and architects (their form for direct action ideation and a tweet with their calls linked) as well as the anti-racism design resources they pulled together
>
> https://twitter.com/BCLeeJr/status/1268291920759054336/photo/1
> 
> https://docs.google.com/document/d/e/2PACX-1vRkuF9o4WDiRW8v2nAPfJRttbZty5MADnFCt38PC4JPbqWMr4VrT307fzz5uAcYupTaWVwTrz-N8pUb/pub
> 
> https://docs.google.com/forms/d/e/1FAIpQLSdzWFz0ekMzq0tzN1dMFW4fxghkui5fg7FWyzXH1hBSKyUi1A/viewform
> 
> So I guess my thoughts are, how can we consider these issues with care, but also move in a timely fashion to consider these questions and others arising:
> 
> - How can we uplift the voices of those above and other Black-led designers and organizations grappling with the theme of values and tech work in technology design?
> - How can we acknowledge the specific issues of anti-Black racism that we must be tackling in design fields, open source, and technology design?
> - How can we ADJUST OUR PRACTICES to challenge anti-Black racism and dismantle white supremacy?

## To Do

- [x] have initial conversation at all hands
- [ ] have more in-depth discussion
- [ ] ...

**Comment by benhylau** [comment]
@patcon and I joined the CWCF call on this, there should be a follow-up call in a week or so.

**Comment by dcwalk** [comment]
Just pasting in some links/resources:
- CWCF statement https://twitter.com/WorkerCoop/status/1269440916130902016
- OCAP statement https://ocap.ca/statement-supporting-black-indigenous-people-de-funding-police/ (other OCAP thing: https://ocap.ca/resistance-pandemic-and-beyond/)

**Comment by patcon** [comment]
`2021-02-25` cleanup in governance: this should stay open

**Comment by dcwalk** [comment]
Also some more concrete things from "How to be an Antiracist" (still digesting parts of this):
- https://www.greatplacetowork.com/resources/blog/dr-ibram-x-kendi-on-building-anti-racist-workplaces

**Comment by dcwalk** [comment]
I think this is a concrete like subinitiative that operations can take up and focus on for a couple weeks after CMC, there are tangible small steps that would better set us up:
- hiring policy more clear in our commitments
- health and safety anti-discrimination policy, we could add our own language from template
- we could think about ~defining~ our values and getting more tight on alignment at the upcoming members meeting or a strat.planning session

**Comment by patcon** [comment]
Might optional reading groups for members be considered part of this? Continual improvement, greater fluency and socializing of concepts together feels like it could be part of a plan.

I have this sense that discussions of race in Hypha often feel quite abstract and depersonalized, and I'm unclear if that's (1) real vs imagined or (2) healthy vs unhealthy. E.g., race comes up more often in Civic Tech Toronto conversations, but more seldom in Hypha. I also appreciated that race came up several times in conversation with Aljumaine @ LANE Digital, and it makes me wonder if I contribute to a blind spot in Hypha.

**Comment by dcwalk** [comment]
Things to consider:
- "systematically overhaul its own cultural and hiring practices and set meaningful goals for recruitment, retention, and compensation to reflect the diversity of"
- participation in CWCF JEDI committee?
- attending the building Racial Justice workshop with cwcf

**Comment by patcon** [comment]
Mention of adding 8th principle. We could adopt/write our own fork of principles, and advocate amongst other Canadian co-ops to similarly adopt
https://canadianworker.coop/should-co-ops-adopt-an-eighth-principle/

**Comment by dcwalk** [comment]
https://inclusivenaming.org/language/word-list/

**Comment by dcwalk** [comment]
This has some nice descriptions: https://datasociety.net/wp-content/uploads/2019/05/Racial_Literacy_Tech_Final_0522.pdf

**Comment by benhylau** [comment]
Relevant lessons from online community moderation of spaces: https://newpublic.org/article/1943/how-talking-about-race-divided-a-beloved-dog-training-facebook-group
