### ISSUE TITLE
Re-evaluate external services

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#320]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** end-March  
🎯 **Success criteria:** Have a plan for continued hosting (or deprecation) of each service listed below.  

In our discussions, we planned to not migrate these services:
>- VM8: email 💧💾💾💾
>- VM9: matrix ~+ whatsapp bridge + chatbot 💧💧💾~
>- ~VM4: nextcloud + onlyoffice 💧💧💾💾~

We should re-evaluate the long-term plan for these services, and deprecate ones that are no longer important.

## To Do

- [ ] Discuss and have a plan for each service

**Comment by dcwalk** [comment]
What do the symbols mean? 

Also, have folks outside of infra been informed of the impact of these not being migrated?

I'm a little surprised to see email on there -- based on what I thought the reason to go with the server you all did was that it had the capacity to bring in-house things that weren't in-house.

**Comment by benhylau** [comment]
They are relative weighs by 💧 units of $5 DO Droplet and 💾 units of disk space. If you look at them all together it would make more sense: https://github.com/hyphacoop/organizing/issues/253#issuecomment-634166075

Everything on that list is currently not "in-house", so all of the milestone is to "bring in-house things that weren't in-house". On this list, email and matrix are tools we depend on that are maintained by @ASoTNetworks through another org, while the rest are non-critical and barely used. I think we should have the discussion about this after the essential tools living on various boxes are brought in?

**Comment by garrying** [comment]
WONTDO
