### ISSUE TITLE
Management of DNS and IP addresses

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#332]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** Oct 2020  
🎯 **Success criteria:** Come up with a plan for DNS and implement.  

Re-visit how to do DNS and IP addresses in Oct (Digital Ocean, OVH, Ansible, etc.)
Right now they are on DO.

## To Do

- [ ] ...

**Comment by garrying** [comment]
WONTDO
