### ISSUE TITLE
Desjardins - Multi Signature

### ISSUE THREAD

**Issue by YurkoWasHere** [hyphacoop/organizing#355]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** Decide and submit resolution to change account to single signature.

Multi sig account is blocking us from doing day to day transactions

- Interact E-Transfer out will not work with multi sig
- Additional confusion when dealing with adding bill payments etc.
- Taxes where blocked due to additional person not available to sign off

## To Do

- [x] Call to find out if its possible
- [x] Decide if we want to
- [ ] Draft resolution
- [ ] Sign resolution
- [ ] Submit resolution

**Comment by YurkoWasHere** [comment]
To chance ONLINE multi sig

- Draft resolution
- Note that we currently have a 2 signature account online
- note that we wish resolve to change it to 1 sig account
- Pass the resolution and sign it
- Submit it


To change multi sig to single sig anywhere other then online many more documents need to be passed.

**Comment by benhylau** [comment]
We only use Desjardins multisig during tax time, 4-5 times a year, won't do. Interacs via TW.
