### ISSUE TITLE
Allow nav to scroll separate from notes

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#365]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

Suggestion from @YurkoWasHere in chat:

> might want to throw the nav bar into a separate scrolling div, its getting pretty long

## To Do

- [ ] ...

**Comment by YurkoWasHere** [comment]
https://github.com/hyphacoop/organizing/tree/nav-fix

Possible solution. 
Not sure how to test it.

**Comment by patcon** [comment]
Thx! Will test tomorrow

**Comment by patcon** [comment]
Thanks Yurko, but I'm seeing the notes content is set to be less than full-width (so the tables don't span), but that non-full-width div is what's scroll, so thers' a big gutter that doensn't scroll. Spent a bit trying to fix it, but I'm apparently not a CSS whiz

<img width="941" alt="Screen Shot 2020-11-13 at 8 20 53 PM" src="https://user-images.githubusercontent.com/305339/99134959-0fa75200-25ee-11eb-8994-abef3f651398.png">

**Comment by YurkoWasHere** [comment]
https://github.com/hyphacoop/organizing/commit/f82007e79ef77967f2ee4f8955246dde3b7ae7ff#diff-8bf729ffe074caee622c02928173467e658e19e28233cff8a445819e3cae4d50

Seems to do the trick.

**Comment by patcon** [comment]
Done in linked PR 🎉
