### ISSUE TITLE
Setup telephone system

### ISSUE THREAD

**Issue by YurkoWasHere** [hyphacoop/organizing#372]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** 02/23/2021  
🎯 **Success criteria:** ...  

## To Do
 Set up FreePBX to terminate incoming / outgoing calls

    Configure voicemail to email
    Extension for BBB
    Extension for Jitsi
    Extensions for members to use for outgoing calls using Hypha's number

- [ ] @YurkoWasHere Update docs to reflect voip.ms and features
- [ ] @YurkoWasHere Update services with new number

**Comment by benhylau** [comment]
Update docs so all the numbers are clear and change our 2-factors to new number for SMS rx.

**Comment by dcwalk** [comment]
@YurkoWasHere can this be updated? The PR with instructions was merged

**Comment by garrying** [comment]
Closing.

@YurkoWasHere there is a small follow up to add SMS instructions for 2FA.
