### ISSUE TITLE
Run OKR process for 2021 Q1

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#375]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

...

## To Do

- [ ] ...

**Comment by patcon** [comment]
Pulled from [bizplan](https://docs.google.com/document/d/1U8C1XZcDpu1r4ciecbKEZ6vOL41nTinfqPCbZDhkAWc/edit#) notes (re: @uditvira @dcwalk)

> During our strategic planning session we will collectively:
>   1. Decide Hypha’s goals and strategic priorities for the coming year
>   2. Identify key actions and activities that Hypha should engage in
>    3. Establish measures for accountability and how actions are tracked
>    4. Create a strategic roadmap by determining the timeframes within which we engage in activities
> 
> 
>    * Pull from notes
>    * Rough clustering
>    * Clean up of early goals / key actions, identify relevant WGs
>    * Discussion / validation of strategy areas (all hands + with WGs)
>    * Write out in Strategy format (Key Action, Time Frame)
>    * Update Biz Plan
>    * Market positioning
>    * Solidarity rate
>    * OKRs fleshed out by WGs that align with strategy
>    * Signoff on Strat and quarterly OKRs mid-July
>    * Long term: develop engagement and procurement plan:
>    * Public activities
>    * Procurement
> 
> 
> Goal-ish form sentence (relevant WGs) (can think with SMART S.M.A.R.T. stands for specific, measurable, achievable, relevant, and time-bound -> “I want to save $10,000 a year for the next ten years.”
>    * Bullet point action/activities that start with Verb
> 
> 
> SMART goal: I want to improve my performance / Hypha should 
> Associated WG’s: 
> Description: To grow in my career, I need to improve my PowerPoint skills. By taking online classes and reviewing tutorials, I’ll improve my PowerPoint skills so that it only requires 25% of my work time.
> Milestone: Complete an online PowerPoint course in three months.
> Deadline: Next employee review in six months.

**Comment by dcwalk** [comment]
This issue has had no content since Nov and given https://github.com/hyphacoop/organizing-private/issues/108 I'm going to close.
