### ISSUE TITLE
Refresh our competitive positioning matrix in Business Plan 

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#376]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** 2021 Q2  
🎯 **Success criteria:** Competitive positioning matrix is updated 

Came out of Y2 strategy discussion (#308), our business plan for the year is updated, but we see value in updating our understanding of the competitive positioning.

## To Do

- [ ] Co-work update at BizDev meeting

**Comment by patcon** [comment]
`2021-02-25` cleanup: uv: do we need this? competitive positioning? why not mapping our co-operative ecosystem? dc: let's keep for review.

- identity gaps, establish a niche. we should frame it as this is what others are doing in ecosystem and but these are the gaps.

**Comment by dcwalk** [comment]
WONTDO, reticketed new approach: #414
