### ISSUE TITLE
Develop conflict resolution process

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#377]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

This came up in Business Plan Y2 (and Y1) strategy and also the 2020-11-26 Ops meeting: we need to codify processes for conflict resolution between members

## To Do

- [ ] review examples
- [ ] draft proposal
- [ ] discuss at all hands
- [ ] ...
- [ ] adopt

**Comment by LexaMichaelides** [comment]
Moved work to: https://github.com/hyphacoop/organizing-private/issues/239
