### ISSUE TITLE
Identify current member competencies+skills as well as org gaps

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#380]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** Q2 2021
🎯 **Success criteria:** ...  

As part of Goal 5: Hypha should identify and support members setting learning goals and interests, from our business plan we identify the following activities:
- Identify what competency gaps exist within the organization (especially around network building and business opportunities)
- Support members identify learning goals both for skills (e.g. be accountable, communicate effectively) and competencies (e.g. project management, server maintenance) and personal interests

Building on #361 and the high-level member capacities we should thicken this mapping and identify goals / interests / skills+area competencies 

## To Do

- [x] collect examples of skill matrices, learning goals, tech skills+competencies lists
- [ ] devise async member activity to create (part of peer feedback mood?)

**Comment by patcon** [comment]
- MJW is interested in competicies+skills evaluation for platform co-op board (could be client project connection)

**Comment by dcwalk** [comment]
Looks like this was done here as part of Y2 agm: https://github.com/hyphacoop/organizing-private/issues/140#issuecomment-888784488
Closing this out for now
