### ISSUE TITLE
Update guide+template for signing resolutions

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#385]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** Q1 2021  
🎯 **Success criteria:** Upated signing process that has passed ServiceOntario acceptance testing.  

Edit: answer was needed visual e-signature.

Waiting to see if government will accept our pgp signed resolution as valid. Regardless we need to update our process, either to smooth out pgp method, or adopt a new one.

Notes on PGP (from operations chat):
```
Used pandoc to build PDF package with resolution + signatures.

Painful lessons on compiling amendment email:
- unicode chars in names no bueno
- using shortcode for emoji (maybe emoji period) no bueno
- literally can't verify if how we've done our digital signatures will be accepted. Can't compile in doc / provide audit trail like most PDF digital signing systems
- no documentation for creating an audit trail from digital signatures
```

## To Do

- [x] send email to Service Ontario RE: PGP signatures (related: #104)
- [ ] add signing process with visual signatures in handbook ONLY for key docs

**Comment by benhylau** [comment]
>- unicode chars in names no bueno

I still believe is one of the worst ideas we ever had 🤣

**Comment by dcwalk** [comment]
handle it in docsprint!

**Comment by dcwalk** [comment]
I just added a line to the handbook to capture this and closing for now: https://github.com/hyphacoop/handbook/commit/f04ef2387b189a7f94b3dca68033916905b6d3a1
