### ISSUE TITLE
Bug: Accepted calendar invites not showing up in calendar

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#393]
Calendars for our hypha email accts seem to be experiencing an issue.

Original report in #hyphacoop-infrastructure:tomesh.net:
> I've had a couple calendar invites come in that I've accepted but they aren't populating my calendar e.g., this one from From Later I just accepted and one from Quartermaster. I logged into the SOGo web interface just now and experiencing the same

I'm using:
- desktop linux 
- thunderbird
or 
- osx
- apple mail

tested accepting google invites in different browsers (e.g., firefox, beaker) didn't change anything.

**Comment by ASoTNetworks** [comment]
I was looking at how events are added into the calendar when the accept link is clicked.

The client side (not server side) will add the event into the calendar once accepted. I tested this in Thunderbird where it adds to the wrong one unless I make all the others read only.

Another report of creating shared calendars events not using the owner's account on SoGo will cause the event to not get send out to attendees. This is because SoGo tries to send the email from the owner's email which is not allowed from a different user.

A workaround is to create a general calendar account and use that to share the calendars and allow anyone to send from the calendar email.

Shared calendar issue: https://www.sogo.nu/bugs/view.php?id=2702

**Comment by dcwalk** [comment]
Just an update that this behaviour is still not as expected. @uditvira flagged other calendar issues around how shared calendars perform but unclear what the resolution on that / this where

**Comment by uditvira** [comment]
My shared cal issue captured in #419

**Comment by garrying** [comment]
From March 23, 2021, infra-wg meet:
- infra-wg is wondering how are people adding their calendar's to their respective clients
- keep posting in this issue: we're looking for reproducible steps, and clients, to help us evaluate possible solutions
- infra-wg will look into CalDev clients and feasibility of support 
- infra-wg will investigate the feasibility of using ActiveSync

**Comment by uditvira** [comment]
I'm still having serious calendar issues, where invites aren't showing up in my calendar client (MacOS/iOS Apple Calendar). I've tried a few times and it's reproducible. When I send an invite from a personal Google account, through the Google calendar web app, to udit@hypha.coop, it doesn't show up in my Apple Calendar. I do get an email invite with the ics file. I can accept it from the SoGo web client, and even then it doesn't show up in Apple Calendar. I'm assuming then that this is a CalDAV issue.

**Comment by ASoTNetworks** [comment]
Does it show up in Sogo? Is your iOS calendar added through the CalDAV account settings option with the correct CalDAV link from Sogo `Links to this Calendar` ?

**Comment by uditvira** [comment]
Yes it shows up in SoGo. CalDAV link should be correct, I'm seeing other previous events. It's not like it's never worked before.  Is there a way to check if CalDAV requests from my client are being served on your side?

**Comment by ASoTNetworks** [comment]
I checked the server logs and don't see any errors. Have you tried deleting the calendar and adding it again?

**Comment by ASoTNetworks** [comment]
This morning @uditvira created a event but didn't sent out invites to attendees. We saw that the organizer was selected randomly with users in alias that he is part of.

We also tried re-creating the accounts on the computer but same results.

After disabling `Alias is visible in SOGo` in all the alias it fixed the organizer issue but still didn't send out invite emails.

I have also tested the same steps in a Big Sur VM and calendar works as expected.

- OS: macOS
- OS-Version: Big Sur
- Mail Software: Apple Mail
    - Version:
- Calendar Software: Apple Calendar 
    - Version:
- Portocols Used:  
    - CalDAV, CardDAV, IMAP

**Comment by ASoTNetworks** [comment]
Things to diagnose why event invitation email not being sent out:
- see if creating a event normally like yesterday will send out an invite
  - verify the organizer is right in SOGo
  - if no email sent out try with Mail app running in the background if it is not already running

**Comment by uditvira** [comment]
I tried all permutations
- mail client open/closed
- create events with 1 or more invitees (including hypha and non hypha accounts)
Mail invites seem to be going out. I'm glad it works, but I don't want to work with such brittle infra, I have no trust in whether invites are actually sent or not.

cc @ASoTNetworks

**Comment by ASoTNetworks** [comment]
Looks like turning off `Alias is visible in SOGo` did the trick and invite should be sent out now.
I would suggest using this internally to test out the feature or ping external contacts to see if they received it

There is currently an know issue with Gmail when they received the invite email but attendee acceptance status is not reflected on SoGo server so you won't get a status if they accepted or declined.
More info: https://www.sogo.nu/bugs/view.php?id=5182#bugnotes

**Comment by ASoTNetworks** [comment]
Also tested sending to a ProtonMail address and accepted the event and acceptance is reflected on SoGo server so it seems like something with Gmail.

**Comment by ASoTNetworks** [comment]
Things @YurkoWasHere and I tested

Created calendar invite event from Hypha email using Outlook to a Gmail address and accepted in Gmail's web UI and got confirmation when accepted or declined actions are clicked.

Creating calendar invite event from Hypha to a bunch of other emails using SOGo and Thunderbird we got all confirmation emails but no email from Gmail user when accepting from Gmail's web UI. Accepting on Thunderbird of the same Gmail user the Hypha email got a response.

Events created from Gmail calendar to Hypha the Gmail user gets a response when the Hypha user accepts or declines.

**Comment by YurkoWasHere** [comment]
Test WORKING email ICAL and NOT WORKING e-mail ICAL invite

Working on was generated by OUTLOOK
Not working one was generated by THUNDERBIRD

Testing using command line mail client

## Test 1 - containers

Working one used 
```
Content-Type: text/calendar; charset="utf-8"; method="REQUEST"
Content-Transfer-Encoding: quoted-printable

ICAL
```

Not working used 
```
Content-Type: multipart/mixed; boundary..

...
--Boundary
Content-Class: urn:content-classes:calendarmessage
Content-Type: text/calendar; method=REQUEST; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable
ICAL
--Boundary
```

Swapped the containers, Working one continued to work, non-working still did not

Conclusion: must be an issue with the ICAL structure itself

**Comment by ASoTNetworks** [comment]
We figured out why acceptance email doesn't reach the inbox from Gmail. If the Hypha email is registered with a Google account the invitation gets routed internally by Google's backend into `/dev/null` and nowhere to be found.

To avoid this **do not** use your Hypha email to register for a permanent Google account.

**Comment by benhylau** [comment]
Has anyone done this?

**Comment by ASoTNetworks** [comment]
Think it is only me since testing I noticed that weird issue.

**Comment by benhylau** [comment]
Can you unregister and "fix" your account?

Can @uditvira @dcwalk confirm they aren't impacted.

**Comment by ASoTNetworks** [comment]
Yes I did that but it will take some time before it is totally purged from Google's systems. I ran a login test trying to sign in with all our emails and shows they don't exists.

**Comment by dcwalk** [comment]
I am not impacted! As of my call with @ASoTNetworks last week I am not experiencing the bug described here, and have the ability to accept/send.

There is a larger issue though with the limits on what Sogo info is shared publicly and Google Calendar's use of non-standard fields (that was my issue with the missing Zoom links).

Best,
Dawn

**Comment by ASoTNetworks** [comment]
> There is a larger issue though with the limits on what Sogo info is shared publicly and Google Calendar's use of non-standard fields (that was my issue with the missing Zoom links).

This is when Google pulls from Sogo into your calendar right?

**Comment by YurkoWasHere** [comment]
O365 complain

https://answers.microsoft.com/en-us/outlook_com/forum/all/calendar-invitations-sent-to-gmail-users-are-not/2c51b41e-99c3-4ce5-85d1-9dc4a740d8e6

**Comment by benhylau** [comment]
If an email address not using a Google inbox (e.g. `x@hypha.coop` uses another provider) is registered on Google Apps, and it sends a calendar invitation, then a recipient _who uses Gmail_ accepts the invitation, Google will _not_ send an acceptance out to the sender. This results in `x@hypha.coop` not being able to get a accept/reject to that calendar invite.

It is related to this flow:

https://www.techrepublic.com/article/how-to-resolve-an-invitation-issue-between-google-calendar-and-office-365/
>As of February 2015, when you send a Google Calendar invitation, the invitation goes to the Google Calendar linked to the email address of the person you invite. If the email address isn't linked to a Google Calendar, then the event invitation routes by email to the recipient. If your organization moves away from Google Apps, make sure to remove the domain -- and thereby the associated emails -- to ensure that future invitations from people who use Google Calendar route properly.
