### ISSUE TITLE
Map our position in the (tech) (dweb) co-operative ecosystem

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#414]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #376 
🗣 **Loomio:** N/A  
📅 **Due date:** Pre april planning meeting
🎯 **Success criteria:** ...  

Have a chat at bizdev meeting identity gaps, establish a niche. we should frame it as this is what others are doing in ecosystem and but these are the gaps.

## To Do

- [x] chat at bizdev
- [x] host activity to do this prelim mapping
- [x] clean up

**Comment by patcon** [comment]
made suggestion on call that this sort of exercise is well-suited to polis:
- finds alignments/divergences across the full spread of dimensions we focus on
- self-serve. representatives/employees of orgs populate data
- participatory. org employees/representatives can add statements to map against others
- long-running. no need to close. could run them periodically, and leave them open for months. late-comers welcome. network effects welcome if we wish.
- x & y axes can actually be meaningfully labelled afterward, and will correspond to the 2 axes over which all our orgs show the most distinction. naming those labels is a bit subjective and a small exercise of its own for participants.

**Comment by dcwalk** [comment]
We did this with miro as a internal activity. I'm closing for now, we should ticket out new issues that arise in initiative structure
