### ISSUE TITLE
Open Collective applicant: Equity4Who

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#416]
Re-ticketed from https://github.com/hyphacoop/organizing/issues/374#issuecomment-788974933

- application interview: https://meetings.hypha.coop/2021-02-05-equity-4-who.html

## To Do

- [x] host interview call. [notes](https://meetings.hypha.coop/2021-02-05-equity-4-who.html)
- [x] create [sample rate sheet](https://docs.google.com/spreadsheets/d/1oyUjNZHaslqu7E_VySMgj6C6AOpSeS63UCZNoVYAtjc/edit?usp=drive_open&ouid=117169981156567015860) :lock:
- [x] create [sample collective](https://opencollective.com/hyphacoop-sample-collective) and invite
- [x] email followup details: WED FEB 10
- [x] followup with E4W after their 2021-02-13 call: TUE FEB 16
- [x] confirmed E4W is in! MON MAR 1
- [x] map out rest of onboarding process
- [x] send invite email. [template](https://docs.google.com/document/d/1RMl2Hlvars_-_BZTgfi37tlVdJTNAT3Nl957GP1EqVY/edit#heading=h.h95c0x4wjowz) :lock:
- [x] approve application
- pre-launch check-in call
  - [x] schedule FRI MAR 19
  - [x] run. [notes](https://meetings.hypha.coop/2021-03-19-equity4who-checkin.html)
- [x] launch! (pending on E4W)
- [x] resolve potential OC platform issue with $1000 vs $100 initial deposit (see: email below https://github.com/hyphacoop/organizing/issues/416#issuecomment-829473237)
- post-launch check-in call
  - [ ] schedule
  - [ ] run

**Comment by dcwalk** [comment]
Can we update the status of this? Pretty sure they launched? @patcon

**Comment by patcon** [comment]
Email fwd'd to finance WG:

> **Subject: Has CA$100 arrived for Equity4Who?**
>
> Was about to schedule a post-launch checkin with this collective, and while reviewing collective, noticed this:
>
> This fwd'd email with a transaction dated Apr 14 references $100 being deposited into Equity4Who. (Has this been received?)
>
> But the OC interface is showing $1000 deposited (below), with a fee appropriate for that amount. ($100 is more what I'd expect from them, so that seems more likely to be correct.)
>
> <img width="794" alt="Screen Shot 2021-04-29 at 1 48 40 PM" src="https://user-images.githubusercontent.com/305339/116597251-616d3b80-a8f3-11eb-9991-65dd2b6bc123.png">
>
> I'm quite confused, and unsure what showed up in the bank account itself, if anything. As an aside, I'm also wondering what they might have seen on their end, and can imagine they might be confused (and thinking it their fault). I'm hoping to have more information before reaching out to them.
>
> How are you seeing this from your end? If you feed me any finance context, then I'm happy to communicate with OC about resolving (I suspect it's a bug).
>
> Happy to do a quick sync call when you get on in your morning.

**Comment by dcwalk** [comment]
Retagging as they were accepted as a collective
