### ISSUE TITLE
Open Collective applicant: Toronto Tech Mentorship

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#417]
## To Do

- [x] introductory conversation and informal demo
- [x] invite to [sample collective](https://opencollective.com/hyphacoop-sample-collective)
- interview call(s). 🔒 [questions & answers.](https://docs.google.com/spreadsheets/d/1BSxPPbLGS7RfmSi6KghcyABlFpGca_5msoeEFWoKcNE/edit#gid=0) 
  - [x] host casual interview call. 
  - [x] prepare remaining interview questions
  - [x] schedule "real" interview SAT MAY 1
  - [x] host "real" interview call 
- [x] email onboarding outline
- [x] collective approval decision by Hypha - DUE a.m. Thurs May 6
- [x]  approve application: https://opencollective.com/hyphacoopinc/dashboard/pending-applications
- pre-launch check-in call  
  - [x]  schedule
  - [x]  run
- [x]  launch! (pending on E4W)
- post-launch check-in call
  - [ ]  schedule
  - [ ]  run
- [ ] ...

**Comment by dcwalk** [comment]
Retagging as they were accepted as a collective tho not sure if action has moved forward.
