### ISSUE TITLE
Virtual Office issue: some forwarded mailcow emails getting marked as spam in gmail

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#418]
I've noticed this a few times. Will document more fully, but starting this stub for tracking. 🙏 

- I use Gmail as my email client from patcon@hypha.coop
- I have my mailcow inbox configured to globally forward all email to patrick.c.connolly@gmail.com (leaving copy unread in mailcow)
- vast majority of email is forwarded cleanly, but sometimes email ~~doesn't make it~~ gets labelled "Spam" by gmail
- ~~when email is missing from gmail,~~ it is still inside mailcow when I go to look
- issues started on Feb 10, 2021

## To Do

- [x] inventory known problematic messages (currently: 20, 4 notable types)
  - (3) real from mailchimp direct to patcon@ (radicalxchange contact list)
  - (1) real from benedict@ => operations@ => patcon@
  - (1) real from benedict@ => project.opencollective@ => patcon@
  - (1) test email from elon@ to patcon@
  - (14) real from random services to patcon@ (not super important rn)
- [x] ~~compare gmail inbox to mailcow inbox, finding any others~~ no need
- [x] document fully (screenshots of settings, dumps of affected email headers, etc)
  - gist of raw emails of notable types: https://gist.github.com/patcon/34f71f0ceb10c5b05e0cc89c63c5ed25
- [ ] validate with @hyphacoop/infrastructure-wg that this is real
  - [ ] optional: contact members@ to advise of quick mitigations
- [ ] ...
- [ ] document mitigation tactics or resolutions

**Comment by patcon** [comment]
What email clients ppl are using:

| name | client(s) |
|---|---|
| pc | fwd:gmail
| uv | apple, gmail
| gi | fwd:gmail
| dc | apple, thunderbird, mailcow
| el | (?)
| bl | (?)
| yj | (?)

**Comment by patcon** [comment]
Also worth noting: hypha emails fwd'ing to spam only started on Feb 10, 2021

**Comment by patcon** [comment]
Current best mitigation:

To find whether anything was filtered already:

`(to:*@hypha.coop OR from:*@hypha.coop OR cc:*@hypha.coop OR bcc:*@hypha.coop) in:spam`

To ensure nothing is lost:

`(to:*@hypha.coop OR from:*@hypha.coop OR cc:*@hypha.coop OR bcc:*@hypha.coop)` and click "down arrow" then "create filter", then check the box "Never send it to Spam" and create the filter. Note that this will prevent real spam to this address from getting caught, but is tolerable for low-volumes of spam.

**Comment by patcon** [comment]
From Chat: Root cause of this spam filter punishment from Google may have had something to do with mailman being reconfigured to be more permissive, as required by COMPOST. Chat starts here: https://chat.tomesh.net/#/room/#hyphacoop-infrastructure:tomesh.net/$x5VO-8tVX-UdREnCFT-MTvzmoETLHmcaAhF9fd38zk8

**Comment by YurkoWasHere** [comment]
listserv is a different mail server and different ip address, and probably does not have any affect on the mail cow instance

**Comment by YurkoWasHere** [comment]
Many of the anti-spam tactics that large provider use (like gmail) are very AI based. All actions on an email are considered and catalogued across the network. This includes engagement with emails.

Just want to flag that the way we use email may not be the most "ai friendly" method as much of the email may not be read or even opened.

One mitigation thing we can try to do to keep ahead of this is to subscribe to "postman" that allows mail server admins to keep tabs on how their servers interacts with google.

https://support.google.com/mail/answer/9981691?visit_id=637506796324023727-393043956&rd=1

**Comment by patcon** [comment]
While I'm a naive about Postmaster, having this insight sounds like a GREAT idea, Yurko

**Comment by YurkoWasHere** [comment]
>  Mailcow sporadically not forwarding some emails from patcon@hypha.coop mailbox

To be clear

Is mailcow is not forwarding emails? or they are just not being received.

**Comment by patcon** [comment]
Thanks for asking (will correct above): I haven't done a tedious one-for-one comparison of my gmail vs mailcow inbox, but found all the important ones that I'd _realized_ were missing, in gmail's Spam folder. So I'm reasonably convinced that spam-filtering by Gmail is main culprit. (Happy to take direction on checking other things though.)

I've never checked mailcows spam/filters, but am assuming nothing is getting stuck there.

**Comment by garrying** [comment]
@patcon infra-wg thinks this is really similar to #422. We will give updates in that issue and close this for now.
