### ISSUE TITLE
Prepare and Host our second AGM in July 2021

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/organizing#463]
Re-ticketed from #
Related issues 
Reference issues #102 (AGM 2020)

## Shared Description

:speaking_head: **Loomio:** TBD 
:date: **Due date:**  July 24, 25 2021 (Actual AGM dates); wrap up tasks to be completed by September 1, 2021
:dart: **Success criteria:** We've run our second AGM.  

### 2021 AGM committee
@uditvira, @benhylau, @dcwalk 

## To Do

- [x] discuss goals and visions of AGM
  - [x] AGM committee
  - [x] broader membership
- ~review requirements for AGM in Act~ (dc: don't think this is needed)
- [x] review requirements for AGM as noted in planning doc
- [x] finalize a date for our AGM  **July 24-25** (Sat-Sun)
   - [x] select potential dates: 1.5 days
   - [x] add to calendar and communicate Save the Date to folks (via poll)
- [x] draft [initial plan (incl. pre-work, requirements, outcomes) 🔒](https://docs.google.com/document/d/1w0sHaXIZa_EIOFict1mM-RCYlAVzQ3r1-T_B4AYPFZs/edit#)
- [x] send official **notice of AGM/member's meeting with location**:  July 10th, 2021; [deadline is 10 days before meeting](https://handbook.hypha.coop/bylaws.html#3-member-meetings): July 14th
  - [x] send guidance for initiatives
- [x] request reports from initiatives
- [x] draft and distribute package 
  -  [agenda](https://hackmd.io/PPaIBTCeRFuG6Qhgj2-NDA)
  - members meeting explainer
- [x] 🎉 run the meeting

**Comment by dcwalk** [comment]
Did a slight cleanup of the todos on this issue.Thanks for starting the process!

**Comment by uditvira** [comment]
I spawned a few wrap up issues. I think we're good to close this
