### ISSUE TITLE
Clean up infra document and move to handbook

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/organizing#467]
We are currently using [this document](https://hackmd.io/pElXZTnUTRO1zApxpdBWDw?both#VM-ID-categories) for documenting infra processes (how to create VMs, setting up VPN access, etc.) as well as to track of our VMs, IP allocation, and local DNS.

After engaging with this document a few times and discussing with @ASoTNetworks I have some thoughts and recommendations:

* This document is hard to find and not very readable. @ASoTNetworks and I discussed that the processes part of the document should be PR'd to handbook.hypha.coop with a link to the hackpad. Every Hypha member should be able to reserve a VM for themselves without having to ping infra people
* The only items that should remain in the hackpad are the tables which need to be updated frequently. This will ensure that the process is discoverable in the handbook, but we don't expect a laborious PR process for updating a single VM ID in the tables
* Currently every time I create a VM, I need to document that in three places (VM ID table, IP allocation table, and DNS table). The chances of error are high. I wonder if we can find a better way of organizing this information so only a single entry is required when creating a VM. I also wonder if some of these tables are that valuable to maintain a document? We are duplicating information that is easily found on Proxmox and pfSense dashboards

cc @YurkoWasHere @benhylau

**Comment by benhylau** [comment]
I agree that instructional docs showing non-privileged information should move to handbook, as the central place for our organization. I am ok with bypassing PR step if minor changes are made.

Agree that hackmd can be used for fast changing info.

**Comment by YurkoWasHere** [comment]
Refrence - https://github.com/hyphacoop/organizing-private/issues/141

**Comment by YurkoWasHere** [comment]
Pending audit

**Comment by YurkoWasHere** [comment]
Migrated content of hackmd to handbook/github repo (https://github.com/hyphacoop/handbook/pull/151)
