### ISSUE TITLE
Complete resourcing and budgeting after AGM 2021

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/organizing#471]
We weren't able to complete resourcing and budgeting for initiatives during the AGM (#463)

Working spreadsheet: https://docs.google.com/spreadsheets/d/1Ycl9pr_gKcnqndDQylYc5ZpPVb_KTSYEN5qpKzvtt-0/edit#gid=809515225 🔒 

Tasks:
- [x] Hold session
- [x] Get org consensus (we are pending on @YurkoWasHere)
- [x] PR to handbook
- [x] Add to link.hypha.coop/initiatives
- [x] Add to link.hypha.coop/hours

**Comment by uditvira** [comment]
I'm suggesting stacking this with #469

**Comment by uditvira** [comment]
@benhylau and @YurkoWasHere I need numbers around reserves to do this resourcing and budgeting.

**Comment by uditvira** [comment]
We did this. Need @YurkoWasHere for final approval since he wasn't here. Please review the spreadsheet, particularly the line highlighted in yellow.

**Comment by YurkoWasHere** [comment]
> 
> 
> We did this. Need @YurkoWasHere for final approval since he wasn't here. Please review the spreadsheet, particularly the line highlighted in yellow.

Looks good to me, removed yellow (inclear how you wanted me to acknowledge)
