### ISSUE TITLE
Commission illustrations from AGM portrait photos

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#472]
Another wrap up task from AGM 2021 #463 which should be completed by Sept 2021:

- [x] review and select photos from shoot
- [x] small post / editing of selected photos
- [x] [upload photos to gdrive :lock:](https://drive.google.com/drive/folders/1xALVq1buU1Pboh9i3uoXxE2rOdyNRbk4?usp=sharing)
- [x] identify illustrators (below)
- [ ] choose illustrator and commission illustrated portraits

**Comment by dcwalk** [comment]
Short list of (mostly Toronto-based) illustrators:
- https://sambeck.ca/illustration
- https://bylaurenp.com
- https://natalieczer.com/commission
- https://jeanniephan.com/about
- https://jensineeckwall.com/links

**Comment by writerly03** [comment]
Adrian created images for Hypha in the last round of website updates, so closing this issue
