### ISSUE TITLE
Consider adding more days our office is closed to align with Federal + important holidays

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#474]
There is a new Federal Statutory holiday:
- [Sept 30, National Day for Truth and Reconciliation](https://www.canada.ca/en/department-national-defence/maple-leaf/defence/2021/07/federal-statutory-holiday-national-day-for-truth-and-reconciliation.html)

And we also have Days / holidays that aren't ON public holidays or federal statutory holidays:
- June 21, [National Indigenous Peoples Day](https://www.rcaanc-cirnac.gc.ca/eng/1100100013718/1534874583157)
- August 1, [Emancipation Day](https://www.canada.ca/en/canadian-heritage/campaigns/emancipation-day.html)

I'd love us to include these as holidays where the office is closed (getting to our goal of more than one holiday a month!) and also down the road consider folding these into our annualized Public Holiday pay policy: https://handbook.hypha.coop/holidays.html / https://handbook.hypha.coop/finance.html#public-holiday-pay

**Comment by LexaMichaelides** [comment]
Moved to: https://github.com/hyphacoop/organizing-private/issues/233
