### ISSUE TITLE
Define operations role: time tracking / payroll

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#475]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** Review https://handbook.hypha.coop/roles.html#operations-coordinator and update the page with responsibilities.  

From chat:
> I can define an ops role (finally, my bad) which includes adding internal hours, it is v. fast when you are looking at the report. But client stuff is all over the place so hard for the ops person to do, has to be initiative lead for client work

See https://github.com/hyphacoop/organizing/issues/97 and https://github.com/hyphacoop/organizing/issues/73 for historical thoughts on this

See: https://docs.google.com/spreadsheets/d/1AwgVq3ghTQgg5J8s1xbcsdAfis2u4vBU9qi1nZANMOE/edit#gid=1967891803

## To Do

- [ ] draft role for ops / timekeeping

**Comment by writerly03** [comment]
Where does time tracking happen? Internal hours managed by operations role
Client hours are documented by client initiative lead.

**Comment by benhylau** [comment]
## Time tracking

Time tracking happens on Clockify: https://app.clockify.me

@writerly03 I just added you as Admin, not that you have to track time, just for you to look.

I also encourage all to switch Clockify to their Hypha emails. @dcwalk @uditvira @YurkoWasHere 

![Screen Shot 2022-04-12 at 8 56 49 PM](https://user-images.githubusercontent.com/2261308/163078233-09d50bc9-b8b0-4faf-a693-72350c1be73c.png)

## Capacity and billable targets

I just added `Capacity commitment` and `Billable target` to https://link.hypha.coop/employees

![Screen Shot 2022-04-12 at 8 50 40 PM](https://user-images.githubusercontent.com/2261308/163077854-4e429cd0-1c38-473e-bed9-fbcba61ea7f7.png)

These are based on latest quarter where the employee has completed time tracking.

**Comment by LexaMichaelides** [comment]
Moved to: https://github.com/hyphacoop/organizing-private/issues/247 and https://github.com/hyphacoop/organizing-private/issues/234
