### ISSUE TITLE
SMS Number that does not appear as VoIP

### ISSUE THREAD

**Issue by YurkoWasHere** [hyphacoop/organizing#487]
Many services reject VoIP numbers as verification phone numbers. I think that most of them use per-defined pools of numbers instead of checking each one individual. This allows them to block "spam" as voip numbers are easy to get, without to much effort.

My hypothesis is that if we get a number from a known cell company, hold it for a month, the port it over to our VOIP provider, that number will "fly under the radar" and not be flagged as a VoIP number so it would work with twitter and facbook etc.

The cost for this experiment will be around $50-60 depending on how cheap of a service we can get then an ongoing cost of ~$1 per month.

If this experiment is successful we can use this number for social media platforms and such, and have SMS2EMAIL enabled (so the account is not tied to a single user).

Is this experiment worth doing?

**Comment by benhylau** [comment]
I think we'll need this for a variety of things. Let's try it!

**Comment by LexaMichaelides** [comment]
@YurkoWasHere - should this issue be closed?

**Comment by YurkoWasHere** [comment]
Task completed we have a number.
