### ISSUE TITLE
Service inventory: add to this to organizing private repo

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/organizing#496]

**Comment by writerly03** [comment]
Move this list https://hackmd.io/@patcon/HyH0W9bAE to organizing private repo and then add link back to hand book. Add new issue for everyone to update this list.

**Comment by benhylau** [comment]
>add link back to hand book. 

Already linked to from here: https://handbook.hypha.coop/onboarding.html#our-virtual-office
