### ISSUE TITLE
Finance: check that all accounts and practices are current

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/organizing#499]

**Comment by writerly03** [comment]
Review and update the page if needed

**Comment by benhylau** [comment]
Wrote up something for quarterly bookkeeping. Put into Finance or Guide later:

## Quarterly bookkeeping

1. Download monthly bank and visa statements from the [bank][bank]
2. Download payroll registers and posting journals from [Wagepoint][wagepoint]
3. Ensure that [finance-snapshots][finance-snapshots] has up to date sheets for the quarter

| Statement         | Download from          | Upload to                                                |
|:------------------|:-----------------------|:---------------------------------------------------------|
| Bank Statements   | [bank][bank]           | [finance-statements-bank][finance-statements-bank]       |
| Visa Statements   | [bank][bank]           | [finance-statements-bank][finance-statements-bank]       |
| Payroll Registers | [Wagepoint][wagepoint] | [finance-statements-payroll][finance-statements-payroll] |
| Posting Journals  | [Wagepoint][wagepoint] | [finance-statements-payroll][finance-statements-payroll] |
 
[bank]: https://link.hypha.coop/bank
[wagepoint]: https://link.hypha.coop/wagepoint
[finance-statements-bank]: https://drive.google.com/drive/u/0/folders/11xgKvAU0iXHgfeGAp515EoncQkJsmbxd
[finance-statements-payroll]: https://drive.google.com/drive/u/0/folders/13ZFnCm0kFLFfvHc83mDiYX5HkE9r0piT
[finance-snapshots]: https://link.hypha.coop/finance-snapshots
