### ISSUE TITLE
Offboarding Checklist for Contractors

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/organizing#504]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** Off boarding checklist complete and linked to/ available in Handbook 

...

## To Do

- [ ] Create an offboarding checklist and process for contractors based on this https://github.com/hyphacoop/handbook/blob/master/templates/checklist-offboarding.md

**Comment by LexaMichaelides** [comment]
Related to https://github.com/hyphacoop/organizing-private/issues/139 - @ASoTNetworks

**Comment by benhylau** [comment]
@writerly03 pls see if this should be integrated to current offboard page or throw.

**Comment by writerly03** [comment]
This is separate from the offboarding page and should still be retained as it provides a rundown of the work that needs to be completed. However, it does need to be moved from its current location in the Handbook to a "Tasks as GitHub Issue template" as per this page: https://handbook.hypha.coop/templates.html  (My question, where do templates live on GH?)

I made a small edit, otherwise, it is up to date but needs to live in GH and not the handbook? I did add a link to it on the new offboarding page as it's a useful resource

**Comment by writerly03** [comment]
@LexaMichaelides to move

**Comment by LexaMichaelides** [comment]
Moved this and the onboarding template into the GH tasks section.
