### ISSUE TITLE
Matrix maubot

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#506]
Implementing Matrix bot actions.

See: https://github.com/hyphacoop/organizing/issues/485#issuecomment-1189495821

**Comment by benhylau** [comment]
- [ ] Look at @YurkoWasHere's PR and put message text into Google sheet
- [ ] Each emoji is a tab in the Google sheet
- [ ] Bot reacts with an emoji when it _first_ archives something
  - If someone removes the last emoji, we have a row without any emoji
- [ ] Updates:
  - Duplicate emojis should not record the message again, but it appends an emoji to the existing UUID
  - Removing an emoji does not remove the text from sheet
  - If message text gets updated, it will not update on sheet (message is archived at time of first emoji reaction)
- [ ] Record columns:
  - UUID
  - Message
  - Emoji (list)
  - Timestamp
  - User
- [ ] Set up a sheet that has one main tab, and other tabs that filter by a single emoji in a column

Example user flow:

1. Ben writes `Hello world`
2. Yurko emotes 🎟 on messge
3. Sheet records `UUID1, Hello World, [ 🎟 ], ts, Ben`
4. Andi emotes 🇺🇦
5. Sheet updates `UUID1, Hello World, [ 🎟 🇺🇦 ], ts, Ben`
6. Reader wants to look at 🇺🇦 topic (i.e. `Column C contains 🇺🇦`) on a tab
7. Andi removes 🇺🇦
8. Sheet updates `UUID1, Hello World, [ 🎟 ], ts, Ben`

| Emoji | Topic |
|:--|:--|
| 💼 | New business development |
| 🕸 | DWeb |
| 🥉 | Web3 |
| 🤝 | Coops |
| 📚 | Curriculum |
| 🌳 | Dripline |

**Comment by kivakiva** [comment]
## Next steps
* write documentation [Adrian]
* whitelist channels using Yurko's code [Adrian]
  * cosmos, private:general, worldwide:coops, worldwild:web, rsf-futures
  * keep off of public channels
* move the code from devbot into roobot [Adrian] 
  * (plugin name will need to change in gh-actions - if pushing master use x if dev use y) [Adrian]
* announce bot [Andi and Adrian]
* proceed to alpha testing

**Comment by deniseyu** [comment]
It looks like the core functionality here is done. I [updated Roo's readme](https://github.com/hyphacoop/matrix-roobot/commit/99e74ff184c7b2c9cf12c9793242d7fe1e34dc32) with a quick overview of this archiving functionality, to tick off the "write documentation" item above. I'm not sure that the allowlisting has been done but I also don't know how impactful it would be to do that right now, given that Roo generates minimal noise.

@benhylau @writerly03 this can probably be closed out, unless you spot anything else that needs doing!

**Comment by writerly03** [comment]
Allowlisting is establishing which rooms Roo can join? Fairly certain this has been done already. So yes, this can be closed off. We can open new tickets if we want to make feature changes to Roo
