### ISSUE TITLE
Consider how past employees maintain access to organizing-priv notes

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#513]
Hey all! Obviously very low priority, but just flagging early as people move in and out of Hypha.

I frequently used to look back on past private notes from when I was employed at Hypha (some informational interviews I did with contacts), and have just now realized that I've been removed from accessing the private repos, and therefore these notes. This makes sense, as I wouldn't expect access to private conversations after I'd left.

However, losing access to past resources feels unexpected, and it'd be great to have a plan for how past employees maintain access to material they co-created :)

Potential Mitigations: (mutually exclusive, hardest to easiest)
1. Take a snapshot of private docs and copy into Google Docs that are shared only with that person.
2. Version the organizing-priv by year, and allow past emloyees to maintain access to old repos.
3. Provide notice of removal of access, so that people can copy resources they wish to keep.

Thanks for considering! I'm in no urgent need of these notes, but might inventory the ones I'd like, and request copies in the future (if that's ok!).

Hope you're all well!

**Comment by benhylau** [comment]
If there are specific resources you need, pls let us know, and we can evaluate this case by case. But I don't think we'd make a general policy for this, as when notes are kept private, the counter-party expectation is that only current employees will maintain access. Anything else would've already been filed as public on https://meetings.hypha.coop/

**Comment by patcon** [comment]
Thanks! Make sense -- I've realized that I happen to **have an local copy** of the `hyphacoop-organizing-private` repo from Mar 18, 2021 (before I went inactive) so anything I'd want to refer back to would be there.

If my still having this local repo is an oversight, just say so and **I'm happy to discuss deleting it**. Might be worth mentioning any expectations around these repos in the [offboarding checklist template](https://github.com/hyphacoop/organizing-private/blob/main/.github/ISSUE_TEMPLATE/offboarding_template.md) 🔒 . (I see a checklist mentioned on the ["Offboarding" handbook page](https://handbook.hypha.coop/Infrastructure/offboarding.html), but can't read it as it's private.)

If you'd like, **feel free to send me the offboarding checklist** (patrick.c.connolly@gmail.com), and I'm happy to confirm that I've followed everything post-facto :)

Hope you're well, Ben!
