### ISSUE TITLE
Migrate organizing project board to new style

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/organizing#514]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

📅 Due date:  next GitHub working group
🎯 Success criteria: new board created and all issues moved over
🤝 Related to: [other issues or tickets]
🎟️ Re-ticketed from: [remove if not needed]
...

## To Do

Directions for moving -> https://docs.github.com/en/issues/planning-and-tracking-with-projects/creating-projects/migrating-from-projects-classic

**Comment by tripledoublev** [comment]
Here is the [new project board ](https://github.com/orgs/hyphacoop/projects/10/)
