### ISSUE TITLE
Directors sign Resolution 004

### ISSUE THREAD

**Issue by LexaMichaelides** [hyphacoop/organizing#523]
Resolution 004 is saved on a branch intended to push to #organizing.
- Approve bylaw amendments
- Add new directors
- Appoint new officers

I think the process now is for two of the existing directors to digitally sign by uploading a signature file and amending the resolution-004.md file to include a link to it, then we create a pr to #organizing main

https://github.com/hyphacoop/organizing/tree/resolution-004/resolutions

**Comment by YurkoWasHere** [comment]
> The following individuals are confirmed as directors of the Co-operative for a term of two years or until replaced:

I think we all stepped down as directors and then had a vote and all got re-appointed, so I think its that we all where appointed to director for a term of 2 years.

This also makes it easier by not having to prove the chain of how we got to where we are.  (2 added on this resolution 3 stepped down on this and then 5 appointed the following year)

**Comment by YurkoWasHere** [comment]
I think this resolution should be bumped to 005 and 004 back dated to 2022 to remove Dawn and Pat from the board of directors. Elon as added at this date. 

So we can do one where everyone steps down and the YJ BL UV and EL are appointed.

**Comment by YurkoWasHere** [comment]
Im wondering if resolutions should be in a branch and only merged when ready.  Since this repo is public it may confuse people who need access to this.

**Comment by benhylau** [comment]
The 2022 board meeting notes should be used to draft `004` and the 2023 one should be `005`.

To draft the 2022 resolution please refer to board meeting notes: https://github.com/hyphacoop/organizing-private/blob/main/meeting-notes/2022-09-20-board-of-directors-meeting.md

Here is AGM notes for context on items such as foreign membership: https://github.com/hyphacoop/organizing-private/blob/main/meeting-notes/2022-10-12-agm.md#c-foreign-membership

As for the signature process, I would strongly advocate transitioning to Dropbox Sign and deprecate the GPG key based signing process. The GPG process is not scalable as our board grows, and also difficult to explain to external folks who may need to refer to our internal documents (e.g. in KYC).

**Comment by benhylau** [comment]
Out for sigs 0753ff56f33077ecee513754bfb43c87f45ff8ec
