### ISSUE TITLE
Review past meeting notes for lost items

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#64]
## Shared Description

🗣 **Loomio:** https://loomio.hypha.coop/d/ZIbOUBsi/tool-talk-task-tracker

## To Do

- [ ] Deep dive through June meeting notes (where most were lost)
- [ ] Skim previous meeting notes
- [ ] Optional: skim chat

**Comment by benhylau** [comment]
@patcon can we close this? It seems you have submitted a bunch of old notes.

**Comment by patcon** [comment]
heh these were waaaaay old ones from even before github. but yeah, def good to close :)
