### ISSUE TITLE
Set up bank account

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#65]
- [x] Make decision on banking institution
- [x] incorporate organization
- [x] Open Desjardins bank account [Steps](https://www.desjardins.com/ca/business/accounts-cash-management/business-accounts/open-business-account/index.jsp)
  - [x] choose [a plan from offerings](https://www.desjardins.com/ca/business/accounts-cash-management/plans/index.jsp?navigMW=mm&)
    - community account for $2.95/mo
  - [x] Online form [form](https://accesd.affaires.mouv.desjardins.com/demande-ouverture-compte-entr/accueil),  [scrape of form](https://hackmd.io/xDRm_dgKS5ifa07Hf20Q-Q)
  - [x] Desjardins call Back
  - [x] ~~schedule bank meeting~~ Call Bank
  -  ~~Finalize everything by mail or at the caisse~~
 - [x] Call all signatories
 - [x] Receive E-Signatures and sign
 - [x] Become a Desjardins member

**Comment by patcon** [comment]
Thoughts:
- are we able to open bank account with just president and secretary?
  - this is for USA companies, but suggestion is [that only secretary need be there](https://smallbusiness.chron.com/banking-rules-non-profit-organizations-829.html)
  - Question: If so, is this blocked on https://github.com/hyphacoop/organizing/pull/113 ?
- Question: If banks in Canada have special process for non-profits, are we a non-profit?
  - As @benhylau and I clarified in Hema meeting, we are a non-profit under the _Income Tax Act_, though not structurally under the _Not-for-Profit Corporations Act_, and the former is prob what the bank cares about
  - potential \#todo, ask Matt@4pig their experience opening a bank account

**Comment by patcon** [comment]
Emailed Matt@4thPig for advice on any gotchas:

> Hopefully a quick question: As a non-profit co-operative, do you have any advice or recollections of how you handled first opening the bank account? (We're with Desjardins.)

**Comment by YurkoWasHere** [comment]
Call bank to complete personal interview to open the account

- [ ] @dcwalk 
- [ ] @patcon 
- [ ] @benhylau 


Number is 1-888-220-8082 
Select ENGLISH from the menu (i think its 9) 
OPEN AN ACCOUNT

May need PhotoID and SIN number handy

**Comment by benhylau** [comment]
Just registered, here are some notes:
- Each of us own 14% (1/7th) of hyphacoop is one number they need to put in
- Process takes about 30 min
- Give them a phone number where you can receive SMS because the password to digital sign the contract comes through that

**Comment by patcon** [comment]
Do they know we're nonprofit? Them talking about ownership feels odd. So nonprofit accounts are not what we're doing, and that was considered? https://www.desjardins.com/ca/business/types/community-humanitarian-organizations/index.jsp

**Comment by YurkoWasHere** [comment]
Account in processing of being finalized 
- We should receive the e-signature today (tomorrow at the latest?)
- We will receive an email - there will be  link - it will send an SMS to your phone to sign
- Once they receive all signatures.. it takes 24 hours to finish with the account

On phone i confirmed:
- Accounting currently setup for multi sig
- Confirmed community level account

Access Card - should we get it?
- You can only deposit with multisig not withdraw/pay.
- I told her we will decide at a later date

---
@patcon  re non-profit  - I did mention we where a non-profit and a co-op.  However it seems that there is a lot of "lost in translation" when dealing with Dejardins customer service.  I think it will be good to keep in mind that if there is an important point we want to make to either call multiple times to confirm with different people, or at least ask in a different way to reduce the possible miscommunication.


Also i noticed that Even though they have information available to them they don't by default look it up.  I was asked if it was a multi sig or no i was not sure so i asked her to look it up.  She did.... So why ask?!  this happens a few times

**Comment by patcon** [comment]
Comments from all hands:
- @YurkoWasHere: seem like we're in 24-hour window
  - account open with numbers (assumed)

**Comment by patcon** [comment]
:tada:
