### ISSUE TITLE
Join Canadian Worker Co-op Federation as a Regular (Worker Co-op) Member

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#67]
Based on the discussion and outcome from [this loomio thread](https://loomio.hypha.coop/p/zyfwtORd/join-canadian-worker-co-op-federation-as-regular-worker-co-op-members), the steps are:

- [x] Fill out (and sign) an application
- [x] Decide our description for website
- [x] Ask for approval to sign as group -> consensed on 2019-09-04 call to go ahead with @dcwalk as point of contact
- [x] Submit 2019-09-04 (in [gdrive](https://drive.google.com/file/d/1jZVRSia3h34vdJGdDa7g55bAZuOMTXwY/view?usp=sharing))
- [x] Confirm payment options and pay dues
- [x] Add calendar reminders for:
  - [x] Updating branding and website description
  - [x] Next year's payment
- [x] File expense reimbursement in https://link.hypha.coop/finances
- [x] Receive acknowledgement of application processed (after Sept 20)

**Comment by patcon** [comment]
Potential todos to add

- [ ] Add calendar reminder to next years payments
- [ ] create a recurring fees doc/spreadsheet, and add

**Comment by dcwalk** [comment]
Draft posted: https://drive.google.com/file/d/108E-P_bZGywGAmZMGyHhiq6igT9KVcsR/view?usp=sharing

**Comment by dcwalk** [comment]
Feels like we should have the Articles back before submitting: #78

**Comment by dcwalk** [comment]
Articles back, will take another look through on this

**Comment by dcwalk** [comment]
Submitted! I'll pay personally if possible and seek an expense reimbursement.

**Comment by dcwalk** [comment]
I've submitted dues to Hazel, but haven't received confirmation the funds were accepted. Will wait a moment before proceeding :woman_shrugging:

**Comment by patcon** [comment]
While calling about RFP submission status (https://github.com/hyphacoop/organizing/issues/115#issuecomment-533692053), kaye mentioned that we'd been approved, and she'd send email shortly 🎉

**Comment by dcwalk** [comment]
I'm marking this as closed for now, reminders added, expense reimbursement submitted/recieved
