### ISSUE TITLE
Initiate new project: Digital coaching for Primal Glow

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#71]
## Shared Description

🗣 **Loomio:** https://loomio.hypha.coop/d/dqZewfs6/new-project-proposal-digital-coaching-for-primal-glow

## To Do

- [x] ~~Create written proposal doc~~ `wont-do`
- [x] ~~Create contract~~ `wont-do`
- [x] ~~Review period for contract~~ `wont-do`
- [x] ~~Sign contract~~ `wont-do`
- [x] Create time-tracking client and project
- [x] Update prior tracked time
- [x] Confirm tracked time with primal glow
- [x] create invoice [custom in gdrive](https://drive.google.com/drive/folders/1q5mvrN6o3l4l24IeWOZxekJWfsDnzCFZ?usp=sharing) :lock: [quickbooks](https://c5.qbo.intuit.com/qbo5/v4/companies/9130347362711396/transactions/djQ6OTEzMDM0NzM2MjcxMTM5NjovdHJhbnNhY3Rpb25zL1RyYW5zYWN0aW9uOg:20.pdf?txnTypeId=4) :lock:
  - [x] send invoice
  - [x] send banking details (blocked on #65)
  - [x] collect on invoice
  - [x] update quickbooks
  - [x] generate new official quickbooks invoice for records
  - [x] explore quickbooks and understand what was done
- [x] ~~Create handbook guide for "starting a new project"~~ https://github.com/hyphacoop/handbook/pull/20

**Comment by benhylau** [comment]
> Create handbook guide for "starting a new project"

I did this https://github.com/hyphacoop/handbook/pull/20/

**Comment by patcon** [comment]
@benhylau do you have a rough invoice process you could share?

I'm thinking just using https://clockify.me/reports/detailed

And manually creating from https://invoice-generator.com/#/1 or something better?

**Comment by patcon** [comment]
- #todo solicit contracts to offer (in our gdrive from dcwalk. others?)
- yurko: could add terms in invoice
- udit: no contract needed if papertrail

**Comment by patcon** [comment]
sent banking details:

Related: https://github.com/hyphacoop/organizing-private/pull/2

**Comment by YurkoWasHere** [comment]
>  generate new official quick books invoice for records

don't think that's needed.....

**Comment by darkdrgn2k** [comment]
> .....

To clarify

I dont think we need to "issue" a new invoice.  The invoice in Quickbooks has been added for record keeping purposes, the invoice issued to the client was added as an attachment and a note made mapping Invoice # 001 to QB's 1002.

**Comment by patcon** [comment]
ok, thanks! in future, please try to be mindful of things that are related to another's client work. I was intending to handle this myself (and would have expected this was mine to do), as I was looking forward to creating an invoice and learning. please ask next time

**Comment by patcon** [comment]
Notes for myself (or other invoicers) for later:

Ok, inspired by some comments in the tech co-op show & tell call yesterday. Micky of Agaric Co-op said they were trying out an invoice format where unbilled time was included on the invoice, to give full picture. I tried this. (invoice linked in issue body above)

Also, played around with itemizing daily, but looked quite noisy, and can see how that could balloon and encourage client to pick apart each day's work. Insight isn't bad, but realized that without connection to the work done (which doesn't show on the invoice), showing each daily item might create bad experience, and encourage skepticism without offering insight that might validate the time used.

So in future, will be inclined to itemized as services over period of time (per week, per month). If someone wants to explore deeper, then that will be encouraged in the Clockify report we send them, which is more likely to have rich context.

**Comment by dcwalk** [comment]
Invoice sent and paid!
