### ISSUE TITLE
Create internal project manager role

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#73]
## Shared Description

🗣 **Loomio:** None.

## To Do

- [x] meet for preliminary discussion: [2019-06-21 meeting notes](https://github.com/hyphacoop/organizing/pull/58)
- [x] archive meeting notes
- Set high-level accountabilities for role
-  Write draft
-  Seek feedback on draft
-  Integrate feedback
-  Bring proposal to all-hands for acceptance
-  Appoint first role holder

**Comment by patcon** [comment]
Hey @garrying, does this feel like it belongs under scope of infra & ops working group label?

**Comment by benhylau** [comment]
This seems like a `General Manager` role? Language seems confusing, overlapping with per project management role.

**Comment by dcwalk** [comment]
Closing this in favour of #406  :)
