### ISSUE TITLE
Implement link shortener tool

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#74]
## Shared Description

🗣 **Loomio:** https://loomio.hypha.coop/d/btj3hpEO/what-do-we-have-need-brainstorm

## To Do

- [x] Migrate shortlink data from Google Drive to CSV: https://github.com/hyphacoop/shortlinks/pull/1
- [x] Add support for reading from raw CSV (not GSheet): https://github.com/hyphacoop/spreadsheet2shortlinks/issues/2
- [x] Point nightly "shortlink update" script from GSheet to GitHub CSV: https://github.com/hyphacoop/worker-coop-scripts/pull/4
- [x] Add mention of link shortener to handbook: https://github.com/hyphacoop/handbook/pull/11
  - [x] rebase branch from master to unblock
- [x] do final sync of [gsheet](https://docs.google.com/spreadsheets/d/1DpnzCpXWgQr66nFJFIlpa5XSBrt8IfZaLVZH0_q6kcA/edit#gid=0) to github csv. https://github.com/hyphacoop/shortlinks/commit/66440e43a9f93d6f70c7ca9f667096b0b4660605
- [x] add deprecation comment to gsheet
- [x] add note about forcing a run outside the nightly one https://github.com/hyphacoop/worker-coop-scripts/pull/5 https://github.com/hyphacoop/shortlinks/commit/fd438b7ef9c763753c8496cda9cf6c94c6050eb4
- [x] force a test run and validate working

**Comment by benhylau** [comment]
@benhylau approve PR
@patcon to add to handbook
