### ISSUE TITLE
Set up voicemail

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#75]
## Shared Description

🗣 **Loomio:** https://loomio.hypha.coop/d/WbpzjRho/transition-virtual-office-to-co-operative-name-and-identity/21

## To Do

- [x] record voicemail > "Hello you've reached Hypha Worker Co-operative, learning and building technologies together since 2019. Unfortunately we are unable to take your call right now, please leave a message and we'll get back to you within 2 working days."
- [ ] add info on voicemail to members handbook ->  https://github.com/hyphacoop/handbook/pull/18
  - accessing
  - changing greetings
  - where to look for info

**Comment by patcon** [comment]
Hey @dcwalk what else do you see as the todo's here? Off the top of my head, I can imagine:
- [ ] create guide for aspects of voicemail:
  - updating message?
  - checking messages?
  - configuring voicemail?
  - other?
- [ ] determine/define role/responsibility for checking and routing voicemail messages
- [ ] testing some aspects of it?

**Comment by YurkoWasHere** [comment]
```updating message```

# Record/Change Greeting
## Login to voice mail

### Remotly
Dial in number: 14164770355 
Account number: 14378876936
Password: in password respository

### Sip Client
Dial *98

## Voice mail greeting

Personal Options - 3
Greetings - 3
Personal Greeting 2 
To record personal greeting press 2

**Comment by YurkoWasHere** [comment]
- determine/define role/responsibility for checking and routing voicemail messages
- checking messages?
Messages come in the form of an email to members@hypha.coop

- configuring voicemail
Its done via website. See password store for more info

- testing some aspects of it?
We been getting spam calls.. so tests successfull?? :)

**Comment by patcon** [comment]
@dcwalk suggested that work in guide was not necessary for now

**Comment by dcwalk** [comment]
not exactly -- just that I'd strike a middle ground between @patcon  and @YurkoWasHere 's comments in adding to guide

**Comment by patcon** [comment]
Just called in! Yay! It sounds so _professional!_ You'd almost think we were a fully incorporated entity :)

**Comment by patcon** [comment]
@cwalk: almost done! -- infra meeting
