### ISSUE TITLE
Host discussion for values-based tool choices

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#76]
## Shared Description

🗣 **Loomio:** https://loomio.hypha.coop/d/edAOmTw8/values-at-play-in-tool-choices

## To Do

- [x] host kick-off conversation with infra wg to set initial expectations
- [ ] host followup with infra wg to discuss tools to navigate values tradeoffs
- [ ] develop proposal / draft approach
- [ ] discussion at all hands

**Comment by dcwalk** [comment]
Had an initial conversation at 2019-09-11 meeting, flow imagined to be: 1 more check in on infra, bring to all hands for approach / signoff.

Language from this other thing about where to consider values:

  - Talk about them!
    - Ask each other questions
    - Stand ups 
    - All the time!
  - Write them down!
    - Vision and Mission Statements
    - Priority Matrix-- what opportunities we're pursuing
      - Time-sensitive
    - Set of guides of rules of thumb
      - e.g. Deep adaptation: 
        - Resilience asks us  "how do we keep what we really want to keep?"
        - Relinquishment asks us "what do we need to let go of in order to not make matters words?"
        - Restoration asks us "what can we bring back to help us with the coming difficulties and tragedies?"
  - Reflect on them
    - Post-mortems

**Comment by patcon** [comment]
re: tools and closures/protections. [`#hyphacoop-public:tomesh.net` chat](https://matrix.to/#/!wvFLvXHaNrxWWwFOKj:tomesh.net/$15723606943138wbzRs:tomesh.net?via=tomesh.net&via=matrix.org&via=elon.li)

**Comment by patcon** [comment]
`2021-02-25` cleanup in ops: closing and will re-ticket as comes up.
