### ISSUE TITLE
Submit articles of incorporation

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#78]
## Shared Description

🗣 **Loomio:** https://loomio.hypha.coop/d/cPnZpext/articles-of-incorporation-submission

## To Do

See Loomio thread for details.

**Comment by dcwalk** [comment]
Just to make clear, progress and discussion on this is being tracked on loomio. Any updates to this issue will flow from the loomio thread linked above

**Comment by benhylau** [comment]
Resubmitted and waiting to hear back

**Comment by YurkoWasHere** [comment]
Certificate of Incorporation received.

**Comment by dcwalk** [comment]
We did this! We're done, I'm closing out of celebration :tada:
