### ISSUE TITLE
Launch initial website

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#80]
## Shared Description

🗣 **Loomio:** None.

## To Do

- [x] Do quick deploy of placeholder website
- [x] First pass at updates and deploy from GitHub https://github.com/hyphacoop/hypha.coop/pull/1
- [x] Second pass on splash page with look from ptich deck => https://github.com/hyphacoop/hypha.coop/pull/8

**Comment by dcwalk** [comment]
@garrying would you mark this as done now? Or is there a further step?

**Comment by garrying** [comment]
Marking as done
