### ISSUE TITLE
Create private archive (meetings notes, tasks, etc.)

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#81]
## Shared Description

:speaking_head: **Loomio:** N/A  
:date: **Due date:** N/A  
:dart: **Success criteria:** We have a place for private content that works for us all.  

## To Do

- [x] Discuss whether need for private space. `2019-10-30`
  - [x] decide :+1:
- [x] Discuss bounds of what might go there
- [x] Discuss what tool to use. `online`
  - [x] decide: GitHub private repo
- ~Ensure clear understanding amongst members~ not actionable
- [ ] Kickstart new private space
  - [x] create [`hyphacoop/organizing-priv`](https://github.com/hyphacoop/organizing-private) repo
  - [x] migrate private notes from hackmd
  - [ ] complete README (codify bounds of what goes in here)

**Comment by patcon** [comment]
This came up somewhere, potentially raised by @benhylau.

We need a longterm archive for storing private notes, which cannot be placed in `hyphacoop/organizing`. So far this includes our money conversations and Aether notes.

Two options have been raised:

### Option 1: Defer. Stay the course with HackMD
Keep leaving the notes in HackMD, and lock them down to collaborators after initial creation. [How To doc for "lock down"](https://hackmd.io/VN4ltoJJTwWSVdODqfBf2w).

### Option 1: Private GitHub repo
We couldn't host this in the github org. We couldn't add everyone, due to collab number limits. We can eventually get nonprofit status (https://github.com/hyphacoop/organizing/issues/68) and will be able to get unlimited private repos.

### Option 2: Private GitLab repo
This would be our first move to GitLab, another tool. Unlimited collaborators for private. Free. We could do it now.

**Comment by patcon** [comment]
- #todo tell ben about it or support
- #todo document somewhere (later)
- #todo move into handbook (later)

**Comment by patcon** [comment]
@patcon: perk of github: search would include pubnotes+provnotes+issues 🎉 -- infra meeting

**Comment by patcon** [comment]
We now have access to private repos via #68, if we want to use GitHub

**Comment by patcon** [comment]
Its been raised by @uditvira and @benhylau that tracking todos related to leads should be private by default. We could start storing them in this hypothetical private repo.

Not that issue titles wouldnneed to use abbreviations or codenames, as the project is public. (Code names became standard practice at myplanet, so we could communicate freely in all digital and IRL spaces, including talking about high-level of clients at events and coherently with non-privileged parties: e.g., "remember how we ran the scrums during the first phase of Big Red, and how disastrous it was?")

If on github, we could migrate easily between public/private as relationship solidifies. And this would happen only if those involved (and who know the client perspective) agree that it suits the situation: https://help.github.com/en/articles/transferring-an-issue-to-another-repository

**Comment by benhylau** [comment]
I don't want to use code names because of the nature of our projects, and it isn't a good way to hide more fine grained details. For example, one can often figure out from the details which org a codename represents. It unnecessarily adds a layer of indirection. I think codenames work for some types of orgs that have a lot of shared time and few big projects, but we are the opposite. Lots of small projects with little shared time. This may get confusing. I rather keep client details private via other means.

**Comment by patcon** [comment]
Sounds good to me! Projects can create them if they need them, with no need for any standard practice.

So am i understanding you that you are alright with: 1) tracking projects in github private repo with 2) no codenames, but 3) just don't mention client names in titles?

**Comment by patcon** [comment]
From [chat](https://matrix.to/#/!wvFLvXHaNrxWWwFOKj:tomesh.net/$15719352301041RkZcN:tomesh.net?via=tomesh.net&via=matrix.org&via=elon.li):

> are folks in favour of creating hyphacoop/organizing-private for private tasks and private notes?

@benhylau requested to move into non-chat discussion space.

- :heart: I feel like we should be careful to avoid fragmentation (ben)
- :heart: I feel like I don't want people confused about a public vs private task boards (ben)
- :mag: [our current task board](https://link.hypha.coop/tasks) is org-wide
  - :mag: our task board can have multiple repos
  - :mag: the tasks on our task board can be from public or private repos
  - :mag: Private issues are hidden on task board if user doesn't have access. [demo](https://github.com/hyphacoop/test-private/issues/1)
- :heart: I feel like we should have very clear/simple rule of thumb for what's public vs private before offering a private space
- :heart: I feel like we should use public tasks for everything unless a case could be made that it _should_ be privileged. (Not that we have to make the case each time, but that there's an articulated reason for choosing "private".)

**Comment by patcon** [comment]
At the last all hands, it came up to create this on GitHub as a private repo. Ben expressed support, and others agreed. No objections raised, to moving forward with Github private repo.

**Comment by dcwalk** [comment]
Discussed in 2020-01-29 gov / ops meetings, reviewed tasks and updated. One minor TODO of updating readme in repo

**Comment by patcon** [comment]
Closing this as its handled in https://github.com/hyphacoop/organizing-private/pull/28
