### ISSUE TITLE
Develop Retreat Playbook

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#9]
**✍️ RETREAT PLAYBOOK [WIP]: https://hackmd.io/pY2llFzrRDeO7TebdaauQQ?view**
TODOs:
- [x] @uditvira integrate summary of co-op requirements doc (#5): https://hackmd.io/s/SJwTqa767
- [x] @benhylau do another round of review
- [x] finalize facilitation details and plan (Wed Nov 28)
- [x] set up loomio for pre/mid retreat work (Wed Nov 28)

---

From Oct 31 meeting, we need a **Retreat Agenda** that will cover:

- length/amount of time,
- activities description,
  - values prioritization based on nesta toolkit
  - reflect and respond to prompts
  - freeform hangout
  - roadmapping activity (with list of legal reqs)
- session goals,
- any outputs (e.g, adopted mission)

It will likely also:
- Define pre-work
- Define post-work expectations

**Comment by dcwalk** [comment]
Parts of that work are happening here: https://hackmd.io/NBVk_Y8bR42x1mAfwPqKqg?view#

**Comment by benhylau** [comment]
Also here: https://hackmd.io/pY2llFzrRDeO7TebdaauQQ

**Comment by uditvira** [comment]
I think we already said this, but perhaps we should take Wednesday's time to merge elements of both these pads, by consensus, in to a single deliverable.

**Comment by benhylau** [comment]
Agree that with the one hour before all-hands, we'll merge this, and afterward I will transfer to a better format (e.g. GitBook or markdown-pdf) Whatever makes sense.

**Comment by benhylau** [comment]
We can decide best platform / timeline at tmr's call :)

**Comment by dcwalk** [comment]
We shipped it!
