### ISSUE TITLE
Add why's to Service Inventory

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#90]
Re-ticketed from https://github.com/hyphacoop/handbook/issues/12

## Shared Description

:speaking_head: **Loomio:** https://loomio.hypha.coop/d/btj3hpEO/what-do-we-have-need-brainstorm  
:date: **Due date:** N/A  
:dart: **Success criteria:** ...  

In `2019-07-10` all hands meeting, this came up. Suggestion from @dcwalk was to go through inventory and ask "why" we were using each tool, and write that in.

Screenshot of how EDGI does it:
![Screen Shot 2019-08-09 at 2 38 03 AM](https://user-images.githubusercontent.com/305339/62759261-c6fa0400-ba4e-11e9-858c-6681d59b1e28.png)

## To Do

- [x] share/link example of how EDGI did this. [:lock: link](https://paper.dropbox.com/doc/EDGI-Service-Inventory-Access-pTsHUVIb2JuFHo8KVfpq2)
- [ ] host discussion
  - [ ] for task-tracker (dc suggested good starter)
  - [ ] for the rest
- [ ] mention in handbook (if section exists yet)
- [ ] ...

**Comment by patcon** [comment]
@dcwalk brought this up as helpful for Odoo #96 at today's infra.

**Comment by dcwalk** [comment]
I'm closing this as won't do as it hasn't come up in the intervening time (and was opened off of a comment of mine). Let's reticket if this comes up again.
