### ISSUE TITLE
Inventory wider community communication spaces

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#91]
## Shared Description

:speaking_head: **Loomio:** https://loomio.hypha.coop/d/sWnNveKO/public-communication-spaces
:date: **Due date:** N/A  
:dart: **Success criteria:** ...  

## To Do

- [x] build list of spaces. [done.](https://loomio.hypha.coop/d/sWnNveKO/public-communication-spaces)
- [x] review/update with which ones we are in
- ~migrate into public resource~
  - option: Google Spreadsheet, to quickly get filtering/tagging. (e.g., "canada", "toronto", "tech", "worker co-op", "business development centres", etc.)
- [ ] add affiliations to handbook, link into resource => https://github.com/hyphacoop/handbook/pull/74

**Comment by dcwalk** [comment]
Not sure about migrating this to a public resource -- many of the links here are dead. I think we could list our affiliations in our handbook and then link into this loomio thread.

**Comment by dcwalk** [comment]
Made a PR with our affiliation, I think that is sufficient to close this out for now.

**Comment by dcwalk** [comment]
Okay, closing! We can re-open/revisit questions around this in new issues :tada:
