### ISSUE TITLE
Publish handbook

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#92]
## Shared Description

:speaking_head: **Loomio:** N/A  
:date: **Due date:** N/A  
:dart: **Success criteria:** We are publishing and sharing an organizational handbook in a way that suits us.

This was raised (by @dcwalk?) in `2019-05-27` and  `2019-06-05` all hands meetings. Research was set as next task.

Note: Not currently intended to include content changes beyond minimal.

## To Do

- [x] Research handbook toolchain -- @all https://github.com/hyphacoop/handbook/pull/1
- [x] Discuss in meeting
- [x] Decide on toolchain
- [x] Publish handbook https://github.com/hyphacoop/handbook/pull/17
- [x] link from gh repo metadata
- [x] update /handbook shortlink https://github.com/hyphacoop/shortlinks/pull/8
- [x] **stretch** create handbook.hypha.coop
  - [x] DNS record
  - [x] Update GitHub Pages with custom domain
    - [x] enabled HTTPS
- [x] **stretch** Link from our website https://github.com/hyphacoop/hypha.coop/pull/7
- [x] **stretch** Add [AMAZING construction notice](http://www.textfiles.com/underconstruction/) to handbook title page https://github.com/hyphacoop/handbook/pull/31

**Comment by patcon** [comment]
Added some other thoughts on steps to close, but open to rescoping.

**Comment by patcon** [comment]
Yo @dcwalk, is this effectively yours? (this was created during the migration from our meeting note #todos, but maybe got lost)

**Comment by dcwalk** [comment]
I guess...? I think we have this essentially covered by issues in the handbook repo: https://github.com/hyphacoop/handbook/pull/17 and https://github.com/hyphacoop/handbook/issues/1

**Comment by patcon** [comment]
Rejigged scope so that this is the largest scope. Thoughts on handbook.hypha.coop, and linking from website?

**Comment by benhylau** [comment]
I floated the name `h2o` before to be on theme but cool with `handbook` too :D

**Comment by dcwalk** [comment]
I think linking from the website eventually makes sense, but given that it is a placeholder I would not prioritize doing it rn.

Otherwise, handbook.hypha.coop is fine, but again, not urgent/critical to me

**Comment by patcon** [comment]
> I floated the name `h2o` before to be on theme but cool with `handbook` too

@benhylau Could create both (redirect + canonical). Then we can be both fun and pragmatic :)

how about handbook.hypha.coop canonical and h2o.hypha.coop redirect? (given the higher likelyhood of latter for typo/ambiguity in various fonts)

**Comment by benhylau** [comment]
I assume @dcwalk has preference for `handbook` so pls go ahead. I rather not have redundant links.

**Comment by patcon** [comment]
K, but in future, I'm highly in support of choices with personality. Redundancy is a non-issue for me

**Comment by dcwalk** [comment]
@ASoTNetworks -- are you able to set up a forwarder for us: `handbook.hypha.coop` -> `https://hyphacoop.github.io/handbook/`? We're adding a CNAME in https://github.com/hyphacoop/handbook/pull/30

**Comment by dcwalk** [comment]
DONE!
