### ISSUE TITLE
Create "virtual office" handbook page

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#93]
Re-ticketed from https://github.com/hyphacoop/handbook/pull/11

## Shared Description

:speaking_head: **Loomio:** N/A  
:date: **Due date:** N/A  
:dart: **Success criteria:**  Page exists in handbook

Mention:
- link shortener https://github.com/hyphacoop/handbook/pull/11
- service inventory https://github.com/hyphacoop/handbook/issues/12
- our "online spaces"

## To Do

- [x] draft initial doc which mentioned our virtual office -> https://github.com/hyphacoop/handbook/pull/18
- [x] get that merged!

**Comment by dcwalk** [comment]
This happened. Closing
