### ISSUE TITLE
Draft and sign IP assignment agreement

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#95]
## Shared Description

:speaking_head: **Loomio:** https://loomio.hypha.coop/d/nzcgMHev/employment-agreement-and-piaa  
:date: **Due date:** N/A  
:dart: **Success criteria:** Draft, approve, and have everyone sign the an Employment Agreement with PIAA  

## To Do

- [x] Draft document
  - [x] @dcwalk review
  - [x] @benhylau Merge/reject minor revisions for clarity 
  - [x] @patcon review
  - [x] @uditvira review
- [x] Approve document
  - [x] @hyphacoop/business-planning-wg review on March 19th
  - [x] @dcwalk review x2
  - [x] discuss and approve during allhands  
- [x] Update Appendix with Working Open Statement #280 
- [x] Sign document

**Comment by patcon** [comment]
- #todo split this issue? 👍 patcon, dcwalk

**Comment by benhylau** [comment]
Re-ticketed #133 and re-scoped this issue to just PIAA, but left Loomio thread as shared. @patcon already [had some discussion](https://community.coops.tech/t/how-do-you-do-employee-agreements-re-employee-vs-owner-classification/1610/3) and I think it confirms what we need here. We need to draft and sign a per member PIAA.

**Comment by benhylau** [comment]
I have received feedback from @uditvira and @YurkoWasHere in agreement with proposal on loomio. I will go ahead and draft our PIAA.

@dcwalk I'd also like to hear from you bc I am most uncertain about your other engagements and would want to make sure you don't have concerns about the proposed language.

**Comment by dcwalk** [comment]
I read through the PIAA's linked and they seem reasonable approaches -- left a comment in Loomio. I think the areas that I'd need think about more are the "What the Company doesn't own" section as well as "Contribution of your IP to Company projects" (or equivalent sections).

**Comment by dcwalk** [comment]
Oh, brainwave -- why don't we ask friends who have startups here in Toronto if they could share a copy of their PIAAs? I think I have one or two people I could email.

**Comment by patcon** [comment]
Good call. Asked a friend at Myplanet if shed be open to sharing her employment contract section dealing with this.

**Comment by patcon** [comment]
https://about.gitlab.com/blog/2017/12/18/balanced-piaa/

Note: I believe "PIAA" is just gitlab's internal acronym for their legal doc -- the github legal doc also has its own. And PIAA isn't listed in any acronym databases -- we're just talking "IP assignment contracts" :)

**Comment by patcon** [comment]
Heard back, re: local 80-100 person agency.

<img width="686" alt="screen_shot_2019-11-02_at_10 57 09_am" src="https://user-images.githubusercontent.com/305339/68073239-b1099000-fd6c-11e9-972e-3f0aa1f499d5.png">

> also possibly of use to you:
>
> _When I signed it I explicitly excluded my personal and volunteer work with the a statement along these lines:_
>
> Further to the Employment Agreement signed on MM/ DD/YYYY COMPANY acknowledges and agrees that "Intellectual Property" does not include work related to the following ongoing volunteer initiatives:
>
> - [list of volunteer projects I was a part of when I signed it]
>
> "Intellectual Property" also excludes: Self initiated projects that may be undertaken in the future for non-commercial, personal purposes, including, but not limited to:
> - [personal projects - I included things like design, art, writing, etc]
> - Hackathon projects
>
> This list may be expanded from time to time upon mutual agreement, provided that any new initiative is not in conflict or competition with COMPANY's business.

**Comment by benhylau** [comment]
PIAA usage is not specific to GitLab but it is also called other things in different organizations, and not standardized. It's usually signed with an Employment Agreement for new hires.

Traditional companies (including all tech startups I have come across) usually have IP assignments that heavily favour employers, as listed [here](https://github.com/github/balanced-employee-ip-agreement#how-does-beipa-differ-from-other-employee-ip-agreements). A lot of the language don't apply to us, for example:

- _Work rendered during regular working hours_: we don't have regular hours, and even if we do I wouldn't think we'd want that to be a defining feature of ownership (e.g. I take a call about another project between Hypha work)
- _With co-op resources_: which @dcwalk also flagged, I think we wouldn't mind using co-op resources to do other projects (e.g. using some Hypha hardware to do other projects)

The language is traditional IP assignment agreements will be default to company-own, unless explicitly consent to by a director. This creates huge logistical burden to our members who participate extensively in open source work and other engagements throughout the day. It means every time we do a patch to an open source project we'd have to get it listed and approved. Instead we should use language that assigns IP _only_ if it is within the scope of a Hypha project, defaulting to let member hold their own IPs otherwise, regardless of working hours or whose resources are being used.

While I agree that we can look at Canadian agreements for legal wording, we should _not_ use those as starting point because they apply to single-employer employment that are incompatible with our relationship with members.

**Comment by patcon** [comment]
Given that (1) the UK law doesn't seem to be big on this (see thread [ben linked](https://github.com/hyphacoop/organizing/issues/95#issuecomment-544200317)), and (2) private corps have different constraints... then it seems USA and Canada tech worker co-ops would be decent ppl to follow lead of, if anyone. Does that sound alright?

cc @freescholar @mlncn (members of @agaric, who run a [weekly international show & tell call](https://pad.drutopia.org/p/show-tell) from Boston). tl;dr - Do you have or know of any IP assignment agreements suited to the USA worker co-op ecosystem?

**Comment by dcwalk** [comment]
Comment from Nov 13: feels blocked, despite general agreement on way forward

**Comment by patcon** [comment]
Downgrading to priority one barring any concern from @benhylau 
(Flagging that might not be governance, but rather operations)

**Comment by benhylau** [comment]
Interesting difference between "contract _of_ service" vs. "contract _for_ service" [here](https://www.smartbiggar.ca/insights/publication/do-you-actually-own-the-ip-generated-by-your-canadian-employees-), the former is a condition for [Copyright Act 13 (3)](https://laws-lois.justice.gc.ca/eng/acts/C-42/page-4.html#h-102834).

This document should establish a "contract _of_ service" for employees, but I am not sure if it can apply to contractors or we need to sign a different document with them for the IP assignment to hold.

**Comment by benhylau** [comment]
@hyphacoop/member-workers there may be some follow-up discussion of who we expect to sign this:

- Members (yes of course)
- Contractors (I hope)
- Collaborator (maybe)
- Contracted organizations (not sure)

But the first draft is ready for review!
https://docs.google.com/document/d/1qWGdFAGNA37lSYEfWa31WGpuYO3nRzuKPnPnMlyPFrs/edit#

**Comment by dcwalk** [comment]
Reviewed, I wonder if you could clean up some of the mass deletions (esp, at the end?) just to make it easier to read/review for now. Left my thoughts

**Comment by patcon** [comment]
If you'd like everyone to actively sign-off (and ideally read), maybe add todo and assign issue to them so it shows up in notifications? Assigning myself in meantime so i can get to this later

### Suggested To Dos

- [ ] Sign-off on doc
  - [ ] @patcon 
  - [ ] @uditvira
  - [ ] @garrying 
  - [ ] @ASoTNetworks 
  - [ ] @YurkoWasHere 
  - [ ] @dcwalk 
  - [ ] @benhylau

**Comment by uditvira** [comment]
Updated the shared description to reflect tasks surfaced during March 12 BPWG meeting

**Comment by benhylau** [comment]
@uditvira I think the one question I have is:

I understand that employer-employee relationship is a "contract of service", whereas independent contractors are engaged in a "contract for service" relationship, and therefore Copyright Act 13 (3) does not hold.

1. Is there a scenario where a contractor is engaged in a "contract of service" relationship and there is an automatic transfer of IP & copyright?

2. If not, is the right step to sign an IP transfer agreement with the contractor?

**Comment by patcon** [comment]
> 1. s there a scenario where a **contractor is engaged in a "contract of service"** relationship and there is an automatic transfer of IP & copyright?

My reading is that no, contractors cannot be engaged in a "contract of service", because that's the definition of what an employee is -- mutually exclusive:

> "If there’s a **contract of service**, meaning the payer controls what type of work you do and how it should be done, you have an employer-employee relationship." [ref](https://turbotax.intuit.ca/tips/how-to-determine-if-you-are-an-employee-or-independent-contractor-6111)

2. And yes, signing seems right: My interpretation is that in relation to IP, it provides almost ALL the business's legal cover for contractors, and tops up its legal cover for employees.

**Comment by benhylau** [comment]
Good resource: [Employee vs Contractor: A Mini Guide for Canadian Small Businesses](https://blog.wagepoint.com/all-content/employees-or-contractor-mini-guide-canadian-small-businesses)

**Comment by benhylau** [comment]
I have updated the Agreement to add language for IP assignment to the Co-operative for people under _contract for service_, based on my understanding of:

- https://www.ballaghedward.ca/uploads/pub_uploads/intellectual-property-ownership-2-.pdf
    >In the absence of an employment relationship or written agreement to the contrary, the general rule is that the “author” will be the first owner of copyright.i This applies to independent contractors. Even after an independent contractor has been paid, a written assignment of copyright is usually required to transfer exclusive rights in the work to those who paid for its creation.ii Otherwise, the independent contractor retains title to the copyright and may sell copies of the work to other parties.

**Comment by benhylau** [comment]
The document is ready for review. I believe all open issues are handled in the current copy, and it is intended to handle any employment relationship (contract of/for service) that is of an individual person, domestic or foreign.

What this is _NOT_ intended for:
- an organization that we hire for service
- a employment contract for an employee or contractor (this is for IP only)

@dcwalk can you resolve the remaining issues. They should all be handled already but want to confirm them with you.

**Comment by dcwalk** [comment]
Reviewed and resolved most issues, a couple more for you to cycle back on. Very close

**Comment by benhylau** [comment]
I think it's DONE 🎆 
Will talk about this at All Hands and move on to signing.

**Comment by benhylau** [comment]
We'll try using HelloSign for this. Signers should **not** need an account.

**Comment by benhylau** [comment]
@patcon pls sign this, then this can finally close.

**Comment by patcon** [comment]
I'll leave the endorphin rush of closing to you 🙂

**Comment by benhylau** [comment]
Thanks all for signing. This will allow Hypha to sign IP agreements with clients when we enter new projects that require it. Signed PDF uploaded to our Drive.
