### ISSUE TITLE
Test Odoo

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#96]
## Shared Description

:speaking_head: **Loomio:** https://loomio.hypha.coop/d/eaH0FZNR/research-on-financial-software  
:date: **Due date:** N/A  
:dart: **Success criteria:** Have a throw-away instance we can pay with and know how to spin it up again  

## To Do

- [x] Deploy [Odoo Community](https://www.odoo.com/page/editions) to try it out (or use [coopdev's ansible](https://gitlab.com/coopdevs/odoo-provisioning) @ASoTNetworks 
- [ ] Does it work well for invoicing & tracking payments? @benhylau 
- [ ] Does it work well for bookkeeping? @benhylau 
- [ ] Other useful features? @benhylau

**Comment by YurkoWasHere** [comment]
Download odoo_12.0.latest_all.deb from website
(done under su as sudo was not configured on stock debian 9)

Vanilla install 

```
apt-get update # Update Repo
dpkg -i odoo_12.0.latest_all.deb # Install Odo
apt-get install -f # resolve dependencies
apt-get install python3-pip postgresql
pip3 install num2words
systemctl restart odoo
su - postgres
psql -U postgres postgres <<EOF
 CREATE USER odoo password 'DSFGHawtewf52d512s';
EOF
exit
```
connect to http://IP:8069
fill in form
takes a bit to load

Possible repo available [Source[(https://www.odoo.com/documentation/12.0/setup/install.html)
```
# wget -O - https://nightly.odoo.com/odoo.key | apt-key add -
# echo "deb http://nightly.odoo.com/12.0/nightly/deb/ ./" >> /etc/apt/sources.list.d/odoo.list
# apt-get update && apt-get install odoo
```

**Comment by patcon** [comment]
Created event to revisit accounting softare and try Odoo in first week of Aug 2020

**Comment by patcon** [comment]
@ASoTNetworks @benhylau Do we close and push to "Done" after the convo on the call, or do we want to repurpose it somehow?

(I've got it linked from the future gcal event, so we can re-open it when that comes up again.)
