### ISSUE TITLE
Submit "Initial Return" to Ministry of Government Services

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#99]
Re-ticketed from https://github.com/hyphacoop/organizing/issues/78

## Shared Description

:speaking_head: **Loomio:** https://loomio.hypha.coop/d/cPnZpext/articles-of-incorporation-submission  
:date: **Due date:** EoD Sunday, Sept. 29  
:dart: **Success criteria:** Form is completed and mailed.  

We must submit this within 60 days of date of incorporation, which according to cover letter is Aug 1st; so due by end of day Sunday, Sept 29th.

https://drive.google.com/drive/u/0/folders/17dEjx7Jd8b8vf3RnmzX2LMid-cfY-RIV

## To Do

- [x] Add deadline to calendar -- @patcon
- [x] Review "Important Notice" section from [received forms](https://drive.google.com/file/d/19r234IK86vKxDLMb7r3-3H4Q1857-AMi/view?usp=sharing)
- [x] Review [Form 1 - 07200E.pdf](https://docdrop.org/pdf/07200E-UDA0A.pdf/) (annotatable)
- [x] draft forms -- @patcon 
- [x] Determine requirements for officers. #discussion 
- [x] draft text of resolution for approval. [done. hackmd.](https://hackmd.io/O7uU0MRxSv-P5i1QUsvmFg)
- [x] decide on immediate signing process
- [x] Nominate officers for President & Secretary. WED SEP 18 [meeting](https://hackmd.io/@patcon/ryMxS3okB/https%3A%2F%2Fhackmd.io%2Fa4AQeoUyQdK9XAOKGCJ3Ww%3Fview?type=book) [PR#113](https://github.com/hyphacoop/organizing/pull/113)
- [x] Update forms. [done](https://drive.google.com/file/d/1NWkwv8mPwaKo2vm0RnW2XK2hnse6vCSB/view?usp=sharing) -- @patcon 
- [ ] Print & mail [form](https://drive.google.com/file/d/1NWkwv8mPwaKo2vm0RnW2XK2hnse6vCSB/view?usp=sharing). -- @YurkoWasHere 

EDIT: Migrated account setup todos into https://github.com/hyphacoop/organizing/issues/110 and https://github.com/hyphacoop/organizing/issues/111

**Comment by patcon** [comment]
Were you imagining this as a continuation of your task @dcwalk?

**Comment by patcon** [comment]
Reviewed and made notes here: https://loomio.hypha.coop/d/cPnZpext/articles-of-incorporation-submission/17

**Comment by patcon** [comment]
yurko: service ontario account also created?
also sign up with CRA HST registration?

**Comment by patcon** [comment]
@hyphacoop/finance-wg do I take it that these two docs mean we are all set up with HST numbers?
- [CRA: Business Number Letter](https://drive.google.com/file/d/1EgIOSN88Ew6QLYqbJ25xg0tLw-LD5DTj/view?usp=sharing)
- [CRA: Business Number Summary of Accounts](https://drive.google.com/file/d/1OuiF0ZO5xllIzY82ShpXqh4MbqOYvtNR/view?usp=sharing)

**Comment by patcon** [comment]
@YurkoWasHere I think you mentioned a Service Ontario online account, but I can't find it. Any advice?

**Comment by patcon** [comment]
![Screen Shot 2019-09-09 at 5 51 31 PM](https://user-images.githubusercontent.com/305339/64569129-8978e700-d32a-11e9-88c3-7cf4cb46b122.png)

Will try to resolve this CRA online issue tomorrow. Realized on return that "Patrick Connolly" instead of full "Patrick Cahill Connolly" was used on the articles, so hoping that's not a big deal.

**Comment by patcon** [comment]
Ok, got CRA online setup for _me_ only:

![Screen Shot 2019-09-10 at 3 28 29 PM](https://user-images.githubusercontent.com/305339/64644222-28abe600-d3e0-11e9-96c8-794fe32226b0.png)

The this to troubleshoot was that at least in theory this is self-serve by business owners, but we each need our SIN's attached to the _business_ account before we can connect that shared account individually to our _personal_ CRA account login.

So add updated my SIN in the business account profile via phone (and could do this for others as well), then connected it to my personal account via web (which only I could do).

So here are the full general instructions for adding a new CRA online business account user:

1. 💻 **Web:** (optional) Ensure that you have a _personal_ CRA account already created.
    - https://www.canada.ca/en/revenue-agency/services/e-services/e-services-individuals/account-individuals.html
1. 📞 **Phone:** This bit can be done **individually by each** business owner, or by one owner **on behalf** of others:
    1. Gather required information:
        - business number (BN)
        - business name
        - business address
        - business owner details (set of one or more name-SIN-birthdate combo for each)
    1. Call CRA at 1-800-959-5525. Press `wait > 1 > 2 > wait > 0`. (10-45 min wait. Shortest ~3-4pm.)
    1. Ask about "adding SIN to business account to allow personal account registration"
    1. Share the above info.
    1. Optional: While you have them on the line, run through next step (for your own account), if you'd like to be certain it worked.
1. 💻 **Web:** This part is done **individually** for each business owner:
    1. Log into your personal CRA account via http://www.cra-arc.gc.ca/mybusinessaccount
    1. Enter our BN.
    1. Our business account is now accessible from your personal CRA account!

**Comment by patcon** [comment]
Re: CRA business account:
- there appear to be at least two access levels: "business owners" and "clients" (each have separate logins)
- "business owners" only seems to include the people mentioned as "directors" in our articles
  - To confirm: _My Business Profile > Owner phone numbers_
- "clients" refers to "employees" (seemingly internal accountants), accounting firms, and representatives of accounting firms
- Any director can in theory add themselves without special authorization of others, though we could choose amongst ourselves not to connect them all to our personal accounts, to minimize risk.

Open questions: (for for Finance WG?)
- Who gets access to the CRA portal? All member-owners? All directors? Members of Finance WG (as "client" access, if needed)? Chair of finance WG, e.g. Treasurer (officer)?
  - What did other worker co-ops do?
  - What does our accountant recommend?
- Do we want to go paperless? (keeps asking)
- Should we audit CRA security options? #todo 
  - See: _My Business Profile > CRA security options_

**Comment by patcon** [comment]
ben suggested in chat that CRA and ServiceOntario accounts need not be bundled with this. I agree. Forking.

**Comment by patcon** [comment]
Ok, reading through our [Guide to the Ontario Co-op Act](https://drive.google.com/file/d/13HAEfMf5w3wTwMtsiPMXZp7Qnyz1jN4B/view?usp=drivesdk):

> ### What role do officers play?
> While the members are responsible for electing directors to the board of directors, the  board itself will **appoint “officers”** to carry out specific tasks.\* The membership does not elect  directors into particular positions. There are other rules about officers **specified by the Act:**
>
> 1. The board has two options for appointing officers – it **passes a resolution appointing them** or  it may elect them by secret ballot.
> 2. The Act requires that every co-operative board **must elect or appoint a president and a  secretary.**
> 3. The secretary does not need to be a director or even a member of the co-op. In some cases,  a co-op board will have the secretary function carried out by an employee of the co-op.
> 4. The directors must appoint a **president from among themselves**. The president must  therefore be a director. The co-op’s bylaws, or the board itself, may create other officer  positions. Two of the most common are treasurer and vice-chair/vice-president.
> 5. The chair of the board may be different from the president of the board, but these offices  are normally considered the same and are occupied by the same person unless specifically  separated by the co-op.
> 6. The bylaws or a board resolution should set out the duties of the officers.

*<sup> Apart from the president, officers may be appointed from any group of people, but they are generally members or  directors, or they possess a particular skill set that the officer position requires.</sup>

So one reading of this says:
- directors (yurko, dawn, Ben, patcon) appoint officers
- directors must hold board meeting to appoint (different than AGM) by resolution
- must have minimum of president and secretary
- president must be one of directors
- secretary can be anyone

Note: adding a treasurer later bears no fees, just resubmitting form. So we can defer that.

**Comment by patcon** [comment]
So **my proposal** is: we take the all hands to be a board meeting, and directors are present to appoint a president from amongst themselves, and a secretary from membership,and defer creation of other officers.

**Comment by benhylau** [comment]
I would say we can appoint also a treasurer since we are doing this process already. Done is better than defer and resubmit.

**Comment by dcwalk** [comment]
Agree with your interpretation @patcon  (my earlier comments about not needing all the roles was in reference to this).

 I would prefer deferring on treasurer if it hasn't been on our radar (which from what I can tell... it hasn't), as I assume once bylaws are codified (etc...) we'll go through another round and there will likely be an update to the officers.

**Comment by patcon** [comment]
Just to make things clear, I've tentatively pretended that (1) Ben is made Secretary, and (2) Yurko is made president, and filled out the form based on that: https://drive.google.com/file/d/1NWkwv8mPwaKo2vm0RnW2XK2hnse6vCSB/view?usp=sharing

Will be revised after real appointments on Wednesday. Someone will need to print pages 1-3 and mail them to:

> Ministry of Government and Consumer Services
> Central Production and Verification Services Branch
> 393 University Ave, Suite 200
> Toronto ON M5G 2M2

@YurkoWasHere, would it be alright if this printer/send was you?

**Comment by patcon** [comment]
Realized I'll need to do some legwork on drafting our first resolution. Anyone have any thoughts? I'm just leaning on this: https://coopcreator.ca/resource/sample-resolution/

This might be a good place to lean on GitHub and PR workflow?

**Comment by patcon** [comment]
Created a demo to show how we might choose to create and approve this resolution using digital signatures. If we want to go this route, I can also commit to documenting signing and verifying.

**Comment by patcon** [comment]
Held allhands standup and passed resolution for officers, unblocking this. [notes](https://hackmd.io/@patcon/ryMxS3okB/https%3A%2F%2Fhackmd.io%2Fa4AQeoUyQdK9XAOKGCJ3Ww%3Fview?type=book)

**Comment by YurkoWasHere** [comment]
C/O is `Dawn Walker` 

If we can keep this -  actually help identify what is meant for hypha at a quick glance as well

**Comment by patcon** [comment]
- updated c/o to DAWN WALKER cc @dcwalk 
- corrected officer appointment dates to 2019-09-18
- ensured proper officers
- saved as separate pages to maintain dynamic forms, since merging dup pages messes with pdf forms (all in gdrive)
- merged flattened single pages into flat single submission (3 pages)

@YurkoWasHere form available for mailing to above addresss: https://drive.google.com/file/d/1NWkwv8mPwaKo2vm0RnW2XK2hnse6vCSB/view?usp=sharing

**Comment by YurkoWasHere** [comment]
Printed/Enveloped/And mailed out of the mailbox in front of post office behind Lisgar park.
